### ISSUE TITLE
能不能新增excel模板导出？

### ISSUE THREAD

**Issue by Nokecy** [dotnetcore/Magicodes.IE#10]
类似 https://github.com/hanzhaoxin/ExcelReport

**Comment by xin-lai** [comment]
可以考虑，不过目前精力有限。
不过建议先可以试着自己实现下，提交PR。

**Comment by xin-lai** [comment]
兄台，我提供思路，你有兴趣来实现不？

**Comment by Nokecy** [comment]
@xin-lai  可以的~~~

**Comment by xin-lai** [comment]
@Nokecy 他这种模板的方式虽然直观，但是不太建议。
其实Excel、Word本质上是一个压缩包，里面由遵循Office open xml的xml等文件组成。因此我们可以根据以下思路来实现：

1. 基于Office制作基础模板
2. 解压模板（使用压缩工具）
3. 提取关键Sheet的xml，基于相关规则编写Razor模板
4. 生成相关的Sheet.xml到模板目录，然后压缩为扩展名为“.xlsx”的压缩包

完成这些之后，我们可以优化和简化整个流程

**Comment by riyuexing** [comment]
支持插入图片吗？

**Comment by xin-lai** [comment]
> 请问大神，模板导出时支持插入图片吗？

暂不支持，后续会支持

**Comment by xin-lai** [comment]
已完成
