### ISSUE TITLE
默认方式导出Excel只有前边十行有背景色，其他都没有背景色

### ISSUE THREAD

**Issue by netty2019** [dotnetcore/Magicodes.IE#100]
![2020-05-24_105206](https://user-images.githubusercontent.com/47128297/82744579-1bd3f480-9dad-11ea-90fd-4c672fd58d10.jpg)

如上图所示

**Comment by netty2019** [comment]
补一下我的代码
  public class ExcelExportHeaderLocalization: IExporterHeaderFilter
    {
        private  ILocalizationSource _localizationSource;

        public ExcelExportHeaderLocalization()
        {
            _localizationSource = LocalizationHelper.GetSource(JiqimaoConsts.LocalizationSourceName);
        }

        public ExporterHeaderInfo Filter(ExporterHeaderInfo exporterHeaderInfo)
        {
            exporterHeaderInfo.DisplayName = _localizationSource.GetString(exporterHeaderInfo.PropertyName);
            return exporterHeaderInfo;
        }
    }


    [AutoMapFrom(typeof(Product))]
    [Exporter(ExporterHeaderFilter = typeof(ExcelExportHeaderLocalization))]
    public class ExportProductDto
    {
	  public string Name { get; set; }
	  
	  public string Code { get; set; }
	  
	  public string Unit { get; set; }
	  
	  public decimal Price { get; set; }
	  
	  public string Status { get; set; }
	  
	  public string Description { get; set; }
	  
	  public Jiqimao.ProductCategories.ProductCategory ProductCategory { get; set; }
	  
	  public string CreatorUserName { get; set; }

      [ExporterHeader(Format = "yyyy/MM/dd HH:mm:ss")]
      public System.DateTime? CreationTime { get; set; }

      public string LastModifierUserName { get; set; }

      [ExporterHeader(Format = "yyyy/MM/dd HH:mm:ss")]
      public System.DateTime? LastModificationTime { get; set; }
    }
}


       /// <summary>
        /// 导出
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpGet]
        [AbpAuthorize(PermissionNames.Products_Export)]
        public async Task<FileContentResult> ExportAsync(PageProductDto input)
        {
            IQueryable<Product> query = CreateFilteredQuery(input);
            var dtoList = query.OrderBy(input.Sorting).AsNoTracking().Take(AppConsts.ExcelExportMaxRowCount).ToList().Select(MapToEntityExportDto).ToList();
            var fileBytes = await _excelExporter.ExportAsByteArray(dtoList);
            return new FileContentResult(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet)
            {
                FileDownloadName = L("Product") + ".xlsx"
            };
        }

**Comment by hueifeng** [comment]
@netty2019  The background color can be modified through this `ExporterAttribute TableStyle="None" `

**Comment by xin-lai** [comment]
@hueifeng 试试看新版本有这个问题不，感觉是一个Bug。

**Comment by hueifeng** [comment]
@xin-lai
No problem with the latest version
在新版本中没有问题

**Comment by hueifeng** [comment]
Fixed in early PR #86
