### ISSUE TITLE
CSV能否提供直接用Stream导入，这样就不用先保存文件再导入了

### ISSUE THREAD

**Issue by gudufy** [dotnetcore/Magicodes.IE#102]
我看了您的源码有这样的，只要多公开一个用stream导入的就行了吧？
using (var reader = new System.IO.StreamReader(FilePath))

**Comment by hueifeng** [comment]
@gudufy Agree

**Comment by gudufy** [comment]
> @gudufy Agree

谢谢

**Comment by gudufy** [comment]
这么快就改了呀，谢谢作者
