### ISSUE TITLE
数据导出的时候，支持Enum，bool类型 的转换成显示值?

### ISSUE THREAD

**Issue by crashsol** [dotnetcore/Magicodes.IE#106]
`public enum CustomerDetailLevel
    {
        [Description("小微客户")]
        Micro = 0,
        [Description("一级")]
        LevelOne = 1,
        [Description("二级")]
        LevelTwo = 2,
        [Description("三级")]
        LevelThree = 3,
        [Description("特级")]
        Special = 4,
    }
`
![image](https://user-images.githubusercontent.com/17925647/83720747-473bc680-a66c-11ea-9177-23b5dce369c8.png)
数据导出的时候，支持Enum，bool类型 的转换成显示值?

**Comment by xin-lai** [comment]
收到，由于最近太忙，在接下来的版本我们会进行处理。

**Comment by QHBZYJJC** [comment]
希望能不只是显示显示值，能不能也带下拉框，因为客户总有导出的数据编辑改改再导入的需求 😀

**Comment by xin-lai** [comment]
@QHBZYJJC 明白。目前这块主要是受限于EPPlus的API设计，修改EPPlus源码实现会更合适一点。我们一直有这个计划，奈何我和 @hueifeng 精力实在是不够，所以这块一直没有开始。

**Comment by hueifeng** [comment]
该需求已在2.4 beta1中处理，欢迎大家后续使用2.4版本通过如下代码实现需求：

```
[ValueMapping(text: "yes", true)]
[ValueMapping(text: "no", false)]
[ValueMapping(text: "小微客户", 0)]
```
