### ISSUE TITLE
用html模板导出excel没有实现

### ISSUE THREAD

**Issue by RuiyanLiu** [dotnetcore/Magicodes.IE#110]
![image](https://user-images.githubusercontent.com/16285387/84224040-1b0dc300-ab0e-11ea-8059-231c0e1b2a7f.png)

期望可以像PDF导出工资条一样，用html模板导出到excel

**Comment by hueifeng** [comment]
Thank you for your suggestion, we need to think about it.

**Comment by xin-lai** [comment]
个人感觉HTML导出Pdf更合适，导出Excel的话，感觉并不是很好处理，也没这个必要。

**Comment by RuiyanLiu** [comment]
这个地方只是看到有这个方法却没有实现，之前项目有这样的需求，所以就提出来了，如果不好处理就不管他吧，我用其它的方式实现了这个Excel的导出。
