### ISSUE TITLE
nuget找不到Magicodes.IE.Core的2.2.5版本，导致无法安装Magicodes.IE.Excel

### ISSUE THREAD

**Issue by dashenxian** [dotnetcore/Magicodes.IE#112]
![image](https://user-images.githubusercontent.com/18696614/84632478-8b0eb580-af21-11ea-8f38-ad4d2a38c676.png)
项目为.net framework web项目，项目比较老，混合有webform、mvc等，属性如下
![image](https://user-images.githubusercontent.com/18696614/84632685-d9bc4f80-af21-11ea-9b78-62e3cac8b030.png)

**Comment by hueifeng** [comment]
@dashenxian I didn't repeat the question.

**Install**

Installation can be done by following the command.

```
PM> Install-Package Magicodes.IE.Excel -Version 2.2.5
```

**Nuget**

You can view it at this address
https://www.nuget.org/packages/Magicodes.IE.Core/2.2.5?_src=template.

Please make sure that the original nuget address is https://api.nuget.org/v3/index.json.

The package is currently in a healthy state on the Nuget server.

**Comment by dashenxian** [comment]
vs2015只能看到2.1.4，但是vs2019可以看到2.2.5，同一个项目
![image](https://user-images.githubusercontent.com/18696614/84725014-30766780-afbc-11ea-9678-fe417e88039c.png)
vs2019：![image](https://user-images.githubusercontent.com/18696614/84725064-4f74f980-afbc-11ea-965b-454a40c653c0.png)
vs2015：![image](https://user-images.githubusercontent.com/18696614/84725080-5b60bb80-afbc-11ea-8bc8-7944c554cc04.png)
