### ISSUE TITLE
在Core 2.2 引用 Magicodes.IE.Html 时有包引用冲突

### ISSUE THREAD

**Issue by RuiyanLiu** [dotnetcore/Magicodes.IE#113]
![image](https://user-images.githubusercontent.com/16285387/84725128-79c6b700-afbc-11ea-8905-729a8e7f0389.png)

**Comment by RuiyanLiu** [comment]
Microsoft.AspNetCore.Razor.Language 中检测到版本冲突。直接安装/引用 Microsoft.AspNetCore.Razor.Language 3.1.4 到项目 BIMMP.WebApp.Mvc 可解决此问题。

**Comment by RuiyanLiu** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态	禁止显示状态
错误	NU1107	Microsoft.AspNetCore.Razor.Language 中检测到版本冲突。直接安装/引用 Microsoft.AspNetCore.Razor.Language 3.1.4 到项目 BIMMP.WebApp.Mvc 可解决此问题。 
 BIMMP.WebApp.Mvc -> Magicodes.IE.Html 2.2.5 -> Magicodes.RazorEngine.NetCore 1.0.0 -> Microsoft.AspNetCore.Razor.Language (>= 3.1.4) 
 BIMMP.WebApp.Mvc -> Microsoft.AspNetCore.App 2.2.0 -> Microsoft.AspNetCore.Razor.Language (>= 2.2.0 && < 2.3.0).	BIMMP.WebApp.Mvc	E:\Workspace\BIM管理平台\src\BIMMP.WebApp.Mvc\BIMMP.WebApp.Mvc.csproj	1

**Comment by hueifeng** [comment]
@RuiyanLiu  Can be local `Microsoft.AspNetCore.Razor.Language `upgrade to  3.1.4.

**Comment by RuiyanLiu** [comment]
Microsoft.AspNetCore.App 2.2.0 -> Microsoft.AspNetCore.Razor.Language (>= 2.2.0 && < 2.3.0).
直接升级后，SDK不兼容

**Comment by hueifeng** [comment]
@RuiyanLiu I released 2.2.6, which is a release that addresses this issue.

**Comment by RuiyanLiu** [comment]
Magicodes.IE.Html 2.2.6 -> Magicodes.RazorEngine.NetCore 1.0.0 -> Microsoft.AspNetCore.Razor.Language (>= 3.1.4) 
这个问题还是存在！看这个依赖关系是Magicodes.RazorEngine.NetCore这个依赖的Microsoft.AspNetCore.Razor.Language 包的问题

**Comment by RuiyanLiu** [comment]
![image](https://user-images.githubusercontent.com/16285387/84863286-4f055d00-b0a7-11ea-9b73-490ff3deab26.png)

**Comment by hueifeng** [comment]
@RuiyanLiu Thank you for issues, Sorry, I neglected to replace it.I will release version 2.2.7 as a replacement.

**Comment by RuiyanLiu** [comment]
问题已解决，谢谢
