### ISSUE TITLE
找不到方法:System.String Magicodes.ExporterAndImporter.Core.Extension.Extension.Save(System.Drawing.Image, System.String, System.Drawing.Imaging.ImageFormat)

### ISSUE THREAD

**Issue by dashenxian** [dotnetcore/Magicodes.IE#114]
版本：Magicodes.IE.Excel 2.1.4，
.net版本：.net frameword 4.7.1
调用代码：
await new Magicodes.ExporterAndImporter.Excel.ExcelImporter().importer.Import<T>(fullpath);

错误详细信息：
引发的异常:“System.MissingMethodException”(位于 Magicodes.ExporterAndImporter.Excel.dll 中)

其他信息: 找不到方法:“System.String Magicodes.ExporterAndImporter.Core.Extension.Extension.Save(System.Drawing.Image, System.String, System.Drawing.Imaging.ImageFormat)”。

错误截图
![image](https://user-images.githubusercontent.com/18696614/84729801-2d34a900-afc7-11ea-9970-3a9573b4136b.png)

**Comment by hueifeng** [comment]
@dashenxian #75 #64 You can upgrade to new version.

**Comment by dashenxian** [comment]
我无法升级到新版本，请见https://github.com/dotnetcore/Magicodes.IE/issues/112，是否有其他办法？

**Comment by hueifeng** [comment]
@dashenxian It is possible to upgrade to the 2.2.0 preview, where this issue was also resolved.

**Comment by dashenxian** [comment]
我升到了2.2.0beta5但是又遇到了https://github.com/dotnetcore/Magicodes.IE/issues/68
因为我在vs2015上最高只能看到2.2.0beta5，#68需要升到2.2.0beta6
![image](https://user-images.githubusercontent.com/18696614/84737394-6cb8c080-afda-11ea-9041-0a0368b85596.png)
这一路真是坎坷啊
