### ISSUE TITLE
The type initializer for 'Gdip' threw an exception.

### ISSUE THREAD

**Issue by AjuPrince** [dotnetcore/Magicodes.IE#115]
系统部署到Linux Centos 8 中 使用导入和导出 Excel 功能
报错，错误信息：The type initializer for 'Gdip' threw an exception.
有遇到的吗？如何解决的

**Comment by hueifeng** [comment]
@AjuPrince You can solve this problem by installing libgdiplus.

**Comment by AjuPrince** [comment]
thank you .
