### ISSUE TITLE
从excel导入数据，不识别日期格式

### ISSUE THREAD

**Issue by dashenxian** [dotnetcore/Magicodes.IE#116]
vs2015创建的项目任何版本（已经测试从2.1.4-2.2.6）都会出现日期格式识别不了，和这个问题一样https://github.com/dotnetcore/Magicodes.IE/issues/68
vs2019无此问题
并且vs2015在nuget界面的Magicodes.IE.Core最高版本只显示到2.2.0beta5，强制修改package文件中的版本可以更行到2.2.6，用nuget命令行工具最高也只能更行到2.2.0beta5，vs2019正常

**Comment by hueifeng** [comment]
I learned from the Nuget team that it is because of SemVer package dependency issues. https://github.com/NuGet/Home/issues/9739

**Comment by dashenxian** [comment]
那怎么办呢，你们会修改引用支持vs2015吗？因为我们的项目最高只能使用vs2015，所以可能无法升级vs

**Comment by hueifeng** [comment]
@dashenxian Thank you for issues, We dealt with this issue in 2.3.0-bate2.
