### ISSUE TITLE
我该怎么自定义 sheetName

### ISSUE THREAD

**Issue by OxOld** [dotnetcore/Magicodes.IE#123]
比如  如果 我使用 ExcelExporter Name 来定义的名称的话。那么 我有一个需求 导出各班的学生。班级 名称是 动态的 我也不知道 有多少个班级

**Comment by hueifeng** [comment]
I want to export dynamically the following way:

``` csharp
var result = exporter.Append(list1).SeparateBySheet().Append(list2).ExportAppendData(filePath);
```

But the dynamic name has not yet implemented this function.

**Comment by OxOld** [comment]
![image](https://user-images.githubusercontent.com/49990116/86311868-ea740180-bc53-11ea-99d3-4b9f09ca6ff7.png)
大概的效果是这样的  他们的 Dto 也是同一个  只是名称不一样而已

**Comment by hueifeng** [comment]
@OxOld At present, it is possible to realize multi-sheet additional export in the chain programming mode through the above code snippet, but regarding the custom name, this function has not yet been implemented, and I think this function is very great. I think we can implement a custom sheet name

**Comment by OxOld** [comment]
谢谢
