### ISSUE TITLE
怎样将某列设为excel里的“文本”格式？

### ISSUE THREAD

**Issue by gudufy** [dotnetcore/Magicodes.IE#126]
船期一般都是：2/4/6，这种格式，导入时会自动变成2002/4/6，如果把列设成excel里的“文本”格式就正常了。
DTO里是string类型

**Comment by hueifeng** [comment]
@gudufy You can refer to the following code snippet.
```
[ExporterHeader(DisplayName = "Text",Format = "@")]
public string Text { get; set; }
```

**Comment by gudufy** [comment]
> @gudufy You can refer to the following code snippet.
> 
> ```
> [ExporterHeader(DisplayName = "Text",Format = "@")]
> public string Text { get; set; }
> ```

谢谢，我试了导出没问题了。但是导出模板还是一样的问题，
`public async Task<IActionResult> ExportCsvTemplate()
        {
            IImporter importer = new ExcelImporter();

            var template = await importer.GenerateTemplateBytes<ImportFreightDto>();

            return File(template, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "FreightfeeImportTemplate.xlsx");
        }`
