### ISSUE TITLE
属性是class 的字段怎么设置特性呢？

### ISSUE THREAD

**Issue by wulienen** [dotnetcore/Magicodes.IE#127]
![daima](https://user-images.githubusercontent.com/26619474/87623787-c71f7b00-c758-11ea-8a54-b1a2ea0616f1.png)

**Comment by hueifeng** [comment]
class字段不可以，如果说如上这个需求满足的情况下，那么最终达到的效果是什么？以什么方式输出到excel？怎么展示，这一块我不是很明白。

**Comment by serfend** [comment]
他的意思可能是在 `Quantity` 属性无标记的时候，能直接用 类`QuantityDto`的标记

**Comment by xin-lai** [comment]
仅模板导出支持类的对象。
如果没有补充，那就先关闭掉了。
