### ISSUE TITLE
怎么样设置单元格的宽度的。

### ISSUE THREAD

**Issue by qcjxberin** [dotnetcore/Magicodes.IE#129]
怎么样设置单元格的宽度的。因为现在有时间字段导出因宽度问题变为#了。请问有什么办法控制这个宽度。

**Comment by hueifeng** [comment]
其实可以通过如下方式对宽度做处理，但是目前只是对图片做了宽度设置，可以在`ExporterHeaderAttribute`中添加width

```
ExcelColumn.Width 
```

**Comment by qcjxberin** [comment]
建议下一版本能支持这个功能。

**Comment by hueifeng** [comment]
非常感谢您的反馈，目前该功能已在2.4 beta1中发布 [href](https://github.com/dotnetcore/Magicodes.IE/blob/81be5b4c52d3aef262645070584e3c068acdc31b/src/Magicodes.ExporterAndImporter.Tests/Models/Export/ExportTestDataWithAttrs.cs#L65) 。
