### ISSUE TITLE
Cannot Export Pdf  "COM Interop is not supported on this platform."

### ISSUE THREAD

**Issue by godzff** [dotnetcore/Magicodes.IE#130]
Use Magicodes.IE.Pdf in macos (10.15.16) environment to export pdf and report errors

1.Install-Package Magicodes.IE.Pdf

2.Create Dto

3.Show Code
`public async Task<IActionResult> ExportReceipt()
        {
            var exporter = new PdfExporter();
            var result = await exporter.ExportListByTemplate(Path.Combine("wwwroot", "test.pdf"), new List<ReceiptInfo>()
            {
                 new ReceiptInfo
                    {
                        Name = "MR.A"
                    },
                    new ReceiptInfo
                    {
                        Name = "MR.B"
                    },
                    new ReceiptInfo
                    {
                        Name = "MR.C"
                    }
            });
            return File("test.pdf", "application/pdf", result.FileName);
        }`

4.Run Demo and Throw an exception

An unhandled exception occurred while processing the request.
TemplateCompilationException: Errors while compiling a Template.
Please try the following to solve the situation:
* If the problem is about missing/invalid references or multiple defines either try to load
the missing references manually (in the compiling appdomain!) or
Specify your references manually by providing your own IReferenceResolver implementation.
See https://antaris.github.io/RazorEngine/ReferenceResolver.html for details.
Currently all references have to be available as files!
* If you get 'class' does not contain a definition for 'member':
try another modelType (for example 'null' to make the model dynamic).
NOTE: You CANNOT use typeof(dynamic) to make the model dynamic!
Or try to use static instead of anonymous/dynamic types.
More details about the error:
- error: (0, 0) Unexpected error writing debug information -- 'COM Interop is not supported on this platform.'

What can I do now？Thanks

**Comment by hueifeng** [comment]
The following code can be executed:

```
PM> Install-Package Magicodes.IE.Pdf -Version 2.3.0-beta4
```

**Comment by godzff** [comment]
I tried 2.3.0-beta4 and 3.0.0-beta1, still the same error @hueifeng

**Comment by hueifeng** [comment]
Sorry, I failed to reproduce this error in MacOS.

**Comment by hueifeng** [comment]
@godzff This problem has been resolved in `2.3.0-beta5`.

```
PM> Install-Package Magicodes.IE.Pdf -Version 2.3.0-beta5
```

**Comment by godzff** [comment]
@hueifeng Thank you very much, I can export normally after updating to this version

**Comment by hueifeng** [comment]
Thanks for verifying @godzff
