### ISSUE TITLE
使用模板导出图片的时候,直接显示图片路径,而不是图片

### ISSUE THREAD

**Issue by kugarliyifan** [dotnetcore/Magicodes.IE#131]
使用模板导出的方式,,导出后的图片列,直接显示网址或者本地文件路径,无法输出成图片信息.
模板文件:  [报价格式.xlsx](https://github.com/dotnetcore/Magicodes.IE/files/4977648/default.xlsx)

导出后的文件:
[采购单导出20200726 (14).xlsx](https://github.com/dotnetcore/Magicodes.IE/files/4977649/20200726.14.xlsx)

**Comment by hueifeng** [comment]
可以参考如下内容：
```
  {{Company}}  //单元格渲染
  {{Table>>BookInfos|RowNo}} //表格渲染开始语法
  {{Remark|>>Table}}//表格渲染结束语法
  {{Image::ImageUrl?Width=50&Height=120&Alt=404}} //图片渲染
  {{Image::ImageUrl?w=50&h=120&Alt=404}} //图片渲染
  {{Image::ImageUrl?Alt=404}} //图片渲染
```

**Comment by kugarliyifan** [comment]
但是高度变得很奇怪,结果是这样的:
[采购单导出20200726 (17).xlsx](https://github.com/dotnetcore/Magicodes.IE/files/4977688/20200726.17.xlsx)

**Comment by xin-lai** [comment]
> 但是高度变得很奇怪,结果是这样的:
> [采购单导出20200726 (17).xlsx](https://github.com/dotnetcore/Magicodes.IE/files/4977688/20200726.17.xlsx)

模板麻烦提供下。

**Comment by kugarliyifan** [comment]
[报价格式.xlsx](https://github.com/dotnetcore/Magicodes.IE/files/4979799/default.xlsx)
这是模板

**Comment by kugarliyifan** [comment]
[ExcelExporter(Name = "sheet1")]
        public class aaa
        {

            public List<ShopCartExcelDTO> List { set; get; }
        }

        [ExcelExporter(ExporterHeaderFilter = typeof(ShopCartExcelDTOHeaderFilter))]
        public class ShopCartExcelDTO
        {
            [ExportImageField()]
            [ExporterHeader("图片")]
            public string ImageUrl { set; get; }

            [ExporterHeader("数量")]
            public int Qty { set; get; }

            [ExporterHeader("价格")]
            public decimal Price { set; get; }

            [ExporterHeader("总额")]
            public decimal TotalPrice => Qty * Price;

            [ExporterHeader()]
            public string Package { set; get; }

            [ExporterHeader()]
            public decimal Size { set; get; }

            public DTO_Product Product { set; get; }



        }  这个是实体

**Comment by xin-lai** [comment]
![image](https://user-images.githubusercontent.com/22255486/88500699-0329ca00-cffc-11ea-9ba0-e84f134bde2f.png)
加下高度的语法，控制下高度。
{{Image::ImageUrl?Width=50&Height=120&Alt=404}}
比如上述语法，Width是控制图片宽度，Height用于控制图片高度，Alt则用于当图片不存在时显示文字

**Comment by kugarliyifan** [comment]
加了,还是一样
模板:   
[报价格式.xlsx](https://github.com/dotnetcore/Magicodes.IE/files/4980291/default.xlsx)

导出后:
[采购单导出20200727 (2).xlsx](https://github.com/dotnetcore/Magicodes.IE/files/4980292/20200727.2.xlsx)

**Comment by kugarliyifan** [comment]
[ExcelExporter(ExporterHeaderFilter = typeof(ShopCartExcelDTOHeaderFilter))]
        public class ShopCartExcelDTO
        {
            [ExportImageField(Width = 200,Height = 120)]
            [ExporterHeader("图片")]
            public string ImageUrl { set; get; }

            [ExporterHeader("数量")]
            public int Qty { set; get; }

            [ExporterHeader("价格")]
            public decimal Price { set; get; }

            [ExporterHeader("总额")]
            public decimal TotalPrice => Qty * Price;

            [ExporterHeader()]
            public string Package { set; get; }

            [ExporterHeader()]
            public decimal Size { set; get; }

            public DTO_Product Product { set; get; }



        }

**Comment by xin-lai** [comment]
![QQ图片20200729140323](https://user-images.githubusercontent.com/22255486/88762730-53439080-d1a4-11ea-88f2-4020f7598d78.png)

**Comment by kugarliyifan** [comment]
我试了一下,,弄了个最简单的代码:
[ConsoleApp1.zip](https://github.com/dotnetcore/Magicodes.IE/files/4993361/ConsoleApp1.zip)  
里面的template.xlsx 是一个最简单的模板

**Comment by xin-lai** [comment]
试试使用beta版本的包。

**Comment by kugarliyifan** [comment]
我发现问题是出在 TemplateExportHelper.RenderRowsHeight  函数里了
sheet.Row(rowIndex).Height =pic.Image.Height;   这时候读取的是pic.Image.Height,,,读取的是原图片的高度,才会导致后面有一堆的空白,,,而且这个高度是pixel的,,,跟excel使用的单位还不一样,,需要加一个换算,要不然也会多少有一小段的空白

**Comment by xin-lai** [comment]
明白了，我一直以为你说的是图片高度不对。

**Comment by kugarliyifan** [comment]
> 明白了，我一直以为你说的是图片高度不对。

.......................额....好吧,,我没说清楚,,不过这个能怎么处理?

**Comment by xin-lai** [comment]
@kugarliyifan 能否PR，最近比较忙。

**Comment by kugarliyifan** [comment]
> @kugarliyifan 能否PR，最近比较忙。

哦,,可以,,我周末研究一下,,看看怎么修复
