### ISSUE TITLE
excel添加对ExpandoObject类型的支持

### ISSUE THREAD

**Issue by sgalcheung** [dotnetcore/Magicodes.IE#135]
**Describe the bug**
I want to export the list dynamically

**Expected behavior**
Dynamically export the list users want

**Screenshots**
![image](https://user-images.githubusercontent.com/42566429/89501597-2cb1d500-d7f6-11ea-9ff2-9b1d74f0e52e.png)
![image](https://user-images.githubusercontent.com/42566429/89501671-51a64800-d7f6-11ea-9622-e02361dfb884.png)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Version [2.2.7]

**Comment by xin-lai** [comment]
2020.08.16

【Nuget】版本更新到2.3.0-beta7
excel添加对ExpandoObject类型的支持 #135**
