### ISSUE TITLE
asp.net core 3.1 项目引入 2.2.7版本并发布到IIS托管后, 导出PDF引发空引用错误

### ISSUE THREAD

**Issue by thinkif** [dotnetcore/Magicodes.IE#139]
asp.net core 3.1 项目引入 2.2.7版本并发布到IIS托管后, 导出PDF时引发空引用错误
此错误与 https://github.com/dotnetcore/Magicodes.IE/issues/105 一样, 不知道 这个issue是如何解决的

经过好几天的测试, 目前发现临时的解决方案:
引入nuget 上的 RazorEngine.NetCore ( https://www.nuget.org/packages/RazorEngine.NetCore/ ), 而不是使用本项目内的 RazorEngine.NetCore  

如果部署后nuget上的RazorEngine.NetCore的dll未出现在目标目录中, 则手动覆盖

这只是临时解决的方法, 希望能引入 https://www.nuget.org/packages/RazorEngine.NetCore 
或者有其他有效的解决方案

再次感谢作者提供这个很赞的项目

**Comment by thinkif** [comment]
你好, 我重新读了本项目内置的 Magicodes.RazorEngine.NetCore 项目的源码( https://www.nuget.org/packages/Magicodes.RazorEngine.NetCore/ ) 发现你已经修复了这个问题, 但是在nuget上却没能加载这个新版本, 后来发现需要使用 2.3.0-beta7 , 在这个版本中使用了已经修复过的 Magicodes.RazorEngine.NetCore 

经过测试, 这个版本是可行的

感谢

**Comment by hueifeng** [comment]
2.3.0-beta7 should solve this problem, can you try it?

**Comment by hueifeng** [comment]
@thinkif   Ok, Thanks for your verification.

**Comment by thinkif** [comment]
是的, 在使用了 2.3.0-beta7 后问题解决了

因为预览版的最大版本号是 3.0.0-beta1 , 而正式版 2.2.7 所以正常使用正式版或最新预览版都加载不到 Magicodes.RazorEngine.NetCore 2.2
所以忽略掉了2.3.0-beta7
