### ISSUE TITLE
excel模板生成下载，身份证号这种长数字会默认使用科学计数法

### ISSUE THREAD

**Issue by IdaDawn** [dotnetcore/Magicodes.IE#140]
我通过模板生成Excel，身份证号如何设置成文本类型呢。要不身份证号码会是科学计数法，在导入的时候就会出现问题

**Comment by xin-lai** [comment]
收到，我们试一下。

**Comment by xin-lai** [comment]
试试：
`[ExporterHeader(DisplayName = "Text",Format = "@")]`
参考 #126

**Comment by IdaDawn** [comment]
收到，谢谢
