### ISSUE TITLE
io读取excel出现异常

### ISSUE THREAD

**Issue by sgalcheung** [dotnetcore/Magicodes.IE#141]
**Describe the bug**
从stream流读取excel时，对dto中必填字段放空，出现空指针异常

**To Reproduce**

![image](https://user-images.githubusercontent.com/42566429/90880006-5a903f80-e3da-11ea-8b4e-23eec7e9fee2.png)
![image](https://user-images.githubusercontent.com/42566429/90880024-60862080-e3da-11ea-9f95-30476a524864.png)

**Expected behavior**
正常处理对必填字段校验

**Additional context**
Magicodes.IE.Excelv2.2.7

**Comment by xin-lai** [comment]
2020.08.22

【Nuget】版本更新到2.3.0-beta8
修复基于文件流导入时的NULL异常，并完善单元测试 #141**
