### ISSUE TITLE
模板导出图片单元格大小的问题{{Image::PartImg?w=60&h=60}}

### ISSUE THREAD

**Issue by 1542793315** [dotnetcore/Magicodes.IE#142]
{{Image::PartImg?w=60&h=60}} 
使用上面这个模板公式会导致导出来的excel文件行高不确定，有的正常 有的很大[

**Comment by 1542793315** [comment]
![image](https://user-images.githubusercontent.com/48785885/91142327-2fac3100-e6e3-11ea-855e-7b528c774ee6.png)
![image](https://user-images.githubusercontent.com/48785885/91142352-38046c00-e6e3-11ea-899d-4966071207c1.png)

**Comment by hueifeng** [comment]
@1542793315 未能复现该问题，麻烦使用新版本帮忙验证，或者提供相应的demo。
