### ISSUE TITLE
导出带图片数据。图片走位。

### ISSUE THREAD

**Issue by yaobo-lab** [dotnetcore/Magicodes.IE#143]
封面这一列没有对yj齐

![image](https://user-images.githubusercontent.com/21329253/91394258-0ddeb580-e86d-11ea-9a0a-7ef5ac389eff.png)

**Comment by xin-lai** [comment]
最近在出差，抱歉了。最好提供下示例程序，如果可以的话，可以考虑PR单元测试示例，这样方便我们直接调测。

**Comment by yaobo-lab** [comment]
> 最近在出差，抱歉了。最好提供下示例程序，如果可以的话，可以考虑PR单元测试示例，这样方便我们直接调测。

OK.我试试。

**Comment by xin-lai** [comment]
麻烦PR到开发分支，Develop。

**Comment by hueifeng** [comment]
该问题已在2.4-beta版本更新，可以更新到beta版本或者等正式版本进行验证
