### ISSUE TITLE
模板导出带图片的时候没有处理模板中多行合并

### ISSUE THREAD

**Issue by RuiyanLiu** [dotnetcore/Magicodes.IE#147]
模板导出带图片的时候没有处理模板中多行合并的情况，目前的情况是只把第一行的高度给设置了！还有最新的版本又不支持core2.2 了
![image](https://user-images.githubusercontent.com/16285387/92580001-793e7380-f2c0-11ea-948b-d4b7465a98b2.png)

**Comment by hueifeng** [comment]
确实，`Magicodes.EPPlus`在`netstandard2.0`中引用的版本库存在差异。

**Comment by hueifeng** [comment]
> 模板导出带图片的时候没有处理模板中多行合并的情况，目前的情况是只把第一行的高度给设置了！
该问题不明确，建议补充详细问题描述，最好的情况是再向我们提供相应的demo
