### ISSUE TITLE
DataTable导出没有列名，这段代码将DataTable的属性与传入的DataTable列名比较导到获取不到列名

### ISSUE THREAD

**Issue by anlem12** [dotnetcore/Magicodes.IE#15]
DataTable导出没有列名，这段代码将DataTable的属性与传入的DataTable数据列名比较导到获取不到列名

https://github.com/xin-lai/Magicodes.IE/blob/master/src/Magicodes.ExporterAndImporter.Excel/ExcelExporter.cs

/// <summary>
        ///     获取头部定义
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="exporterHeaderList"></param>
        /// <param name="dataColumns"></param>
        /// <returns></returns>

 `   
 private static bool GetExporterHeaderInfoList<T>(out List<ExporterHeaderInfo> exporterHeaderList,
            DataColumnCollection dataColumns)
        {
            exporterHeaderList = new List<ExporterHeaderInfo>();
            var objProperties = typeof(T).GetProperties();
            if (objProperties == null || objProperties.Length == 0)
                return true;
            var index = 0;
            for (var k = 0; k < dataColumns.Count; k++)
            for (var i = 0; i < objProperties.Length; i++)
                if (dataColumns[k].ColumnName.Equals(objProperties[i].Name))
                {
                    index += 1;
                    exporterHeaderList.Add(new ExporterHeaderInfo
                    {
                        Index = index,
                        PropertyName = objProperties[i].Name,
                        ExporterHeader =
                            (objProperties[i].GetCustomAttributes(typeof(ExporterHeaderAttribute), true) as
                                ExporterHeaderAttribute[])?.FirstOrDefault()
                    });
                }
            return false;
        }

`

@xin-lai

**Comment by xin-lai** [comment]
@geffzhang 
找张队  哈哈哈。。。

**Comment by geffzhang** [comment]
是基于DTO，DataTable 也一样是基于DTO的，必须指定你使用的DTO， DataTable 的列名和DTO的属性一致，这不是bug，这是一个特性
