### ISSUE TITLE
PDF导出IsEnablePagesCount无效

### ISSUE THREAD

**Issue by fanslead** [dotnetcore/Magicodes.IE#154]
代码如图
![image](https://user-images.githubusercontent.com/22066473/93665698-3c862f80-faab-11ea-97d2-7b9fdc2a2bcd.png)
![image](https://user-images.githubusercontent.com/22066473/93665703-4445d400-faab-11ea-81b8-70fdc9c6cc31.png)
导出效果如图
![image](https://user-images.githubusercontent.com/22066473/93665716-5c1d5800-faab-11ea-87c7-309c58a5533f.png)
页面没有分页是数字出现

**Comment by hueifeng** [comment]
可以通过如下方式实现页码
```
 new PdfExporterAttribute()
 {
      PaperKind = PaperKind.A4,
      IsEnablePagesCount = true,
      #if NETCOREAPP
      HeaderSettings =new HeaderSettings() { FontSize = 9, Right = "Page [page] of [toPage]", Line = true, Spacing = 2.812 }
      #endif
}
```

**Comment by fanslead** [comment]
方法有效，谢谢
