### ISSUE TITLE
Excel模板导出table中行高不等于模板行的行高

### ISSUE THREAD

**Issue by 1542793315** [dotnetcore/Magicodes.IE#155]
模板导出中 行高不一样的问题
我写了个简单的控制台程序，请查看一下

[ConsoleApp1.zip](https://github.com/dotnetcore/Magicodes.IE/files/5259110/ConsoleApp1.zip)
![image](https://user-images.githubusercontent.com/48785885/93843129-8ea59b80-fccb-11ea-94f0-ae20cf6bcf58.png)

**Comment by 1542793315** [comment]
![image](https://user-images.githubusercontent.com/48785885/93843187-bd237680-fccb-11ea-850a-c934ebc0e324.png)

**Comment by 1542793315** [comment]
请问会更新在2.3.0 之后版本的NuGet 包上吗，大概什么时候会有

**Comment by hueifeng** [comment]
我最近发布一版beta版本吧

**Comment by hueifeng** [comment]
该问题已在2.4.0-beta3中发布，可以通过如下命令引用
```
PM> Install-Package Magicodes.IE.Excel -Version 2.4.0-beta3
```
相同的问题 #147 ，麻烦帮忙验证一下 #142 是否有问题。
