### ISSUE TITLE
关于容器注入筛选器

### ISSUE THREAD

**Issue by 44673626** [dotnetcore/Magicodes.IE#156]
后端应用的是abpvnext，按照教程，能实现构造函数的依赖注入。
服务注册代码：
```csharp
 private static void ConfigureExporterHeaderFilterServices(ServiceConfigurationContext context)
        {
            //添加注入关系
            context.Services.AddSingleton<IImportHeaderFilter, ImportHeaderFilterForProject>();
            var serviceProvider = context.Services.BuildServiceProvider();
            AppDependencyResolver.Init(serviceProvider);
        }
```
DTO中代码：
```csharp
public class ImportHeaderFilterForProject : IImportHeaderFilter
    {
        private readonly ICustomerAppService _customerAppService;
        private GetCustomerInputDto input = new GetCustomerInputDto();
        public ImportHeaderFilterForProject()
        {
           
        }
        //构造函数依赖注入
        public ImportHeaderFilterForProject(ICustomerAppService customerAppService)
        {
            _customerAppService = customerAppService;
        }

        /// <summary>
        /// 关联客户信息，应用值映射，动态绑定到excel指定的列中
        /// </summary>
        /// <param name="importerHeaderInfos"></param>
        /// <returns></returns>
        public virtual List<ImporterHeaderInfo> Filter(List<ImporterHeaderInfo> importerHeaderInfos)
        {
            var customerList = _customerAppService.GetAllList(input);
            foreach (var item in importerHeaderInfos)
            {
                if (item.PropertyName == "CustomerName")
                {
                    item.MappingValues = new Dictionary<string, dynamic>()
                    {
                        {"男",0 },
                        {"女",1 }
                    };
                }
            }
            return importerHeaderInfos;
        }
    }
```
在方法中的代码：
  var customerList = _customerAppService.GetAllList(input);
调用时报错：A DbContext can only be created inside a unit of work！
查了abpvnext的资料：https://www.cnblogs.com/myzony/p/11863489.html

**Comment by xin-lai** [comment]
VNext我没跟了，也不是很清楚了。找个时间远程看看。

**Comment by 44673626** [comment]
已经非常感谢了&nbsp; 这块我自行解决一下，等解决了把解决方法分享出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "李文强"<notifications@github.com&gt;; 
发送时间: 2020年9月24日(星期四) 上午9:17
收件人: "dotnetcore/Magicodes.IE"<Magicodes.IE@noreply.github.com&gt;; 
抄送: "房大伟"<44673626@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dotnetcore/Magicodes.IE] 关于容器注入筛选器 (#156)





 
VNext我没跟了，也不是很清楚了。找个时间远程看看。

**Comment by xin-lai** [comment]
好的

**Comment by Nongzhsh** [comment]
> 后端应用的是abpvnext，按照教程，能实现构造函数的依赖注入。
> 服务注册代码：
> 
> ```
>  private static void ConfigureExporterHeaderFilterServices(ServiceConfigurationContext context)
>         {
>             //添加注入关系
>             context.Services.AddSingleton<IImportHeaderFilter, ImportHeaderFilterForProject>();
>             var serviceProvider = context.Services.BuildServiceProvider();
>             AppDependencyResolver.Init(serviceProvider);
>         }
> ```
> 
> DTO中代码：
> 
> ```
> public class ImportHeaderFilterForProject : IImportHeaderFilter
>     {
>         private readonly ICustomerAppService _customerAppService;
>         private GetCustomerInputDto input = new GetCustomerInputDto();
>         public ImportHeaderFilterForProject()
>         {
>            
>         }
>         //构造函数依赖注入
>         public ImportHeaderFilterForProject(ICustomerAppService customerAppService)
>         {
>             _customerAppService = customerAppService;
>         }
> 
>         /// <summary>
>         /// 关联客户信息，应用值映射，动态绑定到excel指定的列中
>         /// </summary>
>         /// <param name="importerHeaderInfos"></param>
>         /// <returns></returns>
>         public virtual List<ImporterHeaderInfo> Filter(List<ImporterHeaderInfo> importerHeaderInfos)
>         {
>             var customerList = _customerAppService.GetAllList(input);
>             foreach (var item in importerHeaderInfos)
>             {
>                 if (item.PropertyName == "CustomerName")
>                 {
>                     item.MappingValues = new Dictionary<string, dynamic>()
>                     {
>                         {"男",0 },
>                         {"女",1 }
>                     };
>                 }
>             }
>             return importerHeaderInfos;
>         }
>     }
> ```
> 
> 在方法中的代码：
> var customerList = _customerAppService.GetAllList(input);
> 调用时报错：A DbContext can only be created inside a unit of work！
> 查了abpvnext的资料：https://www.cnblogs.com/myzony/p/11863489.html

看起来好像是工作单元作用域问题，尝试 为你的 Filter() 添加 [uow] 特性，或者 重新 using(var uow = ...)

**Comment by 44673626** [comment]
> > 后端应用的是abpvnext，按照教程，能实现构造函数的依赖注入。
> > 服务注册代码：
> > ```
> >  private static void ConfigureExporterHeaderFilterServices(ServiceConfigurationContext context)
> >         {
> >             //添加注入关系
> >             context.Services.AddSingleton<IImportHeaderFilter, ImportHeaderFilterForProject>();
> >             var serviceProvider = context.Services.BuildServiceProvider();
> >             AppDependencyResolver.Init(serviceProvider);
> >         }
> > ```
> > 
> > 
> > DTO中代码：
> > ```
> > public class ImportHeaderFilterForProject : IImportHeaderFilter
> >     {
> >         private readonly ICustomerAppService _customerAppService;
> >         private GetCustomerInputDto input = new GetCustomerInputDto();
> >         public ImportHeaderFilterForProject()
> >         {
> >            
> >         }
> >         //构造函数依赖注入
> >         public ImportHeaderFilterForProject(ICustomerAppService customerAppService)
> >         {
> >             _customerAppService = customerAppService;
> >         }
> > 
> >         /// <summary>
> >         /// 关联客户信息，应用值映射，动态绑定到excel指定的列中
> >         /// </summary>
> >         /// <param name="importerHeaderInfos"></param>
> >         /// <returns></returns>
> >         public virtual List<ImporterHeaderInfo> Filter(List<ImporterHeaderInfo> importerHeaderInfos)
> >         {
> >             var customerList = _customerAppService.GetAllList(input);
> >             foreach (var item in importerHeaderInfos)
> >             {
> >                 if (item.PropertyName == "CustomerName")
> >                 {
> >                     item.MappingValues = new Dictionary<string, dynamic>()
> >                     {
> >                         {"男",0 },
> >                         {"女",1 }
> >                     };
> >                 }
> >             }
> >             return importerHeaderInfos;
> >         }
> >     }
> > ```
> > 
> > 
> > 在方法中的代码：
> > var customerList = _customerAppService.GetAllList(input);
> > 调用时报错：A DbContext can only be created inside a unit of work！
> > 查了abpvnext的资料：https://www.cnblogs.com/myzony/p/11863489.html
> 
> 看起来好像是工作单元作用域问题，尝试 为你的 Filter() 添加 [uow] 特性，或者 重新 using(var uow = ...)

用了，还是一样不好使，好像DbContext调用的不一样，注入后找底层的仓储，不一致

**Comment by 44673626** [comment]
有在abpvnext中应用咱这组件中的依赖注入实现从数据库中动态查数据后绑定到模板中，而非绑定枚举，有实现的指点一二。
目前咱这组件和abpvnext中应用的DI容器都是微软自带的Microsoft.Extensions.DependencyInjection

**Comment by xin-lai** [comment]
@44673626 还没解决？

**Comment by 44673626** [comment]
> @44673626 还没解决？

没有呀 大神，还是报先前的，“A DbContext can only be created inside a unit of work！”，到了调用数据库仓储那块过不去，DbContext不匹配，目前还没有找到解决办法，我用的abpvnext，按理说就是.net core的应用

**Comment by xin-lai** [comment]
@44673626 方便的话，麻烦上传一个极简的移除相关业务代码的Demo，我们可以一起来试试。

**Comment by 44673626** [comment]
> @44673626 方便的话，麻烦上传一个极简的移除相关业务代码的Demo，我们可以一起来试试。

好的 文强大神，我弄好了这里@你一下，把这个问题共同解决一下，这样咱的这个组件在abpvnext中就应用无敌了

**Comment by xin-lai** [comment]
好的

**Comment by Nokecy** [comment]
public override void OnApplicationInitialization(ApplicationInitializationContext context)
        {
            AppDependencyResolver.Init(context.ServiceProvider.GetService<AutofacServiceProvider>());
        }

**Comment by Nokecy** [comment]
@44673626  初始化放在Startup 类即可

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplication<WebModule>();
        }

        public void Configure(IApplicationBuilder app, HostingEnvironment env, IServiceProvider serviceProvider)
        {
            app.InitializeApplication();

            AppDependencyResolver.Init(serviceProvider);
        }
    }
