### ISSUE TITLE
cvs导入结果一直为空

### ISSUE THREAD

**Issue by xj728** [dotnetcore/Magicodes.IE#159]
cvs导入结果一直为空

**Comment by xin-lai** [comment]
请提供更详细资料或者Demo。

**Comment by xj728** [comment]
用cvshelper可以读取记录。需要的话可以提供文件给你。
还有就是读取数据科学计数法转换成文本的问题

**Comment by xin-lai** [comment]
@xj728 附件上传一下吧

**Comment by xj728** [comment]
[物流信息.zip](https://github.com/dotnetcore/Magicodes.IE/files/5287902/default.zip)

提示错误：{"The file is not an valid Package file. If the file is encrypted, please supply the password in the constructor."}

但是同一个文件用cvshelper可以读取成功。
另一个问题，导入数据中的科学计数列，怎么在程序中转换成正常的数字？

**Comment by hueifeng** [comment]
Please use CSV to import and export package.
```
PM> Install-Package Magicodes.IE.Csv 
```
