### ISSUE TITLE
word导出支持图片吗？

### ISSUE THREAD

**Issue by iNuoers** [dotnetcore/Magicodes.IE#160]
word导出支持图片吗？能不能加个导出word，支持图片

**Comment by hueifeng** [comment]
可以参考[href](https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/3.%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B%E4%B9%8B%E5%AF%BC%E5%87%BAPdf%E6%94%B6%E6%8D%AE.md)，定义自己的导出模板，word和pdf可以一样去定义导出模板，需要注意的是要引入`Magicodes.IE.Word`。

**Comment by iNuoers** [comment]
> 可以参考[href](https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/3.%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B%E4%B9%8B%E5%AF%BC%E5%87%BAPdf%E6%94%B6%E6%8D%AE.md)，定义自己的导出模板，word和pdf可以一样去定义导出模板，需要注意的是要引入`Magicodes.IE.Word`。

好的，我试一下，谢谢
