### ISSUE TITLE
可否支持单元格合并功能

### ISSUE THREAD

**Issue by 3zengzz** [dotnetcore/Magicodes.IE#169]
如题，可否支持单元格合并功能，支持复杂的导出，模板无法满足这类需求

**Comment by hueifeng** [comment]
来自 @3zengzz 本地提供的文件 [1df35c27bc294612a9a3e9d40697391b.xlsx](https://github.com/dotnetcore/Magicodes.IE/files/5388787/1df35c27bc294612a9a3e9d40697391b.xlsx)

**Comment by xin-lai** [comment]
关键在于如何设计。

**Comment by xin-lai** [comment]
3.0已考虑

**Comment by 3zengzz** [comment]
您好，你发的邮件，我已收到，谢谢！
