### ISSUE TITLE
导出excel，内含图片。

### ISSUE THREAD

**Issue by Dysheng** [dotnetcore/Magicodes.IE#172]
目前excel导出，里面可以图片，但是字段类型必须是字符串，是图片地址。
这样极不方便。
因为一般导出的图片，可能是根据某个字段变量动态生成的图片。
所以，用生成的图片导出，这样更高效

**Comment by hueifeng** [comment]
Base64 export is currently supported.
```
dotnet add package Magicodes.IE.Core --version 2.5.1.8
```
