### ISSUE TITLE
导出文件增加列筛选.

### ISSUE THREAD

**Issue by lament0** [dotnetcore/Magicodes.IE#173]
需求就是,往一列中塞一个下拉框,不让用户乱填...
但是这个下拉框最好可以自定义数值..因为很多值的映射关系都存在数据库里的

**Comment by hueifeng** [comment]
Sounds good, this is a good proposal, I think we can implement the filter function for our ʻExcel` export template.

**Comment by lament0** [comment]
希望根据Excel模板导出也加入此功能.

**Comment by lament0** [comment]
类似的效果如连接
https://jingyan.baidu.com/article/cd4c29795690c0756e6e60ed.html
不过希望是动态取值的效果

**Comment by hueifeng** [comment]
Oh, I remembered it wrong, there is a filter implementation in the generated import template.
