### ISSUE TITLE
能否自定义表头

### ISSUE THREAD

**Issue by BenLampson** [dotnetcore/Magicodes.IE#176]
目前情况是无法定义DTO,DataTable导出完全不能用.
或者说完全不知道杂用,给的DEMO也没有个API说明啥的.
官方的:
``` C#
public async Task LargeDataDynamicExport_Test()
{
    IExcelExporter exporter = new ExcelExporter();
   
    var dt = new DataTable();
    //创建带列名和类型名的列
    dt.Columns.Add("Text", Type.GetType("System.String"));
    dt.Columns.Add("Name", Type.GetType("System.String"));
    dt.Columns.Add("Number", Type.GetType("System.Decimal"));
    dt = EntityToDataTable(dt, exportDatas);

    var result = await exporter.Export(filePath, dt, maxRowNumberOnASheet: 100000);
}
```
我的代码如下:
``` C#
            var dt = new DataTable();
            //创建带列名和类型名的列
            dt.Columns.Add("Text", Type.GetType("System.String"));
            dt.Columns.Add("Name", Type.GetType("System.String"));
            dt.Columns.Add("Number", Type.GetType("System.Decimal"));
            dt.Rows.Add("1", "2", 1);
            var result =await exporter.Export<DataRow>("./X.xlsx", dt);
```
似乎与官方给的DEMO的API是变了...但是也没说应该改成啥..泛型给DataRow纯属猜的ヾ(=ﾟ･ﾟ=)ﾉ喵♪
报错的内容也很迷:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Column index out of range')

**Comment by hueifeng** [comment]
DataTable导出提供快速导出的形式，可直接传递数据源进行导出，如下所示：
```csharp
var dt = new DataTable();
//创建带列名和类型名的列
dt.Columns.Add("Text", Type.GetType("System.String"));
dt.Columns.Add("Name", Type.GetType("System.String"));
dt.Columns.Add("Number", Type.GetType("System.Decimal"));
dt = EntityToDataTable(dt, exportDatas);

var result = await exporter.Export(filePath, dt, maxRowNumberOnASheet: 100000);
```
另外对于`T:class`我们可以通过其去让我们的表格支持拥有一些功能特性，当然需要您先去创建一个DTO的映射类，来完成这些操作

```csharp
var result = await exporter.Export<ExportTestDataWithAttrs>(filePath, dt);
```

感谢您的反馈

**Comment by BenLampson** [comment]
其实问题的核心在于我不能使用任何DTO的模型,总不能我使用natasha先动态构造一堆对象出来然后扔到datatable吧...
如果是这样,那datatable的意义就不大了..
因为我明显已经有模型了,为啥我还需要转换成datatable?

**Comment by BenLampson** [comment]
另外exporter.Export 这个API现在需要传递一个Type...

**Comment by hueifeng** [comment]
@BenLampson 似乎您可以参考如下代码片段[https://github.com/dotnetcore/Magicodes.IE/blob/master/src/Magicodes.ExporterAndImporter.Tests/ExcelExporter_Tests.cs#L582](https://github.com/dotnetcore/Magicodes.IE/blob/master/src/Magicodes.ExporterAndImporter.Tests/ExcelExporter_Tests.cs#L582)

**Comment by BenLampson** [comment]
您代码中不需要填写Type的扩展在哪个包呀?
![image](https://user-images.githubusercontent.com/15414750/97522975-05753900-19dc-11eb-97fc-9dc751fb683b.png)

**Comment by hueifeng** [comment]
可以通过`IExcelExporter`去调用，详情请参考：
https://github.com/dotnetcore/Magicodes.IE/blob/master/src/Magicodes.ExporterAndImporter.Excel/IExcelExporter.cs#L13

**Comment by BenLampson** [comment]
谢谢您,麻烦了~
