### ISSUE TITLE
导出Excel如何实现行单元格合并？

### ISSUE THREAD

**Issue by weiwxg** [dotnetcore/Magicodes.IE#177]

**Comment by wuyajungo** [comment]
目前貌似不支持合并。估计作者也不考虑支持合并单元格，

**Comment by weiwxg** [comment]
> 目前貌似不支持合并。估计作者也不考虑支持合并单元格，

虽然似乎不太合理，但是这种需求确实是存在的

**Comment by hueifeng** [comment]
关于这个问题，我们已在3.0版本的设计中去支持。
https://docs.xin-lai.com/2020/11/04/%E7%BB%84%E4%BB%B6/Magicodes.IE/Magicodes.IE%203.0%E8%AE%BE%E8%AE%A1%E7%95%85%E8%B0%88/

**Comment by zhangzw218** [comment]
> @weiwxg @wuyajungo 两位可以看看3.0的设计是否符合你们的需求。

3.合并列头。 确实是想要的功能，不过，3.0版本似乎还未完成？
