### ISSUE TITLE
请问能兼容xls格式的吗

### ISSUE THREAD

**Issue by 1542793315** [dotnetcore/Magicodes.IE#178]
请问能兼容xls格式的吗 或者 有没有将xls 转为xlsx格式的 ，最好是stream文件流形式的处理

**Comment by hueifeng** [comment]
@1542793315 xls格式是兼容的

**Comment by 1542793315** [comment]
![image](https://user-images.githubusercontent.com/48785885/97961629-a30ea500-1dee-11eb-90a0-965bbf59220d.png)
我用xls格式的文件读取的时候 sheets是空数据
@hueifeng

**Comment by hueifeng** [comment]
我未通过您的描述复现该问题，您可以上传一个Demo吗？或者说参考我们的教程和通过我们的单元测试，以xls格式文件形式进行导入？

**Comment by 1542793315** [comment]
[xlsdemo.zip](https://github.com/dotnetcore/Magicodes.IE/files/5480102/xlsdemo.zip)
@hueifeng

**Comment by 1542793315** [comment]
@hueifeng 请问是什么原因呢？还有其他方法吗OfficeOpenXml不行的话

**Comment by hueifeng** [comment]
Oh~，抱歉，我忽略了EPPlus不支持xls格式文件，您可以修改格式为xlsx进行读取和写入操作.

**Comment by 1542793315** [comment]
So~,该怎么办嘞，所以没有xls转xlsx的方法吗，用程序转而不是手动重新保存
@hueifeng

**Comment by hueifeng** [comment]
IE并没有对外提供格式转换特性，您可以通过其他方式进行格式转换

**Comment by 1542793315** [comment]
> IE并没有对外提供格式转换特性，您可以通过其他方式进行格式转换

好的谢谢你了
