### ISSUE TITLE
已有的项目中安装过EPPlus，再次安装Magicodes.IE出先重复引用的问题，请问我该如何处理

### ISSUE THREAD

**Issue by weiwxg** [dotnetcore/Magicodes.IE#186]
>> 报错信息：类型“ExcelVerticalAlignment”同时存在于“EPPlus, Version=4.5.3.2, Culture=neutral, PublicKeyToken=ea159fdaa78159a1”和“Magicodes.EPPlus, Version=4.6.1.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1”中

**Comment by hueifeng** [comment]
建议对于项目中引用的EPPlus可以选择直接卸载，保留Magicodes.IE即可，里面已有相关的依赖项

**Comment by DUWENINK** [comment]
如果无法卸载呢 因为也是引用的他人的dll

**Comment by weiwxg** [comment]
我记得我当时是通过c#的程序集别名处理的，关键字extern好像
---- 回复的原邮件 ----
| 发件人 | Reynaldo ***@***.***> |
| 发送日期 | 2023年07月24日 19:42 |
| 收件人 | ***@***.***> |
| 抄送人 | weiwxg ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [dotnetcore/Magicodes.IE] 已有的项目中安装过EPPlus，再次安装Magicodes.IE出先重复引用的问题，请问我该如何处理 (#186) |

如果无法卸载呢 因为也是引用的他人的dll
