### ISSUE TITLE
导出Excel如何取消默认的样式

### ISSUE THREAD

**Issue by weiwxg** [dotnetcore/Magicodes.IE#187]
RT

**Comment by hueifeng** [comment]
可通过`TableStyle`来取消样式
```csharp
  [ExcelExporter(Name = "学生信息", TableStyle = "None")]
```

**Comment by weiwxg** [comment]
> 可通过`TableStyle`来取消样式
> 
> ```cs
>   [ExcelExporter(Name = "学生信息", TableStyle = "None")]
> ```

你好，另外请问一下TableStyle的可用值有哪些，在哪里可以查到？

**Comment by hueifeng** [comment]
可以参考Epplus [Enum TableStyles](https://epplussoftware.com/docs/5.3/api/OfficeOpenXml.Table.TableStyles.html) 。

**Comment by weiwxg** [comment]
@hueifeng 对于通过DataTable导出的方式，如何设置ExcelPorter属性，如Name、TableStyle等

**Comment by hueifeng** [comment]
可参考 [DataTable结合DTO导出Excel](https://github.com/dotnetcore/Magicodes.IE/blob/master/src/Magicodes.ExporterAndImporter.Tests/ExcelExporter_Tests.cs#L290)

**Comment by weiwxg** [comment]
> 可参考 [DataTable结合DTO导出Excel](https://github.com/dotnetcore/Magicodes.IE/blob/master/src/Magicodes.ExporterAndImporter.Tests/ExcelExporter_Tests.cs#L290)

我的导出没有Dto，因为列是动态的

**Comment by hueifeng** [comment]
在DataTable类型导出时，可通过DTO去给当前数据集增加特性，按照您上面的描述目前是不可以的。不过后期该功能是可以加强的。

**Comment by zgjcom** [comment]
默认样式能不能去掉啊  干干净净的 需要什么样式 再在自己定义 毕竟默认样式不是个个都喜欢

我也是  就想导出一张干净的二维表  用 DataTabl动态生成列 没有用DTO的..

**Comment by hueifeng** [comment]
@zgjcom 对于默认样式，目前可以使用DTO去实现该特性。

、、、
  [ExcelExporter(Name = "学生信息", TableStyle = "None")]
、、、

**Comment by weiwxg** [comment]
> 默认样式能不能去掉啊 干干净净的 需要什么样式 再在自己定义 毕竟默认样式不是个个都喜欢
> 
> 我也是 就想导出一张干净的二维表 用 DataTabl动态生成列 没有用DTO的..

貌似无解，我觉得默认导出的Excel就不应该有任何的样式才合理

**Comment by weiwxg** [comment]
@hueifeng 建议提供类似函数：
```csharp
_exporter.ExportByTemplete("output.xlsx", datas, "templetes", options => {
    options.TableStyle = "Light10";
    // ...
});
```

**Comment by xin-lai** [comment]
@weiwxg 试试设置  ExcelOutputType = ExcelOutputTypes.None

**Comment by weiwxg** [comment]
> @weiwxg 试试设置 ExcelOutputType = ExcelOutputTypes.None

你好，我使用的是下面这个方法导出的，没有发现有设置`ExcelOutputType = ExcelOutputTypes.None`的地方。
![image](https://user-images.githubusercontent.com/24971860/99925549-89bba180-2d79-11eb-97e9-89e433ef5737.png)

另外，请注意，因为我需要导出的数据集的列是动态的，没有办法自定义导出的实体模型，只能通过动态创建的DataTable导出，所以那些要求在实体模型上做导出设定的方法对我都没有效果。

**Comment by xin-lai** [comment]
@weiwxg 明白了，这个在动态导出确实不支持。我们需要改造一下。
@hueifeng TableStyle的特性设置我们改成枚举吧

**Comment by hueifeng** [comment]
- [x] TableStyle的特性设置
- [ ] DataTable导出支持参数形式表样式
