### ISSUE TITLE
ExporterHeader特性导出int类型数值格式问题

### ISSUE THREAD

**Issue by lament0** [dotnetcore/Magicodes.IE#191]
目前导出方法
![image](https://user-images.githubusercontent.com/25712599/99652756-2d176880-2a93-11eb-9867-15543022d9b7.png)
但是导出的文件,Sum并不是数值格式,不方便自动求和.
![image](https://user-images.githubusercontent.com/25712599/99652828-47514680-2a93-11eb-92b9-04f9c87fb038.png)
希望给一个解决方案.

**Comment by hueifeng** [comment]
如果是List集合导出的话可以选择通过Excel中的 工具栏->数据->分列->分隔符号选择空格->点击完成。

或者通过DataTable类型去自动处理，并展示自动求和信息。
