### ISSUE TITLE
ValueMapping是INT导出无效还是显示0和1

### ISSUE THREAD

**Issue by SmartforXiaoYuan** [dotnetcore/Magicodes.IE#194]
[ValueMapping(text: "否", 0)]
[ValueMapping(text: "是", 1)]
public int AutomaticRenewal { get; set; }
![image](https://user-images.githubusercontent.com/26918295/99793083-0fb1cf80-2b63-11eb-8f5c-2e6f3c125cd1.png)
目前版本是否支持？

**Comment by hueifeng** [comment]
仅对Enum&bool类型指定显示的值

**Comment by xin-lai** [comment]
@hueifeng 你在跟进？是导出的Bug？

**Comment by hueifeng** [comment]
@xin-lai  这个问题不属于BUG，我们目前对于导出值映射限制的是bool和enum类型。
