### ISSUE TITLE
ExcelExporter特性参数fontsize有误，枚举值导出为空

### ISSUE THREAD

**Issue by gnahziak** [dotnetcore/Magicodes.IE#195]
![image](https://user-images.githubusercontent.com/16639887/99899665-03a24b00-2ce6-11eb-9c28-cd865e3138ed.png)

定义枚举如：
```csharp
 public enum Sex
    {
        /// <summary>
        /// 男
        /// </summary>
        [Display(Name = "男")]
        [Description("男")]
        boy =1,
        /// <summary>
        /// 女
        /// </summary>
        [Display(Name = "女")]
        [Description("女")]
        girl =2
    }

  [ExporterHeader(DisplayName = "性别")]
        public Sex Sex { get; set; }

```
导出excel 值为空  
![image](https://user-images.githubusercontent.com/16639887/99899689-364c4380-2ce6-11eb-8a0c-1ec9f1fca3bc.png)

**Comment by wensaint** [comment]
附议，枚举值导出为空

**Comment by hueifeng** [comment]
@gnahziak @wensaint 我尝试去复现该问题 [link](https://github.com/dotnetcore/Magicodes.IE/blob/master/src/Magicodes.ExporterAndImporter.Tests/Excel_Tests.cs#L53)，不幸的是我编写的单元测试，并没有达到如期的效果让我看到复现的内容，可以帮助我们去复现问题吗？或者提供复现的DEMO。

**Comment by xin-lai** [comment]
@hueifeng 我估计是版本问题。值映射在早期版本，只支持导入，并不支持导出。

**Comment by wensaint** [comment]
我的数据结构中，实际存储为int，我希望导出时自动转换成枚举值

－－－－－－－－－－－参考你的测试案例－－－－－－－－－－－－－
var data = GenFu.GenFu.ListOf<Issue195>(100);
            data[0].Sex = (int)Sex.男;
            data[1].Sex =  (int)Sex.女;
            var result = await exporter.Export(filePath, data);

            result.ShouldNotBeNull();
            File.Exists(filePath).ShouldBeTrue();
            using (var pck = new ExcelPackage(new FileInfo(filePath)))
            {
                pck.Workbook.Worksheets.Count.ShouldBe(1);
                var sheet = pck.Workbook.Worksheets.First();

                sheet.Cells["B2"].Text.Equals("男");

                sheet.Cells["B3"].Text.Equals("女");
            }

**Comment by xin-lai** [comment]
int类型暂不支持值映射，需要你先将int转为DTO的枚举属性进行导出才有效。在3.0我们会考虑这个情形。
