### ISSUE TITLE
使用IImportResultFilter 动态生成模板时，MappingValues绑定的数据过大，报The total length of a DataValidation list cannot exceed 255 characters

### ISSUE THREAD

**Issue by Nokecy** [dotnetcore/Magicodes.IE#196]
版本 v2.4.0

**Comment by hueifeng** [comment]
We did a survey and got the following.
> The ListDataValidation rule is indeed limited to 255 symbols (including the commas). This is because in Excel itself you can only define a DataValidation List with no more than 255 symbols. Since Excel doesn’t support DataValidation Lists longer than 255 characters, our engine also can’t support it.

**Comment by Nokecy** [comment]
https://blog.csdn.net/wangchaox123/article/details/97787470
使用隐藏域是否可以规避
