### ISSUE TITLE
动态的多sheet导入

### ISSUE THREAD

**Issue by nblfeng** [dotnetcore/Magicodes.IE#200]
有个这样的需求:
1. 一个excle中可以自定义多个sheet;
2. 每个sheet的数据结构是一样的;

这样在通过ExcelImporter的ImportSameSheets进行导入的时候, 如何获取所有的sheet中的数据以及sheet的名称?

**Comment by hueifeng** [comment]
也许在[多Sheet导入](![file](/uploads/img-a2694109-ab80-4b4d-aa36-9a4d0d4d189e.png))中，您可以得到帮助。

**Comment by xin-lai** [comment]
![image](https://user-images.githubusercontent.com/22255486/100691110-f01c7180-33c2-11eb-8fd4-a92882efecae.png)

**Comment by xin-lai** [comment]
[多Sheet导入](https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/6.%E5%A4%9ASheet%E5%AF%BC%E5%85%A5.md)

**Comment by 256051** [comment]
在不知道有多少个sheet个数的时候，动态导入多sheet怎么处理

**Comment by xl-wenqiang** [comment]
> 在不知道有多少个sheet个数的时候，动态导入多sheet怎么处理

目前是通过Sheet名称来处理的。你可以先通过EPPLUS API获取Sheet数及相关情况再进行处理。
