### ISSUE TITLE
Excel导入超过5000行报错，可否把最大支持导入行数改成可配置的选项

### ISSUE THREAD

**Issue by aioloswong** [dotnetcore/Magicodes.IE#202]
如题。

**Comment by hueifeng** [comment]
@aioloswong 我们在导入的基础类中提供的最大导入限制为`50000`并非`5000`，对于导入行设置我们是有的. 您能提供错误详情吗？
```csharp
    [AttributeUsage(AttributeTargets.Class)]
    public class ImporterAttribute : Attribute
    {
        /// <summary>
        /// 最大允许导入的行数
        /// </summary>
        public int MaxCount = 50000;
 }
```

**Comment by aioloswong** [comment]
代码在Magicodes.ExporterAndImporter.Excel.Utility.ImportMultipleSheetHelper类的第637行，如图所示：
![image](https://user-images.githubusercontent.com/10336303/101610626-77ad5480-3a43-11eb-8800-464d7dda2f19.png)

**Comment by hueifeng** [comment]
The problem has been fixed in 2.5.1, I close the issue.
