### ISSUE TITLE
根据模板文件导出PDF不能正确识别样式

### ISSUE THREAD

**Issue by taoqijing** [dotnetcore/Magicodes.IE#203]
版本2.4.0
方法：PdfExporter.ExportByTemplate
测试用例：如下
```html
<body>
    <div style="text-align:center;font-size:20px;font-weight:normal;writing-mode:vertical-lr;">
        <p>第一联存根(Filing Copy) 白纸   第二联 结算(Finance Copy) 红纸 第三联 客户 (Customer Copy) 蓝纸</p>
    </div>
</body>
 ``` 
结果：目标是竖向文字，但是生成的是横向。

**Comment by taoqijing** [comment]
<body>
    <div style="text-align:center;font-size:20px;font-weight:normal;writing-mode:vertical-lr;">
        <p>第一联存根(Filing Copy) 白纸   第二联 结算(Finance Copy) 红纸 第三联 客户 (Customer Copy) 蓝纸</p>
    </div>
</body>

**Comment by hueifeng** [comment]
@taoqijing  在您的css的使用中，我发现您使用了 `writing-mode:vertical-lr`，不幸的是这个样式是不兼容的，对于PDF导出HTML模板兼容性，您可以在IE浏览器上进行测试样式的兼容。另外对于一些HTML5的标签也是不支持的 #45，对于`writing-mode`您可以采用其他值，详情参考
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode)。

**Comment by taoqijing** [comment]
收到，谢谢。已经替换为其他样式。
