### ISSUE TITLE
有导出word的例子或文档说明吗

### ISSUE THREAD

**Issue by ltcszk** [dotnetcore/Magicodes.IE#209]
docs目录里只看到一个通过请求头导出的，template应该怎么写

**Comment by hueifeng** [comment]
word导出可以参考pdf导出，模板定义是一致的 [基础教程之导出Pdf收据](https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/3.%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B%E4%B9%8B%E5%AF%BC%E5%87%BAPdf%E6%94%B6%E6%8D%AE.md)，需要注意的是引入`Magicodes.IE.Word`
