### ISSUE TITLE
模板导出后存在单元格数据精度的bug

### ISSUE THREAD

**Issue by 1542793315** [dotnetcore/Magicodes.IE#212]
如图在decimal 类型的数据模板导出后，存在精度问题，12.000000000000 变成了11.99999999998  
demo：
[xlsdemo.zip](https://github.com/dotnetcore/Magicodes.IE/files/5694624/xlsdemo.zip)
 
![image](https://user-images.githubusercontent.com/48785885/102194754-a2425600-3ef8-11eb-9ecf-26b7952f096b.png)

**Comment by 1542793315** [comment]
excel显示和复制都是正确的，但是我使用c# 读取的时候数据是错误的

**Comment by 1542793315** [comment]
@hueifeng

**Comment by hueifeng** [comment]
通过调查发现在Excel中，可存储15位有效的数字. 似乎在这里可以提供答案 [Understanding Floating Point Precision, aka “Why does Excel Give Me Seemingly Wrong Answers?”](https://www.microsoft.com/en-us/microsoft-365/blog/2008/04/10/understanding-floating-point-precision-aka-why-does-excel-give-me-seemingly-wrong-answers/)
