### ISSUE TITLE
Excel模板导入中的图片导入，位置偏移问题

### ISSUE THREAD

**Issue by GitKMande** [dotnetcore/Magicodes.IE#213]
**Describe the bug**
进行Excel模板导入，在模板的一单元格中写入图片标签导入图片时，图片导入成功，但是，偏离了指定的单元格。
**To Reproduce**
附件中有整个工程文档，直接解压，我用vs2019。
点击“生产”按钮，就能复现问题。

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
[WpfExcelTransation.zip](https://github.com/dotnetcore/Magicodes.IE/files/5695209/WpfExcelTransation.zip)
用的是2.5.0版本

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hueifeng** [comment]
You can upgrade to the latest version.
```
dotnet add package Magicodes.IE.Excel--version 2.5.1.8
```
