### ISSUE TITLE
导出日期变成了数字

### ISSUE THREAD

**Issue by dashenxian** [dotnetcore/Magicodes.IE#22]
版本：1.4.21
导出的模型属性类型DateTime?类型，excel数据是数字，要手动设置单元格格式才能变成日期
![image](https://user-images.githubusercontent.com/18696614/72325892-0eb14580-36e9-11ea-8a3a-e9441d5762e7.png)

**Comment by xin-lai** [comment]
我看看

**Comment by xin-lai** [comment]
添加特性可以解决：
`
        /// <summary>
        /// 时间测试
        /// </summary>
        [ExporterHeader(DisplayName = "日期1", Format = "yyyy-MM-dd")]
        public DateTime Time1 { get; set; }

        /// <summary>
        /// 时间测试
        /// </summary>
        [ExporterHeader(DisplayName = "日期2", Format = "yyyy-MM-dd HH:mm:ss")]
        public DateTime? Time2 { get; set; }
`

**Comment by xin-lai** [comment]
````C#
        /// <summary>
        /// 时间测试
        /// </summary>
        [ExporterHeader(DisplayName = "日期1", Format = "yyyy-MM-dd")]
        public DateTime Time1 { get; set; }

        /// <summary>
        /// 时间测试
        /// </summary>
        [ExporterHeader(DisplayName = "日期2", Format = "yyyy-MM-dd HH:mm:ss")]
        public DateTime? Time2 { get; set; }
````

**Comment by xin-lai** [comment]
非常感谢。
此问题已修复，可以使用1.4.24版本。默认输出“yyyy-MM-dd”，具体见更新日志。

**Comment by booksir** [comment]
为什么我使用2.5.3.6版本还是会出现，日期变数字的问题，同样需要去设置一下单元格格式才能显示出日期
