### ISSUE TITLE
只支持.net framework 4.6.1  能不能向下兼容支持 4.5 或者到4.0 版本呢

### ISSUE THREAD

**Issue by IMLYQ** [dotnetcore/Magicodes.IE#224]
在做项目的修改时发现.NET版本还在4.0 想使用Magicodes.IE.Excel  结果发现不兼容

**Comment by hueifeng** [comment]
I don't think we will be compatible with the lower version framework, which will be an expensive expense. At the same time, I also recommend that you use the higher version framework.
