### ISSUE TITLE
word导出的样式和razor渲染的html不一致

### ISSUE THREAD

**Issue by ltcszk** [dotnetcore/Magicodes.IE#225]
razor模板直接输出页面看着没问题
导出word发现表格单元格宽度、style里写class的样式之类的设置全无效了

**Comment by hueifeng** [comment]
@ltcszk Please refer to #45, and try to adjust style compatibility in Internet Explorer.

**Comment by ltcszk** [comment]
> 
> 
> @ltcszk Please refer to #45, and try to adjust style compatibility in Internet Explorer.

在ie 8下也是正常的，而且我用word自带的转换html功能做模板，导出格式也不一样

**Comment by hueifeng** [comment]
Can you provide me with templates? Provide two different templates, one for the correct Word template and one for the wrong HTML template.

**Comment by ltcszk** [comment]
[模板](https://github.com/ltcszk/temp/blob/main/temp.cshtml)里面没有动态内容，直接是用word转换的，就替换了@的转义
` var exporter = new HtmlExporter();
var rtn=await exporter.ExportBytesByTemplate(
                new object(), tpl);`
导出的是我想要的结果
`var exporter = new WordExporter();
            var rtn=await exporter.ExportBytesByTemplate(
                list, tpl);`
导出表格的样式会出问题

我现在用前一种输出文件时把后缀名从 .html改成 .doc倒是能解决这个问题

**Comment by xin-lai** [comment]
@ltcszk 和是否有动态内容无关，应该是HTML和CSS的部分语法不支持导致的。
