### ISSUE TITLE
基类派生类导出自定义表头排序导出数据于表头不一致

### ISSUE THREAD

**Issue by 263613093** [dotnetcore/Magicodes.IE#226]
BaseEntity类定义了A，B，C三个属性，ExporterHeader的ColumnIndex分别为1，2，3
D,E,F三个属性设置ExporterHeader的ColumnIndex分别为30，31，31

然后创建EntityA继承BaseEntity，有X,Y,Z三个属性设置ExporterHeader的ColumnIndex分别为11，12，13

这时候调用ExcelExporter的ExportAsByteArray方法导出xlsx文件
头的顺序为A,B,C,X,Y,Z,D,E,F这个是没问题的
但是数据顺序却是X,Y,Z,A,B,C,D,E,F这个是有问题的

**Comment by 263613093** [comment]
[ExportXls.zip](https://github.com/dotnetcore/Magicodes.IE/files/5784563/ExportXls.zip)
示例代码已上传

**Comment by 263613093** [comment]
刚又发现了，不仅仅类继承导出有问题
单独的类导出列头索引也会有问题
例如，上面定义的类属性设置列头索引高于下面的类属性列头索引，就会出问题

**Comment by xin-lai** [comment]
@263613093 用下最新版本试试
