### ISSUE TITLE
与Abp Vnext(autofac)配合使用出现异常

### ISSUE THREAD

**Issue by XuJin186** [dotnetcore/Magicodes.IE#227]
**Describe the bug**
想通过ioc反射出IExporterHeaderFilter出异常

**To Reproduce**
1.打开上传的Demo
2.点击运行
3. 在swagger界面找到test控制器的export接口执行测试
4. 看控制台的异常信息

**Expected behavior**
正常获取到IExporterHeaderFilter实现

异常信息为： Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already been disposed.
System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already bee
n disposed.

[aspnet-core.zip](https://github.com/dotnetcore/Magicodes.IE/files/5780612/aspnet-core.zip)

**Comment by xin-lai** [comment]
![image](https://user-images.githubusercontent.com/22255486/104671430-cae88600-5718-11eb-9d22-a541b2175257.png)
应用模块代码：
```csharp
    public class demoApplicationModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<AbpAutoMapperOptions>(options => { options.AddMaps<demoApplicationModule>(); });
            context.Services.AddSingleton<IExporterHeaderFilter, TestExporterHeaderFilter>();
        }
    }
```
