### ISSUE TITLE
如何把数字导出成文本？

### ISSUE THREAD

**Issue by pjy612** [dotnetcore/Magicodes.IE#23]
Format 设置为什么 可以让 单元格 在导出后变成文本。
long 的 总变成 科学计数法 
网上查了下 设成 @ 也没有用。。。
还是说最新版已经支持？

**Comment by xin-lai** [comment]
把你的代码贴上来看看

**Comment by pjy612** [comment]
```C#
[ExcelExporter]
        class LongToStr
        {
            [ExporterHeader("Long",format:"@")]
            public long Long { get; set; }
            [ExporterHeader("String")]
            public String Str => Long.ToString();
        }

List<LongToStr> list = new List<LongToStr>();
            for (long i = 9223372036854775797L; i > 9223372036854775787L; i--)
            {
                list.Add(new LongToStr(){Long = i});
            }
            ExcelExporter exporter = new ExcelExporter();
            exporter.Export("test.xlsx", list);
```
![image](https://user-images.githubusercontent.com/4072526/72599920-913a3f00-394d-11ea-97de-2267edb3e135.png)

我希望能让数字显示成字符串 = =。有什么方法吗？

**Comment by xin-lai** [comment]
#,##0

**Comment by xin-lai** [comment]
[ExporterHeader(DisplayName = "长数值", Format = "#,##0")]

**Comment by pjy612** [comment]
> [ExporterHeader(DisplayName = "长数值", Format = "#,##0")]
```
###0
#0
#
0
```
我刚都试了，然后 失真了。。。
![image](https://user-images.githubusercontent.com/4072526/72601309-1b83a280-3950-11ea-947e-5e23c6635991.png)

**Comment by pjy612** [comment]
如果暂不支持的话 将来能不能在 Attr 里面加个 type 什么的 让字段当字符串 处理

**Comment by xin-lai** [comment]
等我有空测试一下。
可以考虑。

**Comment by xin-lai** [comment]
设置为“#”是OK的，但是如果数值过长的话，在写入的时候已经存在数据丢失，因此无论你如何设置格式，都是不对的。哪怕再将其转为文本类型。
基于以上情形，建议如下：

- 将DTO长数值列设置为string类型
- 然后使用Select将你的原始List做一个转换再进行导出

后续可以考虑通过特性处理，或者提供数据筛选器。
