### ISSUE TITLE
Excel模板导出报错 - Unterminated string literal (at index 59).

### ISSUE THREAD

**Issue by kekoke** [dotnetcore/Magicodes.IE#230]
错误信息：
![image](https://user-images.githubusercontent.com/17831817/104595757-00a45500-56ae-11eb-9549-7a11fce1efb0.png)

模板如下图所示：
![image](https://user-images.githubusercontent.com/17831817/104595977-4c56fe80-56ae-11eb-9ab2-3bef05bccb74.png)

数据模型如下所示：
`
public class AEvaluationSupplierExportViewModel
    {
        public string Year { get; set; }
        public List<AEvaluationSupplierExportDto> SupplierList { get; set; }
    }
`

**Comment by hueifeng** [comment]
Please note the English and Chinese double quotation marks around x, which will lead to semantic errors.
![image](https://user-images.githubusercontent.com/34702552/104603111-11a59400-56b7-11eb-8458-31727288c886.png)

**Comment by kekoke** [comment]
感谢您的帮助，但是当我修改了模板之后，不再出错。修改之后的模板如下所示：
![image](https://user-images.githubusercontent.com/17831817/104609815-6567ab80-56be-11eb-8f8e-f42f9f7766d9.png)

可以导出excel，但是出现另一个奇怪的问题，那行内容不见了。如下图所示：
![image](https://user-images.githubusercontent.com/17831817/104609206-c478f080-56bd-11eb-9c45-1fd21002e213.png)

还请麻烦您再次解答，谢谢！

**Comment by hueifeng** [comment]
@kekoke  Unfortunately, I can't reproduce this problem. Please provide a reproducible file.

**Comment by kekoke** [comment]
[dept_form_summary_mg.xlsx](https://github.com/dotnetcore/Magicodes.IE/files/5818822/dept_form_summary_mg.xlsx)

已附上附件，谢谢您。

**Comment by hueifeng** [comment]
I'm sorry, I found that this is the same problem as #211.

**Comment by kekoke** [comment]
谢谢您。只是有些奇怪，我再看看有没有其他解决方案，谢谢。
![image](https://user-images.githubusercontent.com/17831817/104705917-71527c80-5755-11eb-8072-46671df9d011.png)

**Comment by kekoke** [comment]
我想是这个Excel模板有问题，我重建了一个模板，这个问题不在出现，很幸运它是正常运行的。非常感谢您的帮助。 @hueifeng
