### ISSUE TITLE
ValueMapping mapValue.value 不一定是int类型，这里强制转换是不是有问题

### ISSUE THREAD

**Issue by Nokecy** [dotnetcore/Magicodes.IE#232]
https://github.com/dotnetcore/Magicodes.IE/blob/d6ea52b6bf21d632072676e883d7fbc5741de5b4/src/Magicodes.ExporterAndImporter.Excel/Utility/ExportHelper.cs#L665

**Comment by hueifeng** [comment]
@Nokecy  Enter this control statement when the original type of the property is int. Do you have any problems at the moment?

**Comment by Nokecy** [comment]
` [ValueMapping("abc",1)]
 [ValueMapping("def",2)]
  public int abc {get;set;}
`
    System.FormatException : Input string was not in a correct format.

**Comment by xin-lai** [comment]
![image](https://user-images.githubusercontent.com/22255486/105811579-cf9a1d80-5fe7-11eb-8c73-64bd791ecaaa.png)
