### ISSUE TITLE
Magicodes.IE-master\src\Magicodes.ExporterAndImporter.Excel\ExcelImporter->GenerateTemplate[67-72]{MissingKeyword'else'}

### ISSUE THREAD

**Issue by JiangYueLin7** [dotnetcore/Magicodes.IE#234]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xin-lai** [comment]
有没有具体异常或者详细信息？

**Comment by hueifeng** [comment]
Customer does not respond, temporarily close the issue.
