### ISSUE TITLE
导入数据的时候，数据Excel 表中有合并的数据，类似于下图，有何方法导入？

### ISSUE THREAD

**Issue by AjuPrince** [dotnetcore/Magicodes.IE#239]
![image](https://user-images.githubusercontent.com/16829343/107189040-a5068680-6a23-11eb-89b0-ec7cba12fac3.png)

如何识别，合并并居中的这种数据？

**Comment by xin-lai** [comment]
目前在3.0的设计中有这个考虑。

**Comment by xin-lai** [comment]
#169 #145 #177
