### ISSUE TITLE
Magicodes.IE.Excel 模板导出异常

### ISSUE THREAD

**Issue by Linsan925** [dotnetcore/Magicodes.IE#240]
您好！

通过模板导出Table，如果只有一条数据，能正常导出，如果大于1条，则提示异常错误！

异常：
Error Saving file C:\work\demo.xlsx
System.InvalidOperationException: The address(N10:#REF!) collides with an existing validation (o10:#REF!)
    at OfficeOpenXml.DataValidation.ExcelDataValidationCollection.ValidateAddress(String address, IExcelDataValidation validatingValidation)

**Comment by hueifeng** [comment]
@Linsan925  You can provide templates, as well as DTO classes.

**Comment by Linsan925** [comment]
hi, @hueifeng 
**My Dto**
 public class NewEntityToExcelInfo
    {
        public List<NewEntityToExcelDto> NewEntitys { get; set; }

        public NewEntityToExcelInfo(List<NewEntityToExcelDto> newEntitys)
        {
            NewEntitys = newEntitys;
        }
    }

    public class NewEntityToExcelDto
    {

        public int RowIndex { get; set; }
        /// <summary>
        /// 外键，连Request.CaseNo
        /// </summary>
        public string CaseNo { get; set; }

        public string EnName { get; set; }

        public string CnName { get; set; }

        public string IsWelfare { get; set; }

        public string EntityType { get; set; }

        public string IsBeFund { get; set; }

        public string Address { get; set; }

        public string City { get; set; }

        public string Province { get; set; }

        public string RegisterCountry { get; set; }

        public string OperateCountry { get; set; }

        public string AuditNameEntity { get; set; }

        public string AuditAgreementEntity { get; set; }

        public string CICPAEntity { get; set; }

        public string PartnerName { get; set; }

        public string EngagementOffice { get; set; }
    }
**My Template**
[Template](https://colin-1302202819.cos.ap-nanjing.myqcloud.com/CN_New%20Entity1.xlsx)

**my method**
var list = await _newEntityRepository.GetAllAsync(w = w.CaseNo == caseNo);

            var result = ObjectMapper.MapListNewEntity, ListNewEntityToExcelDto(list);
            if (result == null  result.Count == 0) throw new UserFriendlyException(New entity is not found);
            for (int i = 0; i  result.Count; i++)
            {
                result[i].RowIndex = i + 1;
            }
            模板路径
            var tplPath = Path.Combine(Directory.GetCurrentDirectory(), File, Template, ${lang.ToUpper() }_New Entity.xlsx);
            创建Excel导出对象
            IExportFileByTemplate exporter = new ExcelExporter();

            var time = DateTime.Now.ToString(yyyyMMdd);
            导出目录
            var directory = Path.Combine(Directory.GetCurrentDirectory(), File, time);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
            导出路径
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), File, time, ${caseNo}_New Enity_{time}.xlsx);
            if (System.IO.File.Exists(filePath)) System.IO.File.Delete(filePath);
            根据模板导出
            await exporter.ExportByTemplate(filePath, new NewEntityToExcelInfo(result), tplPath);

**Comment by hueifeng** [comment]
Ok, Thank you, I will test it.

**Comment by hueifeng** [comment]
Hi, @Linsan925 , I copied the problem and found that it was due to 'DataValidation' in your template, which you can try to remove from the template.

**Comment by Linsan925** [comment]
Hi, @hueifeng ,Thank you very much for your reply!
