### ISSUE TITLE
使用模板导出，当DTO有多个数据列表，出现 Identifier expected (at index 34) 错误

### ISSUE THREAD

**Issue by kekoke** [dotnetcore/Magicodes.IE#242]
1. 数据模型如下
![image](https://user-images.githubusercontent.com/17831817/109751717-08966500-7c1a-11eb-83ec-6da2e24ea9a1.png)

2. 模板如下
![image](https://user-images.githubusercontent.com/17831817/109752005-92dec900-7c1a-11eb-8624-51de2cfd7585.png)

3. 报错如下
![image](https://user-images.githubusercontent.com/17831817/109751566-bce3bb80-7c19-11eb-94d4-38fbbc21c5d1.png)

**Comment by xin-lai** [comment]
应该和模板定义有关，和多个列表数据无关。能否麻烦移除敏感业务逻辑，整理一个Demo上传给我们进行测试呢？
@kekoke

**Comment by xin-lai** [comment]
模板的最底下那个列表的第二个格子的表达式是怎么编写的？有些看不清。

**Comment by kekoke** [comment]
> 模板的最底下那个列表的第二个格子的表达式是怎么编写的？有些看不清。

开头是这样 {{Table>>AEvaluationPersonalFormSuppliers|RowId}}
> 应该和模板定义有关，和多个列表数据无关。能否麻烦移除敏感业务逻辑，整理一个Demo上传给我们进行测试呢？
Keko: 我创建一个简单的模板试试。

**Comment by kekoke** [comment]
> 模板的最底下那个列表的第二个格子的表达式是怎么编写的？有些看不清。

如下所示：
{{CoreSupplierIcon}}{{SupplierNameCn}}
{{SupplierNameEn}}

**Comment by kekoke** [comment]
> 应该和模板定义有关，和多个列表数据无关。能否麻烦移除敏感业务逻辑，整理一个Demo上传给我们进行测试呢？
> @kekoke

找到原因了，是第一个列表的第一个栏位格式写错了。
![image](https://user-images.githubusercontent.com/17831817/109896458-e52bf280-7ccb-11eb-98da-f252e238b7b9.png)

非常感谢您的帮忙，谢谢 -^-^
