### ISSUE TITLE
excel导入是否能在ImporterHeader 加入一个忽略大小写的属性

### ISSUE THREAD

**Issue by axislover** [dotnetcore/Magicodes.IE#243]
在ImporterHeader 有一个IsAllowRepeat属性，但是此属性是区分大小写的判断 比如 aaa 和 AAA 是不一样的，能否加一个忽略大小写的判断 使aaa和AAA的判定是一样的。

**Comment by xin-lai** [comment]
收到。如果急得话，欢迎PR。

**Comment by xl-wenqiang** [comment]
具体使用见单元测试：IsIgnoreColumnCase_Test
包版本：2.5.3.5
