### ISSUE TITLE
是否可以读取名字A 的 Excle中所有的Sheet，包含图片等复制 到B Excle中？

### ISSUE THREAD

**Issue by archerzhaopan** [dotnetcore/Magicodes.IE#252]
是否可以读取名字A 的 Excle中所有的Sheet，包含图片等复制 到B Excle中？
如A Excle 中 含有 Sheet1、 Sheet2、 Sheet3 
B Excle 中 含有 SheetB1 

那么复制A后，B Excle 中 含有 SheetB1 、Sheet1、 Sheet2、 Sheet3

**Comment by hueifeng** [comment]
@archerzhaopan 对于这种情况，是否可通过`EPPlus`进行操作？也许对于目前来说这是一种解决方案。

```csharp
var list2 = GenFu.GenFu.ListOf<ExportTestDataWithAttrs>(30);
using (var pck = new ExcelPackage(new FileInfo(filePath)))
{
                  
}
```

**Comment by archerzhaopan** [comment]
楼上的说得对，也许EPPlus进行操作比较适合点，
package.Workbook.Worksheets.Add()
