### ISSUE TITLE
可设置导入模板 输入行的 单元格格式。

### ISSUE THREAD

**Issue by rzlihaowei** [dotnetcore/Magicodes.IE#253]
![image](https://user-images.githubusercontent.com/58129770/113096365-9a988a00-9227-11eb-9829-7d6d33b84570.png)

**Comment by hueifeng** [comment]
#231 Duplicate of

**Comment by hueifeng** [comment]
Now that this feature has been added, you can upgrade to the latest version.

```
dotnet add package Magicodes.IE.Excel --version 2.5.3.6
```
For example:
```
[ImporterHeader(Format ="@")]
```
