### ISSUE TITLE
导入的值不在模板枚举值的范围 ,输出ErrorMessage是空对象报错,能否使用友好的文本描述.

### ISSUE THREAD

**Issue by QHBZYJJC** [dotnetcore/Magicodes.IE#255]
如题
或者有哪些其他的可信性方案.
![image](https://user-images.githubusercontent.com/50282760/113408578-2e15ba80-93e2-11eb-92f6-28878d7933dd.png)
![image](https://user-images.githubusercontent.com/50282760/113408690-64533a00-93e2-11eb-8b8d-ad70453d2b28.png)

**Comment by QHBZYJJC** [comment]
看了源码有这个,但是好像没起作用,有空附加源码调试看看 ╮（╯＿╰）╭
![image](https://user-images.githubusercontent.com/50282760/113410593-5ef7ee80-93e6-11eb-8864-3eb5c3cf3187.png)

**Comment by xin-lai** [comment]
收到，我们会跟进。

**Comment by QHBZYJJC** [comment]
![image](https://user-images.githubusercontent.com/50282760/113681248-53f9d280-96f4-11eb-8b8f-4c8cb2a2918e.png)
附加代码看了下是这里Null了

**Comment by xin-lai** [comment]
收到。可以写个单元测试然后再进行调试，非常方便。
能否帮忙修复一下？有什么问题随时联系我们。

**Comment by xl-wenqiang** [comment]
已发布2.5.3.4，该问题已修复。详见单元测试和相关分支代码。
