### ISSUE TITLE
2.5.3.6版本日期与时间格式化，导出的时候变成数字格式

### ISSUE THREAD

**Issue by booksir** [dotnetcore/Magicodes.IE#259]
为什么我使用2.5.3.6版本还是会出现，日期变数字的问题，同样需要去设置一下单元格格式才能显示出日期

https://github.com/dotnetcore/Magicodes.IE/issues/22 ，这里的问题也是同样的，但它是之前的版本，按道理，现在当前版本应该解决了才对

**Comment by hueifeng** [comment]
因为在后续的版本升级中，我们修改了默认日期，添加了对地区日期格式的支持 详情 [commit](https://github.com/dotnetcore/Magicodes.IE/commit/646a3031c7b2fa34b252fc6fb307c58ff479da03)。

**Comment by booksir** [comment]
抱歉，是我这里的问题，原因是我在做动态列的导出，因为库并没有支持，所以我把DTO数据重新组装为IDictionary<string, object>数据格式作为导出源，DTO上面的Attribute，在全局的ExporterHeaderFilter中重新给值，在重新给值的时候，没有把Format给带进去，现在重新给Format，日期格式正常了
