### ISSUE TITLE
.net framework 4.6.1 ExportByTemplate no response

### ISSUE THREAD

**Issue by oblin** [dotnetcore/Magicodes.IE#260]
.net framework 4.6.1  Asp.net MVC code as following:
`
        public async Task<ActionResult> Contact()
        {
            string path = Server.MapPath(Url.Content("~/App_Data/Template.cshtml"));
            var template = System.IO.File.ReadAllText(path);

            var exporter = new PdfExporter();
            var data = new Report { Title = "Test", Date = DateTime.Now };

            try
            {
                var bytesResult = await exporter.ExportBytesByTemplate(data, template);
                return new FileContentResult(bytesResult, "application/pdf");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
`
debug 執行到：
await exporter.ExportBytesByTemplate(data, template);

系統沒有反應，也沒有結果。
是否可以麻煩協助？感謝。

**Comment by hueifeng** [comment]
@oblin 这个是控制器吗？如果是的话，我似乎看到有个地方编写错误了，按道理来讲编译器会出现异常。
```
public async Task Contact(){}
Task 无返回值
```
