### ISSUE TITLE
模板导出时候部分数据为空时候不显示 有什么方法实现么

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/Magicodes.IE#264]
比如模板导出时候 某一行内容 如果对应的属性值为空 则整行不显示  而不是留空行这样的情况

**Comment by hueifeng** [comment]
该功能没有很直接的实现，不过您可以考虑在模板执行完再通过如下代码片段加载表格，进行处理（对单元格进行逻辑处理)，例如：
```
var list2 = GenFu.GenFu.ListOf<ExportTestDataWithAttrs>(30);
using (var pck = new ExcelPackage(new FileInfo(filePath)))
{
                  
}

**Comment by lhtuling** [comment]
> 该功能没有很直接的实现，不过您可以考虑在模板执行完再通过如下代码片段加载表格，进行处理（对单元格进行逻辑处理)，例如：
> 
> ```
> var list2 = GenFu.GenFu.ListOf<ExportTestDataWithAttrs>(30);
> using (var pck = new ExcelPackage(new FileInfo(filePath)))
> {
>                   
> }
> ```

哦大概明白了 感谢指导

这个如果表达式到时候支持了就好搞了   
表达式功能有准备做上么?
