### ISSUE TITLE
通过html模版生成pdf占用内存快速不断升高

### ISSUE THREAD

**Issue by guochen2** [dotnetcore/Magicodes.IE#265]
### Expected behaviour
内存占用保持在一定范围内

### Actual behaviour
通过模版生成pdf，内存不断升高，每生成一次pdf大概上升20-150MB，通过PdfExporter ExportBytesByTemplate()方法调用生成。
![image](https://user-images.githubusercontent.com/12321505/116632906-c45de180-a98a-11eb-9dd4-ed661fc00a04.png)

### I'm seeing this behaviour on
_Remove this hint: these checkboxes can be checked like this: [x]_

- [ ] Magicodes.IE.Excel
- [x] Magicodes.IE.Pdf
- [ ] Magicodes.IE.Word
- [ ] Magicodes.IE.Csv
- [ ] Magicodes.IE.Html
- [ ] Magicodes.IE.AspNetCore

#### package versions
Magicodes.IE.Pdf 2.5.3.6
测试环境1：docker 18.09.6,镜像ccr.ccs.tencentyun.com/magicodes/aspnetcore-runtime:5.0
测试环境2：ubuntu 18.04 直接运行

**Comment by hueifeng** [comment]
收到

**Comment by hueifeng** [comment]
我尝试去优化这些，得到的结果：
|                                    Method |     Mean |     Error |   StdDev |     Gen 0 | Gen 1 | Gen 2 |  Allocated |
|------------------------------------------ |---------:|----------:|---------:|----------:|------:|------:|-----------:|
|                  ExportPdfAsByteArrayTest | 383.6 ms | 127.09 ms | 19.67 ms | 2000.0000 |     - |     - | 10864.5 KB |
|          ExportPdfOptimizeAsByteArrayTest | 223.1 ms |   9.87 ms |  2.56 ms |         - |     - |     - |  359.51 KB |

**Comment by guochen2** [comment]
> 收到

经测试，最新265分支已修复此问题， @hueifeng

**Comment by hueifeng** [comment]
@guochen2 好的谢谢啦，近期我们发布一下新版本。
