### ISSUE TITLE
services.AddControllers MagicodesFilter问题

### ISSUE THREAD

**Issue by 15801824890** [dotnetcore/Magicodes.IE#266]
![1620630709623](https://user-images.githubusercontent.com/21243328/117620855-7c696680-b1a3-11eb-9d23-15fbed66a92e.jpg)
![1620631058795](https://user-images.githubusercontent.com/21243328/117620863-7e332a00-b1a3-11eb-8f64-cd95b8fb72e4.jpg)
![1620631134333](https://user-images.githubusercontent.com/21243328/117620864-7f645700-b1a3-11eb-9204-227d53df691a.jpg)

添加 services.AddControllers(
                options => options.Filters.Add(typeof(MagicodesFilter)));能够导出正常打开，但我的api无法返回实体；
未添加是services.AddControllers()，导出无法正常打开，两者无法兼容？

**Comment by 15801824890** [comment]
public class Startup
    {
        /// <summary>
        /// Startup
        /// </summary>
        /// <param name="configuration"></param>
        /// <param name="env"></param>
        public Startup(IConfiguration configuration, IWebHostEnvironment env)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        /// <summary>
        /// ConfigureServices
        /// </summary>
        /// <param name="services"></param>
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            // services.AddControllers(
            //     options => options.Filters.Add(typeof(MagicodesFilter)));

          
            //设置接收文件长度的最大值。
            services.Configure<FormOptions>(x =>
            {
                x.ValueLengthLimit = int.MaxValue;
                x.MultipartBodyLengthLimit = int.MaxValue;
                x.MultipartHeadersLengthLimit = int.MaxValue;
            });

            //配置Mvc + json 序列化
            services.AddMvc(options => { options.EnableEndpointRouting = false; })
                .SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
                .AddNewtonsoftJson(options =>
                {
                    options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                    options.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Utc;
                    options.SerializerSettings.DateFormatString = "yyyy-MM-dd HH:mm:ss";
                })
                .AddJsonOptions(options => options.JsonSerializerOptions.PropertyNamingPolicy = null); //JSON首字母小写解决;

            //设置接收文件长度的最大值。
            services.Configure<FormOptions>(x =>
            {
                x.ValueLengthLimit = int.MaxValue;
                x.MultipartBodyLengthLimit = int.MaxValue;
                x.MultipartHeadersLengthLimit = int.MaxValue;
            });

            //Swagger为API文档增加说明信息,在AddSwaggerGen方法中配置说明信息
            services.AddSwaggerGen(option =>
            {
                option.SwaggerDoc("v1", new OpenApiInfo
                {
                    Version = "v1",
                    Title = "SecTalent WebAPI",
                    Description = "ASP.NET Core Web API",
                    Contact = new OpenApiContact()
                    {
                        Name = "JacobCai",
                        Email = "1499164758@qq.com",
                        //Url = new Uri("https://twitter.com/spboyer"),
                    },
                    License = new OpenApiLicense
                    {
                        Name = "Use under LICX",
                        Url = new Uri("https://www.baidu.com"),
                    }
                });

                // 为 Swagger JSON and UI设置xml文档注释路径
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                option.IncludeXmlComments(xmlPath, true);

                option.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
                {
                    Description = "Please enter into field the word 'Bearer' followed by a space and the JWT value",
                    Name = "Authorization",
                    In = ParameterLocation.Header,
                    Type = SecuritySchemeType.ApiKey
                });
                option.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Id = "Bearer",
                                Type = ReferenceType.SecurityScheme
                            }
                        },
                        Array.Empty<string>()
                    }
                });

                option.OperationFilter<AddRequiredHeaderParameter>();
            });
            //设置跨域
            //services.AddCors(option => option.AddPolicy("cors", policy => policy.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader().AllowCredentials()));
            services.AddCors(option => option.AddPolicy("CorsAdmin", policy => policy
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials()
                .WithOrigins("")));

            //注册appsetting
            services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));
            var appSettings = new AppSettings();
            Configuration.Bind("AppSettings", appSettings);
            services.Configure<SecurityCodeConfig>(Configuration.GetSection("SecurityCodeConfig"));
            //添加jwt验证：
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateIssuer = true, //是否验证Issuer
                        ValidateAudience = true, //是否验证Audience
                        ValidateLifetime = true, //是否验证失效时间
                        //ClockSkew = TimeSpan.FromSeconds(30),// If you want to allow a certain amount of clock drift,
                        ValidateIssuerSigningKey = true, //是否验证SecurityKey
                        ValidAudience = appSettings.TokenAudience, //Audience
                        ValidIssuer = appSettings.TokenIssuer, //Issuer，这两项和前面签发jwt的设置一致
                        IssuerSigningKey =
                            new SymmetricSecurityKey(Encoding.UTF8.GetBytes(appSettings.TokenSecretKey)) //拿到SecurityKey
                    };
                });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="app"></param>
        /// <param name="env"></param>
        /// <param name="loggerFactory"></param>
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            #region Nlog记日志

            //将日志记录到数据库config/NLog.config
            NLog.LogManager.LoadConfiguration("nlog.config").GetCurrentClassLogger();
            var ss = Configuration.GetConnectionString("MySqlConnection");
            NLog.LogManager.Configuration.Variables["connectionString"] =
                Configuration.GetConnectionString("MySqlConnection");
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); //避免日志中的中文输出乱码

            #endregion

            app.UseRouting();
            app.UseMagiCodesIE();

            //添加jwt验证
            app.UseAuthentication();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            //swagger
            var virtualPath = Configuration["virtualPath"];
            app.UseSwagger();
            app.UseSwaggerUI(option =>
            {
                option.SwaggerEndpoint(virtualPath + "/swagger/v1/swagger.json", "V1 Docs");
                // option.SwaggerEndpoint(virtualPath + "/swagger/v2/swagger.json", "V2 Docs");
                option.RoutePrefix = string.Empty;
                option.DocumentTitle = "WEBAPI";
            });
            app.UseHttpsRedirection();

            app.UseCors("CorsAdmin");

            app.UseAuthorization();

   
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
                endpoints.MapControllers();
            });
        }
    }
}

**Comment by hueifeng** [comment]
`Controller`内如何写的？

**Comment by 15801824890** [comment]
![image](https://user-images.githubusercontent.com/21243328/117906469-8f954700-b307-11eb-8100-ebf35a7fdbc9.png)
![image](https://user-images.githubusercontent.com/21243328/117906511-a471da80-b307-11eb-9a3e-9ce79a349d4e.png)
不好意思我试了下还是不行
![image](https://user-images.githubusercontent.com/21243328/117906681-fa468280-b307-11eb-82a4-2990f3481460.png)



> @15801824890 Hi,我在你仓库提交了一个PR。
> 
> ```
> //setupAction.ReturnHttpNotAcceptable = true;
> ```

**Comment by hueifeng** [comment]
@15801824890 谢谢你测试，通过如下片段是可以
```
setup.Filters.Add(typeof(MagicodesFilter));
```
但是通过`app.UseMagiCodesIE();`正如issue中提出的问题一样。

这个问题我排查一下。

**Comment by 15801824890** [comment]
有解决的办法吗╭(●｀∀´●)╯╰(●’◡’●)╮ (●’◡’●)ﾉ ヾ(*´▽‘*)ﾉ

**Comment by hueifeng** [comment]
先通过`setup.Filters.Add(typeof(MagicodesFilter));`使用，中间件的问题等等我去处理一下

**Comment by hueifeng** [comment]
您可以更新到2.5.4.1版本，在该版本修复了此问题。
