### ISSUE TITLE
能否实现多个Sheet模板导出？

### ISSUE THREAD

**Issue by archerzhaopan** [dotnetcore/Magicodes.IE#267]
在Excle中 ，能否实现多个Sheet模板导出？

 比如sheet1 是一个模板，sheet2是一个模板，然后 各自赋值

**Comment by hueifeng** [comment]
@archerzhaopan 分栏、分sheet、追加rows导出 
```
exporter.Append(list1).SeparateByColumn().Append(list2).ExportAppendData(filePath);
exporter.Append(list1).SeparateBySheet().Append(list2).ExportAppendData(filePath);
exporter.Append(list1).SeparateByRow().AppendHeaders().Append(list2).ExportAppendData(filePath);
```
对追加sheet实现同一个Model可自定义传入不同sheet名称
exporter.Append(list1,"sheet1").SeparateBySheet().Append(list2).ExportAppendData(filePath);

**Comment by 298029lkk** [comment]
请问下我引用了Magicodes.IE.Excel库，为什么没有Append方法，exporter中只有Export方法。
