### ISSUE TITLE
模板导出图片太慢了，800条数据，有图片的120条数据，导了一个时，如果时间这么久，感觉没有意义了。。。

### ISSUE THREAD

**Issue by ijlynivfhp** [dotnetcore/Magicodes.IE#270]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ijlynivfhp** [comment]
能不能优化下，800条数据，几分钟，10来分钟还可以，现在这时间，没法用，单线程导的话，一个线程阻塞，后面都等吧。

**Comment by hueifeng** [comment]
收到，我们优化一下

**Comment by ijlynivfhp** [comment]
大佬能快些吗，这两天就上线了，很期待啊

**Comment by ijlynivfhp** [comment]
导出图片四百张图片，一张按5秒算，也半个小时够了，这有点长，实际网络请求下载一张图片应该用不了一秒吧。

**Comment by ijlynivfhp** [comment]
明天晚上上线，现在做的异步导出，单线程导，带图片的一旦支持，卡一个小时，就不能用，，，先谢谢了。

**Comment by ijlynivfhp** [comment]
不是400条数据，是只有一百条有图片的数据。

**Comment by hueifeng** [comment]
图片分别都是不同地址下的网络图？关于这个问题，我需要先复现一下，我们需要掌握耗时在什么地方，或者说如果您能给出一份数据如JSON、XML都是可以的。

**Comment by ijlynivfhp** [comment]
JSON数据打包，实际应用厂景，800多条数据，100多条带图片的，按导出模板导出，实际时间1小时，还有一次是30多分钟。

**Comment by ijlynivfhp** [comment]
已通过邮件发送给你，导出所用json数据，还有excel模板。

**Comment by ijlynivfhp** [comment]
麻烦大佬看一下。

**Comment by ijlynivfhp** [comment]
或者你加下我QQ,380726211,等着用，谢谢大佬

**Comment by wulienen** [comment]
docker 中运行导出1条带图片的数据都非常的慢，windows下秒导
