### ISSUE TITLE
导出的BUG

### ISSUE THREAD

**Issue by iceteacqx** [dotnetcore/Magicodes.IE#271]
[SqlSugar.SugarColumn(IsIgnore = true)]
        [ImporterHeader(IsIgnore =true)]
        public List<t_supplier_class> supplier_Classes { get; set; } = new List<t_supplier_class>();
        
        xxxxxxxx
          await exporter.Export<T>(path, data);|
          然后导出的时候
           Type of value has a mismatch with column typeCouldn't store <System.Collections.Generic.List`1[Supplier.model.t_supplier_class]> in supplier_Classes Column.  Expected type is List`1.
           好像 IsIgnore 没有起作用

**Comment by hueifeng** [comment]
> Type of value has a mismatch with column typeCouldn't store <System.Collections.Generic.List`1[Supplier.model.t_supplier_class]> in supplier_Classes Column. 

The problem appears to have occurred during storage. Since the customer has not responded to this problem, close it first, and re-open it if there is a problem.

**Comment by iceteacqx** [comment]
> 经过测试，没有复现这个问题。可能需要提供更多信息。

我要提供什么？

**Comment by Nokecy** [comment]
有同样的问题 ，导出属性中有列表  使用IsIgnore  也没用
