### ISSUE TITLE
Excel导出导出对ValueMappingAttribute的支持问题

### ISSUE THREAD

**Issue by xl-wenqiang** [dotnetcore/Magicodes.IE#272]
目前在Excel导出时，不支持以下枚举值映射方式：
[ValueMapping("男", 0)] 
[ValueMapping("女", 1)]
仅支持：
 [ValueMapping("男", “man”)] 
而在导入时，则是反过来，即必须是：
        [ValueMapping("男", 0)]
        [ValueMapping("女", 1)]
而不是：
        [ValueMapping("男", “Man”)]
        [ValueMapping("女", “Female”)]

**Comment by xl-wenqiang** [comment]
群里反馈：
[ValueMapping("男", 0)]
导入没问题，导出模板也没问题
导出数据时，值还是0  而不是男

**Comment by hueifeng** [comment]
经验证在ValueMapping非字符串的情况下，可以返回对应的值。
https://github.com/dotnetcore/Magicodes.IE/blob/master/src/Magicodes.ExporterAndImporter.Tests/ExcelExporter_Tests.cs#L758
关于此处
Import 
```
[ValueMapping("男", 0)]
```

Export

```
[ValueMapping("男", 0)]
```
可正常使用，所以关闭此issue。
