### ISSUE TITLE
导出设置列宽为0无效。

### ISSUE THREAD

**Issue by Walnutr** [dotnetcore/Magicodes.IE#273]
需求上，当我设置列宽为0的时候代码直接跳过了设置列宽（看过源码，确认跳过设置列宽，并且列宽默认值就是0）

**Comment by hueifeng** [comment]
> 需求上，当我设置列宽为0的时候代码直接跳过了设置列宽

在width属性为0的情况下，不会设置width。

> 看过源码，确认跳过设置列宽，并且列宽默认值就是0

建议补充，没有明确问题

**Comment by Walnutr** [comment]
当我在exporterHeader上设置Width=0的时候。这个width没起用。在源码的ExportHelper.AddStyle方法内
`//设置单元格宽度
                    var width = exporterHeader.ExporterHeaderAttribute.Width;
                    if (width > 0)
                    {
                        col.Width = width;
                    }`   直接就跳过了。可以更改么?

**Comment by Walnutr** [comment]
当我在exporterHeader上设置Width=0的时候。这个width没起用。在源码的ExportHelper.AddStyle方法内
`//设置单元格宽度
                    var width = exporterHeader.ExporterHeaderAttribute.Width;
                    if (width > 0)
                    {
                        col.Width = width;
                    }`   
直接就跳过了。可以更改么?

**Comment by Walnutr** [comment]
当我在exporterHeader上设置Width=0的时候。这个width没起用。在源码的ExportHelper.AddStyle方法内
> //设置单元格宽度
                    var width = exporterHeader.ExporterHeaderAttribute.Width;
                    if (width > 0)
                    {
                        col.Width = width;
                    } 

直接就跳过了。可以更改么?

**Comment by hueifeng** [comment]
你的需求是什么？设置为0？

**Comment by Walnutr** [comment]
隐藏列功能,某些数据不好直接展示，但是导入的时候又需要跟据这些数据（比如说ID之类的）去做处理，隐藏列就是一个比较好的处理方式

**Comment by hueifeng** [comment]
可以选择忽略，将其不导出。或者可以选择动态形式，以过滤器的形式。

https://docs.xin-lai.com/2020/09/21/%E7%BB%84%E4%BB%B6/Magicodes.IE/Magicodes.IE%E4%B9%8B%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA%E7%AD%9B%E9%80%89%E5%99%A8/

**Comment by Walnutr** [comment]
我们以前的代码均是隐藏列，如果因为换导出框架而要大动代码的话，不现实，虽然只是一个小小的更动。但是其涉及到的代码量太了。如果方便的话可以予以支持隐藏列吗?

**Comment by hueifeng** [comment]
在Attribute中，如果我们将其设置为Nullable类型，其不允许TargetProperty，只能以参数的形式传递Attribute对象。另外我们要注意的是如果我们设置为Nullable，那么给我们其他消费者将带来灾难，再其使用中如果有不设置width值的，其将使用默认值null，将导致列隐藏。

**Comment by Walnutr** [comment]
好的，非常感谢。

**Comment by hueifeng** [comment]
@Walnutr 我发布了2.5.4.0版本，您可以通过ExporterHeaderAttribute增加Hidden属性进行隐藏
