### ISSUE TITLE
请问导出支持固定列宽自动换行功能吗？

### ISSUE THREAD

**Issue by wlclass** [dotnetcore/Magicodes.IE#278]
导出时通过ExporterHeader的Width设置列宽，但超出的字符会被隐藏，请问有支持自动换行功能吗？
在文档上没有看到相关的介绍，是我没有找到地方吗？
非常感谢这个优秀的项目。

**Comment by hueifeng** [comment]
我发布了2.5.4.0版本，您可以通过ExporterHeaderAttribute增加WrapText属性进行设置换行

**Comment by wlclass** [comment]
非常感谢
