### ISSUE TITLE
Excel支持图片导入导出

### ISSUE THREAD

**Issue by xin-lai** [dotnetcore/Magicodes.IE#28]

**Comment by Nongzhsh** [comment]
这里的"支持图片导入导出"是指处理单元格中的图片吗？

**Comment by xin-lai** [comment]
> 这里的"支持图片导入导出"是指处理单元格中的图片吗？

对的。

**Comment by xin-lai** [comment]
Excel图片导入导出已在develop分支完成检查和重构。感谢 @hueifeng。目前已通过线上构建，已合并到master进行发版。主要内容如下：
- **【Excel导入】支持图片导入，见特性ImportImageFieldAttribute**
  - 导入为Base64
  - 导入到临时目录
  - 导入到指定目录
- **【Excel导出】支持图片导出，见特性ExportImageFieldAttribute**
  - 将文件路径导出为图片
  - 将网络路径导出为图片
