### ISSUE TITLE
ubuntu 18.04下导出图片失败

### ISSUE THREAD

**Issue by zhdwwf** [dotnetcore/Magicodes.IE#285]
在ubuntu 18.04下使用模板导出图片失败，同一个程序在windows下导出正常，请问ubuntu下是需要专门配置什么吗？已安装 libgdiplus

**Comment by hueifeng** [comment]
> 请问ubuntu下是需要专门配置什么吗？
可以参考Dockerfile
```
# 如不使用上述基础镜像，那么需要添加以下命令来安装libgdiplus库，用于Excel导出
RUN apt-get update && apt-get install -y libgdiplus libc6-dev
RUN ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll
```
在上述处理完后，还不能解决您的问题，我建议您附加一下错误明细信息.

**Comment by zhdwwf** [comment]
谢谢您的回复，我遇到的问题比较奇怪，程序没有报任何错误，执行后程序卡住无响应，一直处于处理中的状态，查看进程，cpu使用100%，程序代码如下：
```csharp
    class Program
    {
        static async Task Main(string[] args)
        {
            IExporter exporter = new ExcelExporter();
            var data = new List<ExportTestDataWithPicture>();
            data.Add(new ExportTestDataWithPicture
            {
                Img = "http://image-demo.oss-cn-hangzhou.aliyuncs.com/example.jpg"
            });

            var filePath = Path.Combine(AppContext.BaseDirectory, "test.xlsx");
            var result = await exporter.Export(filePath, data);
            Console.WriteLine(result.FileName);
        }
    }

    [ExcelExporter(Name = "测试")]
    public class ExportTestDataWithPicture
    {
        [ExportImageField(Width = 50, Height = 120, Alt = "404")]
        [ExporterHeader(DisplayName = "图", IsAutoFit = false)]
        public string Img { get; set; }
    }
```
执行后的情况：
![image](https://user-images.githubusercontent.com/564279/122351410-af600080-cf80-11eb-8ae2-1b1c635df95c.png)
![image](https://user-images.githubusercontent.com/564279/122351493-c30b6700-cf80-11eb-81b2-95c7bb192f80.png)
同样的程序在windows下可以正常生成Excel，Ubuntu下已经安装了libgdiplus、libc6-dev并且做了软链接，这种问题根据您的经验有可能是哪里引起的呢？

**Comment by hueifeng** [comment]
您可以通过WSL2进行调试，也可以将这个测试项目上传，我这边看一下。

**Comment by xin-lai** [comment]
我们测试一下。

**Comment by zhdwwf** [comment]
测试项目地址：[https://github.com/zhdwwf/ExcelExportDemo](https://github.com/zhdwwf/ExcelExportDemo)
ubuntu环境是：阿里云ECS，Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-88-generic x86_64)
接下来我在win10的WSL2下测试一下， @hueifeng @xin-lai 您二位方便的话也可以用上边项目地址测试下，非常感谢!

**Comment by xl-wenqiang** [comment]
![image](https://user-images.githubusercontent.com/22266819/122416273-2e722a80-cfbb-11eb-8891-7ec13d3af0ff.png)

**Comment by xl-wenqiang** [comment]
https://www.nuget.org/packages/Magicodes.IE.Tools/

> dotnet tool install --global Magicodes.IE.Tools --version 0.0.3

**Comment by xl-wenqiang** [comment]
代码见：https://github.com/dotnetcore/Magicodes.IE/blob/develop/src/Magicodes.IE.Tools/Program.cs

**Comment by zhdwwf** [comment]
测试了您的示例代码和mie test，对比了我的代码，发现问题出在图片格式上，如果是png图片，导出成功，jpg图片程序就会卡死，测试代码如下(已同步更新到 [https://github.com/zhdwwf/ExcelExportDemo/blob/master/ExcelExportDemo/Program.cs](https://github.com/zhdwwf/ExcelExportDemo/blob/master/ExcelExportDemo/Program.cs))
```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Magicodes.ExporterAndImporter.Core;
using Magicodes.ExporterAndImporter.Excel;

namespace ExcelExportDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            string format=args[0];
            string img=format.ToLower() == "png" ? "https://gitee.com/magicodes/Magicodes.IE/raw/master/docs/Magicodes.IE.png" : "https://gitee.com/magicodes/Magicodes.IE/raw/master/res/wechat.jpg";
            IExporter exporter = new ExcelExporter();

            var data = new List<ExportTestDataWithPicture>
            {
                new ExportTestDataWithPicture
                {
                    Img =img
                }
            };

            var filePath = Path.Combine(System.IO.Directory.GetCurrentDirectory(), "test.xlsx");
            var result = exporter.Export("test.xlsx", data).Result;
            Console.WriteLine("导出成功！");
        }
    }

    [ExcelExporter(Name = "测试")]
    public class ExportTestDataWithPicture
    {
        [ExportImageField(Width = 50, Height = 120, Alt = "404")]
        [ExporterHeader(DisplayName = "图", IsAutoFit = false)]
        public string Img { get; set; }
    }
}


```

测试结果见图：
![test](https://user-images.githubusercontent.com/564279/122490020-8f2d5180-d013-11eb-8264-9618f38f978f.gif)

**Comment by xin-lai** [comment]
收到，非常感谢，我再试试。

**Comment by xin-lai** [comment]
确实存在这个问题。

**Comment by zhdwwf** [comment]
在WSL下调试发现JPG图片没能成功取到图片的HorizontalResolution、VerticalResolution导致while循环一直在执行，代码文件：
[https://github.com/xin-lai/Magicodes.EPPlus/blob/479c8f7a08c35bba49d8d7ea2804edba352ce2a6/EPPlus/Drawing/ExcelPicture.cs#L262](https://github.com/xin-lai/Magicodes.EPPlus/blob/479c8f7a08c35bba49d8d7ea2804edba352ce2a6/EPPlus/Drawing/ExcelPicture.cs#L262)
```csharp
        
        private void SetPosDefaults(Image image)
        {
            EditAs = eEditAs.OneCell;
            SetPixelWidth(image.Width, image.HorizontalResolution);
            SetPixelHeight(image.Height, image.VerticalResolution);
        }
```
此处的HorizontalResolution和VerticalResolution均为0，搜了一下此问题，发现libgdiplus下有issue提到
mono/libgdiplus#611
但我使用了新版本的libgdiplus依然获取不到，这里是否能够把获取图片分辨率改为固定值呢，比如使用定义的这个标准DPI
```csharp
const float STANDARD_DPI = 96;
```

**Comment by xin-lai** [comment]
收到，非常感谢，我们尽量尽快处理！

**Comment by hueifeng** [comment]
目前我们发布了`2.5.4.3`现在您可以更新到最新版本，该问题已在该版本修复

**Comment by zhdwwf** [comment]
感谢您的工作，我升级一下
