### ISSUE TITLE
excel导出

### ISSUE THREAD

**Issue by wsiscool** [dotnetcore/Magicodes.IE#290]
在excle导出的时候，如何设置指定列的字体颜色，应用场景是，导出失败的excel，并将异常提示列标红

**Comment by hueifeng** [comment]
> 导出失败的excel

似乎您指的是导入Excel？目前导入是存在结果筛选器的，详情[Magicodes.IE之导入导出筛选器](https://docs.xin-lai.com/2020/09/21/%E7%BB%84%E4%BB%B6/Magicodes.IE/Magicodes.IE%E4%B9%8B%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA%E7%AD%9B%E9%80%89%E5%99%A8/)。

**Comment by xin-lai** [comment]
目前仅支持导入的验证和标记，对于导出，需要在导出完成后，调用EPPlus的API再次处理。
