### ISSUE TITLE
导出模板后，在手动给某列添加数据下拉项，导致模板无法正常使用，

### ISSUE THREAD

**Issue by crashsol** [dotnetcore/Magicodes.IE#293]
老版本2.3.0没有问题，2.5.4出了问题

> IImporter Importer = new ExcelImporter();
  var temp = await Importer.GenerateTemplateBytes<DrillOpsStringsStructureImportDto>();
  var mockeSelctItems = new List<string> { "测试一", "测试二", "测试三" };
            // TODO: 添加真实的下拉数据，添加后，  模板会出问题
            using (var stream = new MemoryStream(temp))
            {
                using (var package = new ExcelPackage(stream))
                {
                    var sheet = package.Workbook.Worksheets.FirstOrDefault();
                    var listSheet = package.Workbook.Worksheets.Add("业务分类");
                    listSheet.Hidden = eWorkSheetHidden.Hidden;
                    int rowIndex = 1;
                    foreach (var item in mockeSelctItems)
                    {
                        listSheet.Cells[rowIndex, 1].Value = item;
                        rowIndex++;
                    }
                    var validation = sheet.DataValidations.AddListValidation("A2:A10000");
                    validation.ShowErrorMessage = false;
                    validation.ErrorStyle = ExcelDataValidationWarningStyle.warning;
                    validation.ErrorTitle = "输入得值无效";
                    validation.Error = "请选择所属分类";
                    //validation.Formula.ExcelFormula = $"=OFFSET(业务分类!$A$1,MATCH(\"*\"&A2&\"*\",业务分类!$A:$A,0)-1,,COUNTIF(业务分类!$A:$A,\"*\"&A2&\"*\"),)";
                    validation.Formula.ExcelFormula = $"业务分类!$A$1:$A${rowIndex - 1}";
                    return package.GetAsByteArray();
                }
            }

![微信图片_20210626115555](https://user-images.githubusercontent.com/17925647/123501170-84a73380-d675-11eb-9c5b-439f25dd337b.png)
![微信图片_20210626115601](https://user-images.githubusercontent.com/17925647/123501172-87a22400-d675-11eb-8a3e-dfe96e187ba3.png)

**Comment by xl-wenqiang** [comment]
这个问题确实挺奇怪。

**Comment by xl-wenqiang** [comment]
已修复。试试：2.5.4.8
