### ISSUE TITLE
当导入的数据不符合模版校验规则(自定义校验,自定义添加错误信息)返回的文件样式错误

### ISSUE THREAD

**Issue by DUWENINK** [dotnetcore/Magicodes.IE#297]
当模版校验不通过的时候 所有的返回的模版都会变形

![6CXWOVHLUMGB XVOJLXAVV4](https://user-images.githubusercontent.com/16337239/124371382-dc681f00-dcb3-11eb-9d05-0591439e22ba.png)
![Z% HOB)YZRLU41KR(OSYYB9](https://user-images.githubusercontent.com/16337239/124371383-deca7900-dcb3-11eb-97b2-a9e6bbcb184f.jpg)

**Comment by xl-wenqiang** [comment]
@DUWENINK 方便提供下Demo不？

**Comment by hueifeng** [comment]
还有这个#293，这似乎是同一个问题

**Comment by xl-wenqiang** [comment]
试试 2.5.4.8
