### ISSUE TITLE
是否支持输出excel到浏览器？？？

### ISSUE THREAD

**Issue by yunjie-yao** [dotnetcore/Magicodes.IE#300]
### 业务场景
前端调用API，浏览器里直接返回文件下载到用户本地。

目前测试使用中发现文件都是直接保存在服务器，是不是我的使用方式有问题？

**Comment by xl-wenqiang** [comment]
建议基于API自行包装实现下载。
当然IE也封装了简便的方式：
[Magicodes.IE.AspNetCore之一行代码多格式导出](https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/12.Magicodes.IE.AspNetCore%E4%B9%8B%E4%B8%80%E8%A1%8C%E4%BB%A3%E7%A0%81%E5%A4%9A%E6%A0%BC%E5%BC%8F%E5%AF%BC%E5%87%BA.md)
