### ISSUE TITLE
标记错误Excel出现斜线

### ISSUE THREAD

**Issue by linch90** [dotnetcore/Magicodes.IE#301]
### Actual behaviour
![image](https://user-images.githubusercontent.com/1113475/125564712-a685bbb1-8c80-4e53-9b47-65b72d43bee6.png)

### I'm seeing this behaviour on
Magicodes.IE.Excel

#### package versions
Magicodes.IE.Excel 2.5.4.6

环境：.net 5

### So how can we reproduce this?
升级到新版本后，导出标记错误的EXCEL，每行数据都会出现斜线

**Comment by xl-wenqiang** [comment]
试试 2.5.4.8

**Comment by linch90** [comment]
@xl-wenqiang 感谢，新版本测试已无斜线问题
