### ISSUE TITLE
csv模板生成下载，身份证号这种长数字会默认使用科学计数法 设置Format无效

### ISSUE THREAD

**Issue by guoyiwen** [dotnetcore/Magicodes.IE#303]
我试了用CsvExporter设置Format无效,用ExcelExporter导出设置Format没有问题

**Comment by guoyiwen** [comment]
csv设置Format 时间也无效 
[ExporterHeader(DisplayName = "交易时间",Format = "yyyy-MM-dd HH:mm")]
public DateTime? TranStartTs { get; set; }

**Comment by xl-wenqiang** [comment]
csv不支持Format，因为其充其量就是个逗号分隔的文本。

**Comment by xl-wenqiang** [comment]
对于长数值，建议导出时在数值前添加英文单引号。
