### ISSUE TITLE
MagicodesFilter有问题

### ISSUE THREAD

**Issue by Rourss** [dotnetcore/Magicodes.IE#310]
### Expected behaviour
我这里想返回这个
![image](https://user-images.githubusercontent.com/47970410/128453613-5a2e964b-1521-4108-ac2f-f755c8c8f4b5.png)

以下是测试报告：
API接口添加特性，返回的是数组，可以正常返回
API接口添加特性，返回单个对象，可以正常返回

API接口未添加特性，返回的是数组，什么都没有
API接口未添加特性，返回单个对象，什么都没有
### Actual behaviour
实际上并没有返回，什么都没有
![image](https://user-images.githubusercontent.com/47970410/128453658-d4ccf8bb-9d33-48ef-8d2d-8aecc444d609.png)

#### package versions
Magicodes.IE.AspNetCore-2.5.4.9版本

### So how can we reproduce this?
使用Filter，接口不添加特性标记，发起请求，没有结果返回
使用Filter，接口添加特性标记，发起请求，有结果返回

#### Meh :star::star:
以上问题在添加next后可以正常返回
![image](https://user-images.githubusercontent.com/47970410/128453770-fc8bb427-7696-45d9-ba53-07211d03aa48.png)

**Comment by xl-wenqiang** [comment]
接口Demo代码方便贴一下么？

**Comment by hueifeng** [comment]
好的感谢，该判断中忽略的中间件的执行（让该方法处理时没有继续往下执行，我们修改一下。

**Comment by hueifeng** [comment]
该问题已处理
