### ISSUE TITLE
Magicodes.IE.Excel 导入，自2.5.4.1版本开始，导入含多层边框的excel会报错

### ISSUE THREAD

**Issue by ZoeyuYK** [dotnetcore/Magicodes.IE#313]
Magicodes.IE.Excel 导入，自2.5.4.1版本开始，导入含多层边框的excel会报错。
提示模板出现未知错误：System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')

**Comment by ZoeyuYK** [comment]
@xin-lai 谢谢

**Comment by ZoeyuYK** [comment]
是否是Magicodes.EPPlus部分的问题？

**Comment by xl-wenqiang** [comment]
对，应该是前一段时间改了Magicodes.EPPlus导致的。我们还需要时间排查。
