### ISSUE TITLE
Can u add delimiter option for Export CSV?

### ISSUE THREAD

**Issue by hendxxx** [dotnetcore/Magicodes.IE#319]
Please add delimiter option while export CSV, for example sometimes user want to CSV with ; instated of ,

example of use:

var result = await exporter.ExportAsByteArray(mquery, ";");

**Comment by xl-wenqiang** [comment]
收到，感谢建议！
Thanks for the suggestion ！

**Comment by xl-wenqiang** [comment]
已发布到2.6.0
