### ISSUE TITLE
希望增加对导入模板、错误消息，标注、枚举项的多语言支持

### ISSUE THREAD

**Issue by netty2019** [dotnetcore/Magicodes.IE#32]
我尝试了继承ExporterHeaderAttribute特性，重写DisplayName的Get方法，加了一层翻译字符串的方法，但是不起作用，
能否考虑在后台反射获取特性的时候，可以获取继承的特性，谢谢

**Comment by netty2019** [comment]
不好意思，我看到2.0测试版中提供了一个IExporterHeaderFilter过滤器可以实现多语言。
另外提一点小建议：
1.能否将ExcelExporter特性的Name属性也加进去，这样就能对Sheet的名称进行翻译
2.导入的时候是否也可以加一个过滤器，这样可以对生成的模板进行多语言翻译

**Comment by xin-lai** [comment]
OK  这些有考虑，需要抽时间重构并支持
同时也需要更多人参与进来才行

**Comment by netty2019** [comment]
好的，等你重构完，我也可以贡献代码

**Comment by xin-lai** [comment]
- 支持导入结果筛选器——IImportResultFilter，可用于多语言场景的错误标注，具体使用见单元测试【ImportResultFilter_Test】

- 即将添加值映射筛选器和导入列头筛选器

**Comment by netty2019** [comment]
谢谢，已经看到了

**Comment by xin-lai** [comment]
导入列筛选器也添加了，具体可以看单元测试。
