### ISSUE TITLE
导出Excel数据表格

### ISSUE THREAD

**Issue by shiyi-lab** [dotnetcore/Magicodes.IE#329]
![image](https://user-images.githubusercontent.com/56857231/132799076-de641054-8180-49d2-a591-4d61751fa1d7.png)
第一：日期格式不生效

**Comment by shiyi-lab** [comment]
第二：导出数据，不能选择导出类型

**Comment by shiyi-lab** [comment]
我想问的是，我格式化，只要年月日，但是我导出的时候还是会把时分秒带出来

**Comment by ThreeLambs** [comment]
咋还没修好，不维护了吗

**Comment by xl-wenqiang** [comment]
此问题已修复，请使用最新版本测试。
