### ISSUE TITLE
可以打印pdf文件吗？

### ISSUE THREAD

**Issue by 5653325** [dotnetcore/Magicodes.IE#33]
比如生成了pdf（或现有的pdf文件），可以推送给打印机吗？

**Comment by xin-lai** [comment]
生成PDF后，唤起打印是客户端的事情，目前不在本库的考虑范围。

**Comment by 5653325** [comment]
生成pdf的库很多，但可以打印pdf的库很少。
希望可以考虑下增加以下。
谢谢

**Comment by xin-lai** [comment]
> 生成pdf的库很多，但可以打印pdf的库很少。
> 希望可以考虑下增加以下。
> 谢谢

相关场景方便介绍下不？

**Comment by 5653325** [comment]
> > 生成pdf的库很多，但可以打印pdf的库很少。
> > 希望可以考虑下增加以下。
> > 谢谢
> 
> 相关场景方便介绍下不？

比如有个服务（或者客户端）把生成的pdf文件，推送给打印机。
