### ISSUE TITLE
使用 Magicodes特性导出时，ValueMapping特性无效

### ISSUE THREAD

**Issue by YaChengMu** [dotnetcore/Magicodes.IE#337]
![QQ图片20210918113004](https://user-images.githubusercontent.com/9545729/133871182-36771099-ba58-4262-96b8-939075379892.png)
![QQ图片20210918113011](https://user-images.githubusercontent.com/9545729/133871187-ae3ff1f5-4c34-441a-9e88-d549e60c7793.png)
![QQ图片20210918113017](https://user-images.githubusercontent.com/9545729/133871190-9f81aea4-1b9e-4bf7-802c-6d5f7ec40f87.png)

**Comment by xl-wenqiang** [comment]
![_1%}`}~@F61AMKL~PQNZ59T](https://user-images.githubusercontent.com/22266819/133871582-36cf8c91-d6bf-4ab7-ad40-a5b50be64c39.png)
未复现此问题

**Comment by YaChengMu** [comment]
仅在使用Magicodes特性导出时存在bug，
![QQ截图20210918140612](https://user-images.githubusercontent.com/9545729/133878167-8b62ab0b-fc69-4829-a1ae-523aa4d77f5b.png)
这样导出的时候正常。

**Comment by xl-wenqiang** [comment]
收到

**Comment by wensaint** [comment]
> 仅在使用Magicodes特性导出时存在bug，
> ![QQ截图20210918140612](https://user-images.githubusercontent.com/9545729/133878167-8b62ab0b-fc69-4829-a1ae-523aa4d77f5b.png)
> 这样导出的时候正常。

我用这个方法导出时，一样错误。
[ExporterHeader(DisplayName = "是否校友")]
[ValueMapping("是", true)]
[ValueMapping("否", false)]
public bool? IsAlumni { get; set; }

导出后，单元格内容为"TRUE"或"FALSE"

**Comment by wensaint** [comment]
测试过的版本：2.5.4.1、2.5.4.6、2.5.5.4。均存在问题
数据导出方法：
/// <summary>
        /// 数据导出
        /// </summary>
        /// <returns></returns>
        [ApiPermissionIngore]
        [HttpGet("Export")]
        public async Task<ActionResult> Export()
        {
            var filePath = $"数据导出{DateTime.Now:yyyyMMdd}.xlsx".UrlEncode();
            var list = await _service.GetListAsync();
            if(list==null)
                throw new BusException("没有可导出数据");

            var exporter = new ExcelExporter();
            var file= await exporter.ExportAsByteArray(list);
            return File(file,FileHelper.GetContentType(filePath),filePath);
        }

Dto：
[ExcelExporter(Name = "导出结果", TableStyle = OfficeOpenXml.Table.TableStyles.None)]
    public class ParttimeTutorExportDto{
        
        /// <summary>
        /// 名称
        /// </summary>
        [ExporterHeader(DisplayName = "姓名")]
        public string Name { get; set; }
        
        /// <summary>
        /// 性别
        /// </summary>
        [ExporterHeader(DisplayName = "性别")]
        public string Gender { get; set; }
        
        /// <summary>
        /// 是否校友
        /// </summary>
        [ExporterHeader(DisplayName = "是否校友")]
        [ValueMapping("是", true)]
        [ValueMapping("否", false)]
        public bool? IsAlumni { get; set; }
}

**Comment by wensaint** [comment]
测试过的版本：2.5.4.1、2.5.4.6、2.5.5.4。均存在问题
数据导出方法：
```
/// <summary>
        /// 数据导出
        /// </summary>
        /// <returns></returns>
        [ApiPermissionIngore]
        [HttpGet("Export")]
        public async Task<ActionResult> Export()
        {
            var filePath = $"数据导出{DateTime.Now:yyyyMMdd}.xlsx".UrlEncode();
            var list = await _service.GetListAsync();
            if(list==null)
                throw new BusException("没有可导出数据");

            var exporter = new ExcelExporter();
            var file= await exporter.ExportAsByteArray(list);
            return File(file,FileHelper.GetContentType(filePath),filePath);
        }
```

Dto：
```
[ExcelExporter(Name = "导出结果", TableStyle = OfficeOpenXml.Table.TableStyles.None)]
    public class ParttimeTutorExportDto{
        
        /// <summary>
        /// 名称
        /// </summary>
        [ExporterHeader(DisplayName = "姓名")]
        public string Name { get; set; }
        
        /// <summary>
        /// 性别
        /// </summary>
        [ExporterHeader(DisplayName = "性别")]
        public string Gender { get; set; }
        
        /// <summary>
        /// 是否校友
        /// </summary>
        [ExporterHeader(DisplayName = "是否校友")]
        [ValueMapping("是", true)]
        [ValueMapping("否", false)]
        public bool? IsAlumni { get; set; }
}
```

**Comment by xl-wenqiang** [comment]
跟踪发现，目前不支持bool？的ValueMapping，建议暂时使用bool，接下来我们会尽快处理

**Comment by xl-wenqiang** [comment]
试试 v2.5.6.1

**Comment by YaChengMu** [comment]
> 试试 v2.5.6.1

问题依然存在。

**Comment by YaChengMu** [comment]
我修改了一下项目中的测试用例

    [ExcelExporter(Name = "测试", TableStyle = TableStyles.Light10, AutoFitAllColumn = true)]
    public class ExportTestDataWithAttrs
    {

        [ExporterHeader(DisplayName = "加粗文本", IsBold = true)]
        public string Text { get; set; }
        [ExporterHeader(DisplayName = "普通文本")] public string Text2 { get; set; }
        [ExporterHeader(DisplayName = "忽略", IsIgnore = true)]
        public string Text3 { get; set; }
        [ExporterHeader(DisplayName = "数值", Format = "#,##0")]
        public decimal Number { get; set; }
        [ExporterHeader(DisplayName = "名称", IsAutoFit = true)]
        public string Name { get; set; }

        /// <summary>
        /// 时间测试
        /// </summary>
        [ExporterHeader(DisplayName = "日期1", Format = "yyyy-MM-dd")]
        public DateTime Time1 { get; set; }

        /// <summary>
        /// 时间测试
        /// </summary>
        [ExporterHeader(DisplayName = "日期2", Format = "yyyy-MM-dd HH:mm:ss")]
        public DateTime? Time2 { get; set; }

        public DateTime Time3 { get; set; }

        public DateTime Time4 { get; set; }

        /// <summary>
        /// 长数值测试
        /// </summary>
        [ExporterHeader(DisplayName = "长数值", Format = "#,##0")]
        public long LongNo { get; set; }
        [ExporterHeader(DisplayName = "性别", Format = "#,##0")]
        [ValueMapping("男",1)]
        [ValueMapping("女", 2)]
        [ValueMapping("未知", 3)]
        public Gender Sex { get; set; }
    }
    public enum Gender
    {
        /// <summary>
        /// 男
        /// </summary>
        [Description("男")]
        MALE = 1,

        /// <summary>
        /// 女
        /// </summary>
        [Description("女")]
        FEMALE = 2,

        /// <summary>
        /// 未知
        /// </summary>
        [Description("未知")]
        UNKNOWN = 3
    }
导出后的内容是这样的
![image](https://user-images.githubusercontent.com/9545729/136495589-a8b84c5e-c2ec-4170-b5ec-9c6eaf34eda6.png)

**Comment by xl-wenqiang** [comment]
不要使用 Magicodes特性，直接通过API导出 ，这个根据Content-Type导出的工程我们可能还要抽时间重构一下。也欢迎多多PR。
