### ISSUE TITLE
enum 枚举 继承 byte

### ISSUE THREAD

**Issue by moxixuan** [dotnetcore/Magicodes.IE#367]
### Expected behaviour
hi， 我有一个导入需要导入的dto，
里面有个枚举值，当这个枚举值继承byte的时候，返回了如下的错误类型，并且没有读到excel的值，
Object of type \'System.Int32\' cannot be converted to type Genders 
我想这个错误是在转换枚举的时候报错的，我可以做些什么吗？

```
    /// <summary>
    ///     性别
    /// </summary>
    public enum Genders : byte
    {
        /// <summary>
        ///     男
        /// </summary>
        Man = 0,

        /// <summary>
        ///     女
        /// </summary>
        Female = 1
    }
```
### I'm seeing this behaviour on
_Remove this hint: these checkboxes can be checked like this: [x]_
- [ ] Magicodes.IE.Excel

#### package versions
Example: Magicodes.IE.Excel.Abp 2.6.1

**Comment by moxixuan** [comment]
![图片](https://user-images.githubusercontent.com/19483437/147020550-1d3ad94f-6dcf-400c-9687-7928547e365a.png)

**Comment by moxixuan** [comment]
![图片](https://user-images.githubusercontent.com/19483437/147200898-cb70d524-4198-4785-8f55-2a8f7f572f08.png)

**Comment by xl-wenqiang** [comment]
> ![图片](https://user-images.githubusercontent.com/19483437/147200898-cb70d524-4198-4785-8f55-2a8f7f572f08.png)

能否麻烦提供一个PR，年底了比较忙。

**Comment by hueifeng** [comment]
已发布 2.6.5-beta1
