### ISSUE TITLE
建议在Excel导入时增加一个回调函数，方便做一些自定义的验证

### ISSUE THREAD

**Issue by netty2019** [dotnetcore/Magicodes.IE#368]
如下图这个样子的
![image](https://user-images.githubusercontent.com/47128297/148549196-ac202b1f-c863-46b1-a340-bb5abbe1bb92.png)

**Comment by xl-wenqiang** [comment]
能否PR一个，年底了要做年终总结和年度规划，忙的飞起。

**Comment by netty2019** [comment]
已提交

**Comment by xin-lai** [comment]
#369
