### ISSUE TITLE
XSSFWorkbook support

### ISSUE THREAD

**Issue by hendxxx** [dotnetcore/Magicodes.IE#373]
Excel file from export have difference file header

Picture bellow from magicode IE
![image](https://user-images.githubusercontent.com/6839640/150318001-3bea2b1c-0baf-4310-9e93-d7cccf2d7aca.png)

Picture bellow re-saved from msoffice
![image](https://user-images.githubusercontent.com/6839640/150318449-29d82bd9-9d73-444e-a33a-b9d3c0b63c77.png)

I have difficulty to upload magicode IE or EPPlus. After re-saved using NPIO the file is accepted with our API. Please add this feature at least using the latest file header with MS Office. Or for extreme solution add laternative NPIO not only EPPlus 😄, I love EPPlus but NPIO is good also.
 
Thanks !

**Comment by hendxxx** [comment]
This is from NPIO 
![image](https://user-images.githubusercontent.com/6839640/150340987-4df9e0af-e0fd-4970-9d21-db7e81471523.png)

**Comment by hendxxx** [comment]
For additional Info ,this from NPIO
![image](https://user-images.githubusercontent.com/6839640/150341176-9f213920-cb41-4154-a943-f70676aca9d5.png)

**Comment by hendxxx** [comment]
For additional Info, this picture bellow from NPIO file header with same data.
![image](https://user-images.githubusercontent.com/6839640/150341327-fb7de0bf-d793-499d-8321-2cd9ff9b2d7b.png)

**Comment by hueifeng** [comment]
@hendxxx would you like to contribute this change?

**Comment by hendxxx** [comment]
well ... i will try, 

may I use another lib for generate excel ? in this case we have EPPlus but also in my case NPIO is show correct value.

**Comment by xl-wenqiang** [comment]
> well ... i will try,
> 
> may I use another lib for generate excel ? in this case we have EPPlus but also in my case NPIO is show correct value.

no problem.
