### ISSUE TITLE
建议去掉System.Drawing.Common

### ISSUE THREAD

**Issue by 280780363** [dotnetcore/Magicodes.IE#375]
linux上非要安装libgdiplus是一个非常恶心的操作
建议使用ImageSharp等替代库

**Comment by hueifeng** [comment]
dup #357

**Comment by xin-lai** [comment]
影响范围比较大，需要慎重。

**Comment by langhaoabcd** [comment]
> 影响范围比较大，需要慎重。

这个库，libgdiplus(System.Drawing.Common)将很快被彻底废弃，请看一下这个文档
https://docs.microsoft.com/zh-cn/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only
