### ISSUE TITLE
导入模板能否生成一个Summary ,用于展示导入需要注意的一些要点

### ISSUE THREAD

**Issue by kasugaharu** [dotnetcore/Magicodes.IE#38]
**Is your feature request related to a problem? Please describe.**
在日常导入中,需要有一个导入说明提供查看当前导入模板的使用方法或者注意事项
In the daily Excel import, there needs to be an import specification that provides the usage or considerations for viewing the current Excel import template

**Describe the solution you'd like**
能否在导入模板生成的时候 在导入模型上指定一个标签用于填写导入说明,
并将导入说明 填充到Excel Sheet的第一行或进行醒目的展示
Can you specify a label on the Excel import model to fill in the import instructions when the import template is generated?
Fill in the first row of the Excel Sheet with the import instructions or make them  visible
Thanks U

**Comment by xin-lai** [comment]
这个建议不错，后续会支持。得抽精力。可以考虑自己PR，并不难。
大哥，英文不错啊，给我买写写英文文档呗。

**Comment by kasugaharu** [comment]
感谢回复~哈哈,有道加中式翻译的成果;
另外还有一个建议,最近碰到的导入问题:
导入处理 Excel时,一部分错误是Excel模板中定义的错误,还有一部分则是业务上的错误(e.g.存在重复的数据库唯一列,导入的某些数据非法....)
我们会把这些错误的数据返回给用户,一般来说会返回一个Excel文件告知用户导入的数据存在业务问题.
这时出现了一个问题:
我们进行导入操作验证完成后需要将上述的不满足系统业务的数据返回,此时需要进行一次导出操作
![image](https://user-images.githubusercontent.com/15976040/74799194-d534b100-530a-11ea-93f2-b5f21e3ab7ce.png)
生成的导入模板和此时的导出模板并不相同....
![image](https://user-images.githubusercontent.com/15976040/74799983-11691100-530d-11ea-8d20-44719f77f682.png)

能否够考虑对此时的错误数据使用导入模板导出返回给用户方便用户修改之后进行2次上传

**Comment by xin-lai** [comment]
有的。你看导出结果那个类，包含：
```csharp

        /// <summary>
        ///     验证错误
        /// </summary>
        public virtual IList<DataRowErrorInfo> RowErrors { get; set; }

        /// <summary>
        ///     模板错误
        /// </summary>
        public virtual IList<TemplateErrorInfo> TemplateErrors { get; set; }

        /// <summary>
        ///     导入异常信息
        /// </summary>
        public virtual Exception Exception { get; set; }
```

另外还支持生成错误标注文件，哪一行哪个数据报错都会标注。

**Comment by kasugaharu** [comment]
你好~
RowErrors  这个地方我知道
这里的错误是模型中定义的,当模型验证失败会返回一个Excel 同时标注模型上的错误.
![image](https://user-images.githubusercontent.com/15976040/74806620-6747b400-5321-11ea-8a0c-289cb3cc1c19.png)

而我的意思是,数据模型上数据验证已经通过,但是无法满足业务系统的需求的情况;
比如说 我们在导入用户数据的时候发现有一条数据已经存在于数据库中了,或者这条导入的数据某些字段在系统中关联的外键不存在...

这部分业务错误的数据需要我们返回给用户并提醒用户这些数据存在的问题;这个时候需要我们导出一份错误数据的Excel

这里最好是开放一个 生成错误标注文件的方法,提供手动生成并且补充 错误原因(业务错误)

**Comment by kasugaharu** [comment]
稍后 我PR一个版本 给您看看

**Comment by xin-lai** [comment]
收到。非常期待。
另外你刚说的可以基于筛选器来实现。有单元测试示例，教程好像还没写。
