### ISSUE TITLE
多ImportHeaderFilter注入，获取时，不符合预期。

### ISSUE THREAD

**Issue by applebananamilk** [dotnetcore/Magicodes.IE#382]
### Expected behaviour
![image](https://user-images.githubusercontent.com/37533208/156706950-79619ef8-879b-4c15-9568-b3a1b2ef93a2.png)
![image](https://user-images.githubusercontent.com/37533208/156706985-45356973-cb0b-45f6-87aa-2e60ca168d3a.png)
这样应该走`ImportHeaderFilterB`的`HeaderFilter`

### Actual behaviour
实际走的最后一个注入的`ImportHeaderFilterC`

### I'm seeing this behaviour on

-  Magicodes.IE.Excel

#### package versions
Example: Magicodes.IE.Excel 2.6.1

### So how can we reproduce this?
[Demo.zip](https://github.com/dotnetcore/Magicodes.IE/files/8183303/Demo.zip)

### Other
不知道用法是否对错？

不过源码是直接获取的。
![image](https://user-images.githubusercontent.com/37533208/156707231-35686e7e-28ea-47a5-9259-b298b5b3d4c2.png)
是否应该修改为：
![image](https://user-images.githubusercontent.com/37533208/156707456-41fd4000-3bae-4194-8d8d-0d76314c4188.png)
UPDATE. 图中判断类型修改为GetType() ==  filterType

**Comment by xin-lai** [comment]
@applebananamilk 看起来，你这边好像是混用了。
通过builder.Services.AddTransient<IImportHeaderFilter, ImportHeaderFilterA>()方式，筛选器是全局的
通过[ExcelImporter(ImportHeaderFilter = typeof(ImportHeaderFilterB))]方式，筛选器是局部的。
前者的优先级高于后者。

**Comment by applebananamilk** [comment]
> 
第二种会自动注入到容器吗？我的ImportHeaderFilterA和ImportHeaderFilterB都是需要从容器中构造使用。

**Comment by xin-lai** [comment]
@applebananamilk 第二种不会注入

**Comment by applebananamilk** [comment]
@xin-lai 那我这样使用也没有问题啊，多个导出模板对应多个ImportHeaderFilterXX，而多个ImportHeaderFilterXX需要都注入吧，不然无法从容器中获取，但是这样注入了，通过容器获取的时候使用GetService<T>不就获取最后一个注入的了吗？

**Comment by xin-lai** [comment]
目前这个注入方式确实不太完善，多次想修改，但是没有精力。
如果是全局的ImportHeaderFilter，应该支持判断Dto或者支持其他条件处理。
有时间欢迎PR。

**Comment by applebananamilk** [comment]
#384

**Comment by xin-lai** [comment]
做了点小改，如不通过特性指定类型，则使用第一个该类型的全局筛选器。
