### ISSUE TITLE
CsvImporter  导入数据时  header信息 验证bug

### ISSUE THREAD

**Issue by ByZhouhang** [dotnetcore/Magicodes.IE#393]
### Actual behaviour
DTO  导入CSV 数据时，验证Head提示信息有误

同样的DTO  使用 ExcelImporter  导入xlsx 文件是没有问题的，用 CsvImporter 导入转换后的Csv文件 头文件验证信息有误

```C#
   public class CheckViewModel
    {
        [Required(ErrorMessage = "中心编号不能为空")]
        [ImporterHeader(Name = "中心编号", AutoTrim = true)]
        public string SiteCode { get; set; } = string.Empty;


        [Required(ErrorMessage = "受试者筛选号不能为空")]
        [ImporterHeader(Name = "受试者筛选号", AutoTrim = true)]
        public string SubjectCode { get; set; } = string.Empty;

        [Required(ErrorMessage = "访视名称不能为空")]
        [ImporterHeader(Name = "访视名称", AutoTrim = true)]
        public string VisitName { get; set; } = string.Empty;

        [Required(ErrorMessage = "检查日期不能为空")]
        [CanConvertToTime(ErrorMessage = "检查日期格式有问题")]
        [ImporterHeader(Name = "检查日期", AutoTrim = true)]
        public string StudyDate { get; set; } = string.Empty;

        [Required(ErrorMessage = "Modality不能为空")]
        [ImporterHeader(Name = "检查技术", AutoTrim = true)]
        public string Modality { get; set; } = string.Empty;
}
```

![ef60ddc23a039d44a5dd3d183ae862e](https://user-images.githubusercontent.com/43258053/161935121-7db117ba-f6ec-463e-a683-09d42d566be3.png)

### I'm seeing this behaviour on

- [ x] Magicodes.IE.Csv

[2022-04-02一致性核查.csv](https://github.com/dotnetcore/Magicodes.IE/files/8425334/2022-04-02.csv)

#### package versions
 Magicodes.IE.Csv 2.6.3

**Comment by xin-lai** [comment]
麻烦上传下文件

**Comment by xin-lai** [comment]
[2022-04-02.csv](https://github.com/dotnetcore/Magicodes.IE/files/8427072/2022-04-02.csv)
改成UTF-8解决了此问题

**Comment by xin-lai** [comment]
@ByZhouhang 关于ASCII编码，可能需要你将CSV文件另存为UTF-8或者进行文件编码转换后再导入，这块目前没合适的处理方式。
