### ISSUE TITLE
导入模板生成列宽度，设置导出宽度的时候不生效

### ISSUE THREAD

**Issue by ChengXiMei** [dotnetcore/Magicodes.IE#399]
- [ ] Magicodes.IE.Excel
导入模板应该如何设置列宽度，系统是否支持
![image](https://user-images.githubusercontent.com/104045077/164132030-ec19161d-1ba5-44a8-a8f1-34d4a4c4d5ed.png)

**Comment by hueifeng** [comment]
在Excel导出时，可以通过`ExporterHeaderAttribute`特性的Width属性设置宽度，这个是没问题的

**Comment by hueifeng** [comment]
长时间未响应，暂时关闭这个问题
