### ISSUE TITLE
导入标注问题

### ISSUE THREAD

**Issue by kasugaharu** [dotnetcore/Magicodes.IE#40]
如果当前Excel上传模板上的某一个单元格有一个标注,再次在相同的单元格上写标注就会报错
![image](https://user-images.githubusercontent.com/15976040/75085818-0231cf80-5568-11ea-8288-e4aa60e2e8a4.png)

需要处理这种情况吗?

**Comment by xin-lai** [comment]
就是同一个单元格只能存在一个批注？
需要处理。

**Comment by kasugaharu** [comment]
已处理
之后 我本地项目 通过验证之后 我会再发一个PR过来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "李文强"<notifications@github.com&gt;; 
发送时间: 2020年2月22日(星期六) 下午2:54
收件人: "dotnetcore/Magicodes.IE"<Magicodes.IE@noreply.github.com&gt;; 
抄送: "透"<671118155@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dotnetcore/Magicodes.IE] 导入标注问题 (#40)




就是同一个单元格只能存在一个批注？
 需要处理。

**Comment by xin-lai** [comment]
ok

**Comment by xin-lai** [comment]
已经合并PR。

**Comment by kasugaharu** [comment]
感谢 另外我还新增了 另外一个使用导入数据 返回自定义错误标注的方法&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 李文强 <notifications@github.com&gt;
发送时间: 2020年2月22日 22:02
收件人: dotnetcore/Magicodes.IE <Magicodes.IE@noreply.github.com&gt;
抄送: kasugaharu <671118155@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dotnetcore/Magicodes.IE] 导入标注问题 (#40)




已经合并PR。

**Comment by xin-lai** [comment]
OK。

**Comment by xin-lai** [comment]
我想将 SheetDescription  改为 ImportDescription 。方便的话，通过我的公众号 麦扣聊技术 加下微信，我们晚些沟通下。

**Comment by kasugaharu** [comment]
我觉得 没什么问题 这个 字段名称 我考虑到 一个模型针对一个Sheet 才这么命名的另外 多sheet导入 这个测试 我不太清楚是不是正常的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "李文强"<notifications@github.com&gt;; 
发送时间: 2020年2月22日(星期六) 晚上10:25
收件人: "dotnetcore/Magicodes.IE"<Magicodes.IE@noreply.github.com&gt;; 
抄送: "透"<671118155@qq.com&gt;; "Assign"<assign@noreply.github.com&gt;; 
主题: Re: [dotnetcore/Magicodes.IE] 导入标注问题 (#40)




我想将 SheetDescription  改为 ImportDescription 。方便的话，通过我的公众号 麦扣聊技术 加下微信，我们晚些沟通下。

**Comment by xin-lai** [comment]
目前我正在进一步完善单元测试。我来验证下。

**Comment by kasugaharu** [comment]
好的 我微信加你了
可以微信联系




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "李文强"<notifications@github.com&gt;; 
发送时间: 2020年2月22日(星期六) 晚上10:29
收件人: "dotnetcore/Magicodes.IE"<Magicodes.IE@noreply.github.com&gt;; 
抄送: "透"<671118155@qq.com&gt;; "Assign"<assign@noreply.github.com&gt;; 
主题: Re: [dotnetcore/Magicodes.IE] 导入标注问题 (#40)




目前我正在进一步完善单元测试。我来验证下。
