### ISSUE TITLE
导出pdf图片无法显示

### ISSUE THREAD

**Issue by wuyajungo** [dotnetcore/Magicodes.IE#406]
在导出pdf时，html模板中携带的 图片<img src="logo.png" width="290" height="50"/>无法显示。
请问是不支持pdf中携带图片还是我没搞清楚方法，
怎么能在生成的pdf中显示图片？

**Comment by hueifeng** [comment]
是这样的，图片可以显示，但你要设置为绝对路径，在生成PDF的时候一定要让他访问到。
当然你可以选择设置在线地址http://xxx/test.png，或者转换为base64格式显示。
