### ISSUE TITLE
  Export Pdf TypeLoadException: Could not load type 'Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine'

### ISSUE THREAD

**Issue by hueifeng** [dotnetcore/Magicodes.IE#43]
**An unhandled exception occurred while processing the request.**

TypeLoadException: Could not load type 'Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine' from assembly 'Microsoft.AspNetCore.Razor.Language, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
RazorEngine.Compilation.CompilerServiceBase.GetGeneratorResult(IEnumerable<string> namespaces, TypeContext context)

**Comment by hueifeng** [comment]
please try run 

``` Uninstall-Package Microsoft.VisualStudio.Web.CodeGeneration.Design ```

**Comment by Aviw13** [comment]
If you're using .NET Framework, downgrade the package to the version 2.3.0. This is the latest possible version which has the necessary class
