### ISSUE TITLE
后续对.net7的支持会移除 System.Drawing.Common/libgdiplus的依赖吗

### ISSUE THREAD

**Issue by choby** [dotnetcore/Magicodes.IE#440]
经过测试发现Magicodes.IE依赖了System.Drawing.Common的图形接口, 所以在linux环境下需要依赖libgdiplus库, 但是微软官方表示在.net7中, 会移除System.Drawing.EnableUnixSupport相关的api, 这也就导致了在linux下可能无法再显示的依赖libgdiplus库了,详见: [https://docs.microsoft.com/zh-cn/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only](https://docs.microsoft.com/zh-cn/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only), 所以请问一下贵团队对.net后续的变化会同步更改库来支持吗?

**Comment by xl-wenqiang** [comment]
一直在考虑，前段时间做过尝试，发现迁移的工作极大。
