### ISSUE TITLE
动态数据源是否可以导出到多个sheet

### ISSUE THREAD

**Issue by answerforever** [dotnetcore/Magicodes.IE#449]
问题描述:
我需要将多个动态的数据源导出到多个相应的sheet中,数据源定义成Dictionary,然后使用append导出到多个sheet,代码如下(dataList1和dataList2是Dictionary集合):

`var result1 = await exporter.Append<ExpandoObject>(dataList1, "SHEET1")
                .SeparateBySheet().Append<ExpandoObject>(dataList2, "SHEET2")
             .ExportAppendDataAsByteArray();`

执行后报错如下:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/35658951/197150941-5f9e70f0-9a9a-4f99-8f52-6fffcb5d749b.png">
是不是动态数据源不支持多sheet的导出,有没有其他方法可行

**Comment by xl-wenqiang** [comment]
时间有点久，我也忘的差不多了。有空的话，麻烦提供一下Demo，以便我这边确认和编写单元测试。

**Comment by XingLiLi06** [comment]
![image](https://user-images.githubusercontent.com/34709557/197486322-f56a3805-44cf-42d8-925f-51c208c7b40a.png)
这里少句话

**Comment by XingLiLi06** [comment]
问题原因 及修复
<img width="838" alt="df336ce419184ae785895e6db5523ff" src="https://user-images.githubusercontent.com/34709557/197666860-d14afaa7-204f-4a33-91a6-54f3109cc5ca.png">

**Comment by answerforever** [comment]
> 问题原因 及修复 <img alt="df336ce419184ae785895e6db5523ff" width="838" src="https://user-images.githubusercontent.com/34709557/197666860-d14afaa7-204f-4a33-91a6-54f3109cc5ca.png">

感谢,加上IsExpandoObjectType赋值后确实可行,动态数据源加多sheet的导出可以了 @xl-wenqiang 大佬看下,是不是源码里构造函数需要加上IsExpandoObjectType赋值

**Comment by xl-wenqiang** [comment]
收到，我这周抽时间看看。最好提供一下Demo或者单元测试，基本上都是碎片时间，没那么多时间梳理代码，必须得靠单元测试来验证。

**Comment by xl-wenqiang** [comment]
@answerforever 非常感谢，已修复！
