### ISSUE TITLE
与EPPlus的版本兼容性问题

### ISSUE THREAD

**Issue by Sheldon-NULL** [dotnetcore/Magicodes.IE#457]
### Expected behaviour
在项目中，以前的同事使用的EPPlus版本是6.0.8.0，nuget上Magicides的版本应该也就是2.69，其内置的EPPlus版本是2.6.9.0,两个无法兼容。再我把它们分别用不同的类库引用的时候，使用一些特性的时候，又会出现无法正确引用的问题。

![image](https://user-images.githubusercontent.com/83170675/198946888-6602a8c7-f146-4aef-b511-3acc85ca16d3.png)

![image](https://user-images.githubusercontent.com/83170675/198946924-b8b5c8d0-7bfa-4aed-b9ee-300c47fbc814.png)

Example: Magicodes.IE.Excel.AspNetCore  2.6.9.0,

**Comment by Sheldon-NULL** [comment]
对于Issues186的解决方案，似乎智能提示并不能帮助找到命名空间

**Comment by xl-wenqiang** [comment]
只能二选一了，因为我们这边的EPPLUS是我们基于开源代码修改过的版本，而不是原本的EPPLUS
