### ISSUE TITLE
网络流导入会报错Specified method is not supported.

### ISSUE THREAD

**Issue by sampsonye** [dotnetcore/Magicodes.IE#465]
### Expected behaviour
使用HttpClient.GetStreamAsync拉取网络流格式的Excel，Import失败

### Actual behaviour
```
Specified method is not supported.
   在 System.Net.Http.HttpBaseStream.get_Length()
   在 OfficeOpenXml.ExcelPackage..ctor(Stream newStream)
   在 Magicodes.ExporterAndImporter.Excel.Utility.ImportHelper`1.Import(String filePath, Func`2 importResultCallback)
```

### I'm seeing this behaviour on
_Remove this hint: these checkboxes can be checked like this: [x]_

- [x] Magicodes.IE.Excel
- [ ] Magicodes.IE.Pdf
- [ ] Magicodes.IE.Word
- [ ] Magicodes.IE.Csv
- [ ] Magicodes.IE.Html
- [ ] Magicodes.IE.AspNetCore

#### package versions
`<PackageReference Include="Magicodes.IE.Excel" Version="2.7.0" />`

### So how can we reproduce this?
```csharp
var client = factory.CreateClient();
using var stream = await client.GetStreamAsync("https://someexcel.address", HttpContext.RequestAborted);
var importer = new ExcelImporter();
var result = await importer.Import<CustomCommodityImportModel>(stream);
Console.WriteLine(result.Exception)
```

**Comment by hueifeng** [comment]
@sampsonye Hi, you need to modify it.
```
MemoryStream memoryStream = new MemoryStream();
await stream.CopyToAsync(destination: memoryStream);
var result = await importer.Import<CustomCommodityImportModel>(memoryStream);
```
