### ISSUE TITLE
当前导出PDF的时候，能否实现使用自定义字体？

### ISSUE THREAD

**Issue by HouHaiqiang** [dotnetcore/Magicodes.IE#473]
当前导出PDF的时候，能否实现使用自定义字体？

**Comment by xl-wenqiang** [comment]
如果在Linux下，需要引入字体文件，并在导出的Html中指定相应字体。

**Comment by HouHaiqiang** [comment]
> 

感谢回复，在windows下使用，引入字体文件报 找不到font 是因为 @font-face 需要转义@ 写作 @("@")font-face   
url引用本地字体文件例如 file:///C:/Fonts/fontfile.otf 即可
