### ISSUE TITLE
字段排序属性ColumnIndex 失效

### ISSUE THREAD

**Issue by boboyunz** [dotnetcore/Magicodes.IE#477]
### Expected behaviour
字段排序功能部分失效，见下图
![image](https://user-images.githubusercontent.com/45583988/210486956-a27a125b-9eae-4bd8-91a4-b1b4674c9816.png)
当前版本：
Example: Magicodes.IE.Excel 2.7.4.1

**Comment by xl-wenqiang** [comment]
目前列排序可能需要重构。目前排序的逻辑下，后面的序号可能会影响前面的列排序。
