### ISSUE TITLE
Excel表的导入

### ISSUE THREAD

**Issue by Sheldon-NULL** [dotnetcore/Magicodes.IE#478]
请问当前针对Excel表的导入，是只支持文件路径的形式吗？希望能有对IfromFile或者字节流的支持

**Comment by Sheldon-NULL** [comment]
嗯，在重载中发现了对stream的支持，但官网教程没有更新这个？

**Comment by xl-wenqiang** [comment]
抱歉，官方教程没有提供。如果可以的话，能否麻烦您分享一下这块的文档。

**Comment by Sheldon-NULL** [comment]
核心方法代码如下：
           IImporter importer = new ExcelImporter();

            using MemoryStream ms = new MemoryStream();
            
            await file.CopyToAsync(ms);

            var import = await importer.Import<T>(ms);
