### ISSUE TITLE
Asp.net core 3.1 WebAPI 调用 PdfExporter 报错

### ISSUE THREAD

**Issue by arcchen** [dotnetcore/Magicodes.IE#48]
具体错误如下：
Could not load type 'Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine' from assembly 'Microsoft.AspNetCore.Razor.Language, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'."
按提示 添加 Microsoft.AspNetCore.Razor.Language.RazorTemplateEngine 更新引用到3.1.2.0 也报错，不明白了！
但是.net core 3.1的测试项目确可以运行
感谢

**Comment by hueifeng** [comment]
Hi,please check #43

**Comment by arcchen** [comment]
Thanks!
