### ISSUE TITLE
对.NET版本有要求不？

### ISSUE THREAD

**Issue by kergee** [dotnetcore/Magicodes.IE#49]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		无法安装程序包“Magicodes.IE.Excel 2.1.2”。你正在尝试将此程序包安装到目标为“.NETFramework,Version=v4.5”的项目中，但该程序包不包含任何与该框架兼容的程序集引用或内容文件。有关详细信息，请联系程序包作者。

**Comment by kergee** [comment]
安装NPOI 2.4.1没有报错

**Comment by xin-lai** [comment]
最低支持.NET461，不支持.NET451。。。

**Comment by xin-lai** [comment]
如果有需求，我们可以考虑支持。

**Comment by kergee** [comment]
暂时没有特别的需求，多谢。
