### ISSUE TITLE
Magicodes.ExporterAndImporter.Excel.ExportByTemplate 模板导出 能支持dynamic 类型吗

### ISSUE THREAD

**Issue by 1542793315** [dotnetcore/Magicodes.IE#496]
![image](https://user-images.githubusercontent.com/48785885/228165171-defac7b9-fbc8-4ff0-9d90-859b6b06c7de.png)
new ExcelExporter().ExportByTemplate(destinationFilePath, templateData, templateFilePath);
调用后就报错了  ，但是自己手动能获取到值的
![image](https://user-images.githubusercontent.com/48785885/228165114-523b3b44-59c9-43eb-9951-294ecf0ca985.png)

**Comment by wlclass** [comment]
你这不是dynamic类型,只是一个匿名对象.

**Comment by 1542793315** [comment]
好的，我指定dynamic不用匿名对象已可以使用
