### ISSUE TITLE
excel导出可以支持追加表格的情景么

### ISSUE THREAD

**Issue by ccccccmd** [dotnetcore/Magicodes.IE#50]
读取包含1，2月数据的2个sheet的表格，然后再后面追加3月的表格，导出1，2，3月数据3个sheet的新表格

**Comment by xin-lai** [comment]
描述的业务有点笼统啊。我们这个是一个工具组件，尽可能会实现一些通用的场景。您这个需求，换个说法是否可以这么解释：

- 支持多个Dto导出多个Sheet
- 支持一个Dto导出多个Sheet
- 支持多个Sheet导入

**Comment by ccccccmd** [comment]
我再描述下：我有个月度报表，里面有4个sheet，分别是每个周的周度统计，4周4个sheet。
每周日开始动态生成本周的，生成一个sheet，追加到上一周的的sheet后面。
生成一周的数据报表很费时间，不想重复生成本月前几周的，希望直接读取上周生成好的excel，再其后追加本周的数据sheet，得到新的表格。

**Comment by xin-lai** [comment]
业务这块我明白，但是从IE的设计理念出发，我们得考虑清楚如何设计才能更符合通用的场景。

**Comment by xin-lai** [comment]
如果可以，这块我们可以一起来。欢迎PR。

**Comment by ccccccmd** [comment]
嗯，明白了，谢谢，😀

**Comment by xin-lai** [comment]
@ccccccmd 非常感谢！
