### ISSUE TITLE
Excel模板导出多个数据表导出时会填充错位，并且有些表数据会不展示

### ISSUE THREAD

**Issue by RuiyanLiu** [dotnetcore/Magicodes.IE#51]
[ConsoleApp1.zip](https://github.com/dotnetcore/Magicodes.IE/files/4336755/ConsoleApp1.zip)

excel模板导出：当需要导出多个表的数据时，数据条数多了就会出现填充的位置错位，甚至有些表的数据会导不全，不同数据行的格式也会出现错乱。

**Comment by xin-lai** [comment]
方便的话，麻烦测试下2.1.4的包，之前这个包没有推成功，今天才发现：
`Install-Package Magicodes.IE.Excel -Version 2.1.4`

**Comment by xin-lai** [comment]
请使用最新的包进行测试，如还出现此问题，我们再打开这个Issue。

**Comment by RuiyanLiu** [comment]
![image](https://user-images.githubusercontent.com/16285387/77714237-74884a80-7013-11ea-91ed-041620b5f15a.png)

[ConsoleApp2.1.4.zip](https://github.com/dotnetcore/Magicodes.IE/files/4391078/ConsoleApp2.1.4.zip)


还是有之前的这个情况，如图 模板与实际导出来的excel相差很大

**Comment by xin-lai** [comment]
@hueifeng 麻烦有空跟进下。

**Comment by hueifeng** [comment]
Ok I will test it.
