### ISSUE TITLE
Importer 能否加一个去除前后空格的判断

### ISSUE THREAD

**Issue by yangliadmin** [dotnetcore/Magicodes.IE#516]
Importer 能否加一个去除前后空格的判断？

**Comment by hueifeng** [comment]
对表头的处理吗？可以看下拦截器这边是否可满足需求

**Comment by yangliadmin** [comment]
表格内容

**Comment by hueifeng** [comment]
根据目前的描述来看结果的话可以在Excel中读取到后进行处理，具体的场景及需求可以详细描述下，我们也好考虑如何做到支持。

**Comment by yangliadmin** [comment]
这个目前看起来就是我想要的，nice
    [ImporterHeader(AutoTrim = true)]
