### ISSUE TITLE
.NETFramework,Version=v4.7.2 "Install-Package Magicodes.IE.Excel" 提示“Install-Package : 找不到与 'Magicodes.IE.EPPlus 2.7.4.5 约束

### ISSUE THREAD

**Issue by rickeygong** [dotnetcore/Magicodes.IE#521]
`Install-Package Magicodes.IE.Excel`提示“Install-Package : 找不到与 'Magicodes.IE.EPPlus 2.7.4.5 约束: Collections.Pooled (>= 2.0.0-preview.27)' 兼容的“Collections.Pooled”版本。”，这个怎么处理啊（“.NETFramework,Version=v4.7.2”的项目）？
![image](https://github.com/dotnetcore/Magicodes.IE/assets/51323554/7d920d4c-cd27-45a2-a3e0-d9234cfb65cd)

**Comment by WinChance** [comment]
要先安装Collections.Pooled！去nuget找最新版安装。
