### ISSUE TITLE
多sheet 动态导入 并且动态sheetName和动态sheet个数的导入的实现

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/Magicodes.IE#524]
现有的 多Sheet导入 不太灵活 动态sheetName和动态sheet个数导入时候比较麻烦
不知道是否有更方便的方法 实现，或者后续是否考虑更灵活的导入方式

**Comment by lhtuling** [comment]
在使用ImportSameSheets导入时候使用SheetIndex导入会报错，
···
    public class ImportMainProductDto
    {

        [ExcelImporter(SheetIndex = 0)]
        public MainProduct MainProduct1 { get; set; }

        [ExcelImporter(SheetIndex = 1)]
        public MainProduct MainProduct2 { get; set; }

    }
···
![image](https://github.com/dotnetcore/Magicodes.IE/assets/44140500/756dae85-0fb0-4250-a513-642e94f814ad)

**Comment by WinChance** [comment]
我也遇到同样的需求，后面只能https://github.com/eraydin/EPPlus.Core.Extensions的ToList，动态指定返回类型来解决了。我水平不够，本来想通过动态构建ImportDto来解决，但是后面时间紧迫放弃了。
`            using (ExcelPackage package = new ExcelPackage(existingFile))
            {
                ExcelWorkbook excelWorkbook = package.Workbook;
                for (var i = 1; i < excelWorkbook.Worksheets.Count + 1; i++)
                {
                    if (1 == i)
                    {
                        shippingInformationImportDTOs = package.GetWorksheet(i).ToList<ShippingInformationDTO>();
                    }
                    else
                    {
                        string worksheetName = excelWorkbook.Worksheets[i].Name;
                        List<ShippingInformationDtlDTO> shippingInformationDtlDTOs = package.GetWorksheet(i).ToList<ShippingInformationDtlDTO>();
                    }
                }
            }`
