### ISSUE TITLE
wps 编辑后execl导入报错 The given key 'rId1' was not present in the dictionary

### ISSUE THREAD

**Issue by HeHoney** [dotnetcore/Magicodes.IE#543]
execl 导入是数据存在想邮箱之类的数据，用wps 编辑过后，导入就会报这个错误， The given key 'rId1' was not present in the dictionary  
如果用微软的重新另存为一个文件又不会出现这个错误

**Comment by HeHoney** [comment]
[派送计划模板(1).xlsx](https://github.com/dotnetcore/Magicodes.IE/files/13622515/1.xlsx)
这是报错的文件

**Comment by txbauo** [comment]
你把超链接那一列设置取消超链接就可以导入了

**Comment by txbauo** [comment]
我调试了源代码,超链接单元格只要有值是一样就会出现这个异常.
 在ExcelWorksheet这个代码文件1183行能获取到两个一样的rid

**Comment by huguodong** [comment]
还真是，只能取消超链接吗
