### ISSUE TITLE
一个DTO中有多个字段，如何选择让某些个字段不导出

### ISSUE THREAD

**Issue by AjuPrince** [dotnetcore/Magicodes.IE#55]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AjuPrince** [comment]
[ExcelExporter(Name = "学生信息", TableStyle = "Light20", AutoFitAllColumn = true)]
    public class Person
    {
        [ExporterHeader(DisplayName = "姓名")]
        public string Name { get; set; }
        [ExporterHeader(DisplayName = "年龄", Format = "#,##0")]
        public int Age { get; set; }
        [ExporterHeader(DisplayName = "出生日期", Format = "yyyy-mm-DD")]
        public DateTime? Birthday { get; set; }
        public string Remark { get; set; }
    }

比如说，我让 Person类中的Remark不导出，这个该如何控制呢？

**Comment by hueifeng** [comment]
Hi,Can Use ExporterHeaderAttribute  **IsIgnore** 
 https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/2.%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B%E4%B9%8B%E5%AF%BC%E5%87%BAExcel.md

**Comment by AjuPrince** [comment]
thank you！
