### ISSUE TITLE
在导出Excel时如何自定义复杂表头？

### ISSUE THREAD

**Issue by AjuPrince** [dotnetcore/Magicodes.IE#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hueifeng** [comment]
Maybe this can help you 
https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/7.Excel%E6%A8%A1%E6%9D%BF%E5%AF%BC%E5%87%BA%E4%B9%8B%E5%AF%BC%E5%87%BA%E6%95%99%E6%9D%90%E8%AE%A2%E8%B4%AD%E8%A1%A8.md

**Comment by xin-lai** [comment]
复杂表头推荐使用模板导出。

**Comment by AjuPrince** [comment]
thank you
