### ISSUE TITLE
Reminder:Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream(System.String)'.

### ISSUE THREAD

**Issue by Xugg-1999** [dotnetcore/Magicodes.IE#560]
### Expected behaviour
After the Npoi version is upgraded, "Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream(System.String)'." is displayed,
After the Npoi package is degraded, the export function can be used normally.

**Comment by LingDian2019** [comment]
I have the same problem, you reduced the package to that version, I use is.  Net 8
