### ISSUE TITLE
表头问题

### ISSUE THREAD

**Issue by AjuPrince** [dotnetcore/Magicodes.IE#58]
目前导出Excel时，会自动加入筛选功能
问题1、如何取消这个自动筛选功能
问题2、既然有了筛选功能，那为啥只支持10行呢？

我想要的解决方案是
筛选功能 需要我自己设置（可以加入到 ExporterAttribute 这个特性中 ）
筛选行数也支持自己定义

**Comment by xin-lai** [comment]
@AjuPrince 筛选行数指的是？

**Comment by AjuPrince** [comment]
我所指的筛选
![image](https://user-images.githubusercontent.com/16829343/77020979-68234280-69c0-11ea-8e8d-3212c87621e8.png)

**Comment by AjuPrince** [comment]
筛选行数，以上图的A列为例，
行数就是从A1到A10 只有这10行，也就是说筛选的行数默认是A列下的10行。这个能否支持自定义，
还有列头（A【name】、B【年龄】、C【Remarks】、D【出生日期】）的筛选功能也支持自定义不？好像目前没有找到自定义的特性。

**Comment by xin-lai** [comment]
之前是没有启用Excel表格筛选的，我们特地完成这个功能的。。。
见：[#17 ](https://github.com/dotnetcore/Magicodes.IE/issues/17)

**Comment by AjuPrince** [comment]
因有的需要有的不需要，所以能否有个 特性 来开启 ，而且这个帅选行数为何只是10行呢？能否全选呢？

**Comment by AjuPrince** [comment]
我看 
https://github.com/dotnetcore/Magicodes.IE/issues/46 
这个讨论里 Superllb93  这个人 也问到了同样的问题，
希望您能考虑下这个需求。

**Comment by xin-lai** [comment]
好的，我们会考虑来处理这个功能的。
如果只能筛选10行，那么应该是Bug，晚点我验证下。

**Comment by xin-lai** [comment]
![image](https://user-images.githubusercontent.com/22255486/77039223-74bf8f00-69f0-11ea-98bc-a383f33d27e2.png)
 没有问题啊。
见单元测试：AttrsExport_Test 的结果

**Comment by AjuPrince** [comment]
我在测试下，谢谢您的解答，还有一个问题 和  https://github.com/dotnetcore/Magicodes.IE/issues/54 
上报的bug一样

**Comment by xin-lai** [comment]
@AjuPrince 那个问题出在EPPlus底层，这个需要我们抽精力替换底层之后才能解决

**Comment by xin-lai** [comment]
2020.03.25
【Nuget】版本更新到2.2.0-beta3
【Excel导入】修复日期问题 #68
【Excel导出】添加ExcelOutputType设置，支持输出无格式的导出。#54可以使用此方式。

@AjuPrince 配置下ExcelOutputType，类型设置为None。可以解决此问题。
