### ISSUE TITLE
Excel模板导出支持图片

### ISSUE THREAD

**Issue by tiansfather** [dotnetcore/Magicodes.IE#62]
给dto中的属性加了ExportImageField没有用
![image](https://user-images.githubusercontent.com/16606743/77221735-69529c00-6b87-11ea-89c7-734f4ce657b0.png)

**Comment by hueifeng** [comment]
Through the above code, I judge that he is correct. 
Suggested examples or can you refer to
https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/8.Excel%E5%9B%BE%E7%89%87%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA.md

**Comment by tiansfather** [comment]
示例不是基于模板的导出。
模板导出还有另一个问题是不支持表格中的单元格合并，如下图，存在行合并时，导出会报错
![image](https://user-images.githubusercontent.com/16606743/77222601-bc305180-6b8f-11ea-89ad-ea0f4af6508d.png)
![image](https://user-images.githubusercontent.com/16606743/77222611-cf432180-6b8f-11ea-9aaa-2ff8ed800e04.png)

**Comment by hueifeng** [comment]
Exporting images with templates is not supported at this time, we will process them, and welcome to submit PR
现在不支持图片导出到模板，我们会进行处理的，同时也欢迎向我们提交PR

**Comment by xin-lai** [comment]
这个功能即将发布。支持合并的单元格我们开了个新的Issue  #72

**Comment by xin-lai** [comment]
已发布2.2.0-beta8，支持以下渲染语法：
```
{{Image::ImageUrl?Width=50&Height=120&Alt=404}}
{{Image::ImageUrl?w=50&h=120&Alt=404}}
{{Image::ImageUrl?Alt=404}}
```
