### ISSUE TITLE
ASP.NET Core Web API导入excel希望能提供接口（或者校验数据接口）

### ISSUE THREAD

**Issue by SmartforXiaoYuan** [dotnetcore/Magicodes.IE#65]
目前在导入excel基于文件夹的方式，校验在helper中，现在我只能自己写校验转到dto，希望可以把校验单独提供接口。或者提供web api的导入excel转dto接口。

**Comment by xin-lai** [comment]
这块在2.2这个版本有精力会优先考虑。参考 #64 
目前由于精力原因，此块暂未开始。

**Comment by hueifeng** [comment]
You can install this package.
```
Install-Package Magicodes.IE.AspNetCore
```
