### ISSUE TITLE
nuget 安装Magicodes.IE.Excel 2.1.4，导入报错

### ISSUE THREAD

**Issue by zilo555** [dotnetcore/Magicodes.IE#67]
var import = await _importer.Import<ImportStudentDto>(fullPath, "");
import.Exception ：
Method not found: 'System.String Magicodes.ExporterAndImporter.Core.Extension.Extension.Save(System.Drawing.Image, System.String, System.Drawing.Imaging.ImageFormat)'.

clone最新的源码直接引用，没有异常，

**Comment by SmartforXiaoYuan** [comment]
我也遇到导入报错！坑爹

**Comment by hueifeng** [comment]
You can upgrade to the preview version first.The issue has been resolved in the preview release

**Comment by SmartforXiaoYuan** [comment]
> You can upgrade to the preview version first.The issue has been resolved in the preview release

yes,preview version success
