### ISSUE TITLE
2.1.0版本，从excel导入数据，不识别日期格式

### ISSUE THREAD

**Issue by zhujinhu21** [dotnetcore/Magicodes.IE#68]
**Describe the bug**
excel中 列是日期格式，导入报错，提示“值 43914 无效，请填写正确的日期时间格式！”
**To Reproduce**

**Expected behavior**

**Screenshots**
![微信截图_20200325165247](https://user-images.githubusercontent.com/4327149/77518677-252e0700-6eb9-11ea-8acc-08a4e380676b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xin-lai** [comment]
问题已收到，正在处理。目前发现线上的单元测试是OK的，但是本地单元测试确实没有通过，原因已经找到，我们会尽快处理并发布Beta版。

**Comment by zhujinhu21** [comment]
netcore2.2的项目不能使用 Magicodes.IE.Excel 2.1.0以上的版本。nuget添加失败

**Comment by xin-lai** [comment]
试试2.2 Beta版的包

**Comment by xin-lai** [comment]
刚试过2.1.4版本没有问题。

**Comment by zhujinhu21** [comment]
netcore2.2 不能使用2.1.4以上的包，我引用下载的源码编

**Comment by xin-lai** [comment]
是Beta版的不支持么？.net core 2.2我试过用2.1.4可以啊。

**Comment by zhujinhu21** [comment]
我是webapi项目 ,目标框架 netcore 2.2 ,vs2017工具

PM> Install-Package Magicodes.IE.Excel -Version 2.1.4
正在还原 D:\Work\isolate_user\room_user\api\cov19_api\cov19_api\cov19_api.csproj 的包...
Install-Package : NU1107: Microsoft.Extensions.Configuration 中检测到版本冲突。直接安装/引用 Microsoft.Extensions.Configuration 3.1.0 到项目 cov19_api 可解决此问题。 
 cov19_api -> Magicodes.IE.Excel 2.1.4 -> EPPlus 4.5.3.3 -> Microsoft.Extensions.Configuration.Json 3.1.0 -> Microsoft.Extensions.Configuration (>= 3.1.0) 
 cov19_api -> Microsoft.AspNetCore.App 2.2.0 -> Microsoft.Extensions.Configuration (>= 2.2.0 && < 2.3.0).
所在位置 行:1 字符: 1
+ Install-Package Magicodes.IE.Excel -Version 2.1.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : 程序包还原失败。正在回滚“cov19_api”的程序包更改。
所在位置 行:1 字符: 1
+ Install-Package Magicodes.IE.Excel -Version 2.1.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by zhujinhu21** [comment]
其中的WebApplication1项目不能添加Magicodes.IE.Excel 2.1.4

**Comment by xin-lai** [comment]
收到。

**Comment by xin-lai** [comment]
这是EPPlus的坑，已解决：
```powershell
Install-Package Magicodes.IE.Excel -Version 2.2.0-beta5
```

**Comment by zhujinhu21** [comment]
用2.2.0-beta5导入报错

System.Drawing.Common 要用System.Drawing.Common (>= 4.6.0-preview6.19303.8)的包才行，4.7.0包找不到dll
[ConsoleApp5.zip](https://github.com/dotnetcore/Magicodes.IE/files/4391251/ConsoleApp5.zip)

**Comment by xin-lai** [comment]
收到。我们试试能否解决。这个是EPPlus的坑。。。

**Comment by xin-lai** [comment]
https://www.nuget.org/packages/Magicodes.IE.Excel/2.2.0-beta6
好了，请使用 2.2.0-beta6

**Comment by xin-lai** [comment]
`Install-Package Magicodes.IE.Excel -Version 2.2.0-beta6`

**Comment by zhujinhu21** [comment]
ok，谢谢
