### ISSUE TITLE
导入的错误标注文件支持仅输出验证未通过的数据

### ISSUE THREAD

**Issue by zilo555** [dotnetcore/Magicodes.IE#70]
假设我导入的记录中，有两条记录不正确，客户在下载导入失败的文件，只需要看这两行错误的数据就可以了，而不需要把所有的记录都呈现出来。比如下图，只留着前两行，其他的就不需要了
![image](https://user-images.githubusercontent.com/16952789/77873639-24142580-727d-11ea-9820-64c102045637.png)

**Comment by xin-lai** [comment]
已收到，下个版本规划我们可以优先考虑这个需求。

**Comment by zilo555** [comment]
@xin-lai 下个版本什么时候上线😄
本来想自己改改，打算在LabelingBussinessError重新将错误记录保存一下，可是不知道怎么取出记录。。。只能找到index 也不知道怎么用😂，放弃了。。。

**Comment by xin-lai** [comment]
下个版本2.3可能得5月份了。晚点我有空了看看，如果实现简单的话，我们当前版本就加入好了。

**Comment by liuzilong312** [comment]
请问  这个功能现在有了吗
