### ISSUE TITLE
含有图片的列导出有错误

### ISSUE THREAD

**Issue by xinzhyu** [dotnetcore/Magicodes.IE#71]
1.图片列的列宽是之前URL地址的长度,渲染为图片后,宽度依旧很宽
建议
![image](https://user-images.githubusercontent.com/2132993/78001644-957cd280-7368-11ea-99bf-5b1cbd900fe7.png)
` //图片表头重新指定宽度
            if (ExporterHeaderList.Any(p => p.ExportImageFieldAttribute != null))
            {
                ExporterHeaderList.Where(p => p.ExportImageFieldAttribute != null).ToList().ForEach(c =>
                {
                    CurrentExcelWorksheet.Column(c.Index).Width = c.ExportImageFieldAttribute.Width/4;
                });
            }`

2.图片列的图片会错位,建议位置和大小重新计算一下
![image](https://user-images.githubusercontent.com/2132993/78001754-bfce9000-7368-11ea-912a-1f5a4ae1985f.png)

**Comment by xinzhyu** [comment]
`        /// <summary>
        ///     添加图片
        /// </summary>
        protected void AddPictures(int rowCount)
        {
            for (var i = 0; i < ExporterHeaderList.Count; i++)
            {
                if (ExporterHeaderList[i].ExportImageFieldAttribute != null)
                {
                    for (var j = 1; j <= rowCount; j++)
                    {
                        var cell = CurrentExcelWorksheet.Cells[j + 1, i + 1];
                        var url = cell.Text;
                        if (File.Exists(url) || url.StartsWith("http", StringComparison.OrdinalIgnoreCase))
                        {
                            try
                            {
                                cell.Value = string.Empty;
                                var bitmap = Extension.GetBitmapByUrl(url);
                                if (bitmap == null)
                                {
                                    cell.Value = ExporterHeaderList[i].ExportImageFieldAttribute.Alt;
                                }
                                else
                                {
                                    var pic = CurrentExcelWorksheet.Drawings.AddPicture(Guid.NewGuid().ToString(), bitmap);
                                    
                                    //pic.SetPosition(j, ExporterHeaderList[i].ExportImageFieldAttribute.Height / 5, i - 1, 0);
                                    pic.SetPosition(j, 0, i - 1, 100);

                                    CurrentExcelWorksheet.Row(j + 1).Height = ExporterHeaderList[i].ExportImageFieldAttribute.Height;

                                    //pic.SetSize(ExporterHeaderList[i].ExportImageFieldAttribute.Width * 7, ExporterHeaderList[i].ExportImageFieldAttribute.Height);
                                    pic.SetSize(ExporterHeaderList[i].ExportImageFieldAttribute.Width, ExporterHeaderList[i].ExportImageFieldAttribute.Height);
                                }

                            }
                            catch (Exception)
                            {
                                cell.Value = ExporterHeaderList[i].ExportImageFieldAttribute.Alt;
                            }
                        }
                        else
                        {
                            cell.Value = ExporterHeaderList[i].ExportImageFieldAttribute.Alt;
                        }
                    }
                }
                //else
                //{
                //    for (var j = 1; j <= rowCount; j++)
                //    {
                //        CurrentExcelWorksheet.Cells[j + 1, i + 1].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;//水平居中
                //        CurrentExcelWorksheet.Cells[j + 1, i + 1].Style.VerticalAlignment = ExcelVerticalAlignment.Center;//垂直居中
                //    }
                //}
            }
        }
`

**Comment by xinzhyu** [comment]
`        /// <summary>
        /// 添加表头、样式以及忽略列、格式处理
        /// </summary>
        /// <returns></returns>
        private ExcelPackage AddHeaderAndStyles()
        {
            AddHeader();

            if (ExcelExporterSettings.AutoFitAllColumn)
            {
                CurrentExcelWorksheet.Cells[CurrentExcelWorksheet.Dimension.Address].AutoFitColumns();
            }

            AddStyle();
            DeleteIgnoreColumns();
            //以便支持导出多Sheet
            SheetIndex++;

            //图片表头重新指定宽度
            if (ExporterHeaderList.Any(p => p.ExportImageFieldAttribute != null))
            {
                ExporterHeaderList.Where(p => p.ExportImageFieldAttribute != null).ToList().ForEach(c =>
                {
                    CurrentExcelWorksheet.Column(c.Index).Width = c.ExportImageFieldAttribute.Width/4;
                });
            }

            return CurrentExcelPackage;
        }`

**Comment by xin-lai** [comment]
可以上传附件的，代码建议直接上传附件。
