### ISSUE TITLE
请问如何配置输出只有一列的EXCEL表格？

### ISSUE THREAD

**Issue by drj18** [dotnetcore/Magicodes.IE#73]
只有一列表格的模板配置，就是只有这一列 {{Table>>ddgs|dggg}}，后面没有列，如何配置，当然还有其它一些表及字段。

**Comment by hueifeng** [comment]
According to the problem description I guess you want to ask how to ignore other properties.

**ExporterHeaderAttribute**
DisplayName： 显示名称
FontSize： 字体大小
IsBold： 是否加粗
Format： 格式化
IsAutoFit： 是否自适应
IsIgnore： 是否忽略

**Comment by drj18** [comment]
只有一列表格的模板配置，就是只有这一列 {{Table>>ddgs|dggg}}，后面没有列，如何配置

**Comment by xin-lai** [comment]
@drj18 这确实是一个问题。我们考虑下如何支持。

**Comment by xin-lai** [comment]
如果只存在一列，仅需设置：
`{{Table>>model | field}}`
目前我们还需要对此进行测试，由于精力原因，欢迎PR。
