### ISSUE TITLE
分栏导出，追加导出

### ISSUE THREAD

**Issue by drj18** [dotnetcore/Magicodes.IE#74]
需要导出分栏模板配置，一个表格分2栏导出，表格形式如下
序号|名称|          |序号| 名称
-----|-----|-------|-----|------
1      |名1|           |3|名称2
2|名称3|   |4|名称4

**Comment by xin-lai** [comment]
这个需求并不是很通用，欢迎PR。可以考虑结合Append方法实现。也就是Append既可追加Sheet，也可以追加到当前Sheet。
`exporter.Append(list1).Separate(1).Append(list2).ExportAppendData(filePath);`

**Comment by xin-lai** [comment]
后续可以支持以下方式：
```csharep
exporter.Append(list1).SeparateByColumn().Append(list2).ExportAppendData(filePath);
exporter.Append(list1).SeparateBySheet().Append(list2).ExportAppendData(filePath);
```

**Comment by xin-lai** [comment]
#60
