### ISSUE TITLE
2.1.4 版本导入数据调用meth:Extension.Save 失败

### ISSUE THREAD

**Issue by yichuanbiao** [dotnetcore/Magicodes.IE#80]
提示Method not found: 'System.String Magicodes.ExporterAndImporter.Core.Extension.Extension.Save(System.Drawing.Image, System.String, System.Drawing.Imaging.ImageFormat)'.

**Comment by hueifeng** [comment]
#67
You can upgrade to the preview version first.The issue has been resolved in the preview release

**Comment by yichuanbiao** [comment]
ok,thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Huei Feng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午3:43
收件人:&nbsp;"dotnetcore/Magicodes.IE"<Magicodes.IE@noreply.github.com&gt;;
抄送:&nbsp;"病态"<1143494074@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnetcore/Magicodes.IE] 2.1.4 版本导入数据调用meth:Extension.Save 失败 (#80)





 
#67
 You can upgrade to the preview version first.The issue has been resolved in the preview release
