### ISSUE TITLE
模板导出->>导出后列会被拉的很长

### ISSUE THREAD

**Issue by 1542793315** [dotnetcore/Magicodes.IE#82]
模板导出->>
1.导出后列会被拉的很长
![image](https://user-images.githubusercontent.com/48785885/79538162-6085b500-80b6-11ea-8cad-75de397a6641.png)
2.在有table循环的列后面有合并单元格的情况程序会报错
![image](https://user-images.githubusercontent.com/48785885/79538296-acd0f500-80b6-11ea-89d4-8c162ee4668b.png)
3.能不能做一个重载方法，全部都是用文件路径的，当我进行多sheet处理的时候都要重新进行保存和读取，能不能重载 个的方法  模板用System.IO.Stream传入  输出也是System.IO.Stream
  
[工艺单模板.xlsx](https://github.com/dotnetcore/Magicodes.IE/files/4491285/default.xlsx)

**Comment by hueifeng** [comment]
It is recommended to provide relevant examples,Let me test it

**Comment by 1542793315** [comment]
> 建议提供相关的例子，让我测试一下

[工艺单模板.xlsx](https://github.com/dotnetcore/Magicodes.IE/files/4491286/default.xlsx)

**Comment by 1542793315** [comment]
> 建议提供相关的例子，让我测试一下

table 循环的    右侧合并单元格去掉就不会报错了

**Comment by 1542793315** [comment]
> 建议提供相关的例子，让我测试一下

请问，图片导出来的时候目前是填充单元格的，他会把整个单元格的行高和列宽变大(这个可以)， 需要多一个设置的是，当设置图片跨单元格显示的时候不拉大行高和列宽
