### ISSUE TITLE
Excel模板导出，1.不支持公式？2.不支持合并列？

### ISSUE THREAD

**Issue by yaobo-lab** [dotnetcore/Magicodes.IE#88]
Excel模板导出，
1.不支持公式；例如 Table 某列G5 合计。
2.合并列时，会出现报错。

**Comment by hueifeng** [comment]
That's great! Welcome to PR.

**Comment by hueifeng** [comment]
Formula export is currently supported, please refer to the following code snippet:
```
{{Formula::AVERAGE?params=G4:G6}}
```

> 2.合并列时，会出现报错。

This problem has not been reproduced, please add information about the problem.
