### ISSUE TITLE
调用new ExcelImporter().import()出现无法找到Save()方法错误

### ISSUE THREAD

**Issue by GeenoLiT** [dotnetcore/Magicodes.IE#89]
**Describe the bug**
>调用new ExcelImporter().import()出现:
**找不到方法:“System.String Magicodes.ExporterAndImporter.Core.Extension.Extension.Save(System.Drawing.Image, System.String, System.Drawing.Imaging.ImageFormat)”**

>系统环境=>使用的Nuget安装库:
Magicodes.IE.Core => 2.1.4
Magicodes.IE.Excel => 2.1.4

**To Reproduce**
代码:
```c#
//1. DTO实体
[ExcelImporter]
    public class ImportStudentDTO
    {
        public class StuSex
        {
            public enum IDs
            {
               Female, Male
            }
        }
        [ImporterHeader(Name = "姓名", Description = "姓名", IsAllowRepeat = false)]
        public S Name { get; set; }
        [ImporterHeader(Name = "性别", Description = "性别")]
        [ValueMapping("男","1")]
        [ValueMapping("女","0")]
        public StuSex.IDs Sex { get; set; }
        [ImporterHeader(Name = "年龄", Description = "年龄")]
        public int Age { get; set; }
    }
//2. 执行方法调用
public static async Task ImportExcel()
        {
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), 

"GenerateStudentImportTemplate_Test.xlsx");
             var result = await Importer.Import<ImportStudentDTO>(filePath);
        }
```

**结果**：
调用 ImportExcel()在获取result的时候出现:

```shell
# exception
找不到方法:“System.String Magicodes.ExporterAndImporter.Core.Extension.Extension.
Save(System.Drawing.Image, 

System.String, System.Drawing.Imaging.ImageFormat)”

# stacktrace

   at Magicodes.ExporterAndImporter.Excel.Utility.ImportHelper`1.ParseData(ExcelPackage excelPackage)
   at Magicodes.ExporterAndImporter.Excel.Utility.ImportHelper`1.Import(String filePath)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/63500846/80269904-7c0c4380-86e6-11ea-9273-c3c355080dde.png)

![image](https://user-images.githubusercontent.com/63500846/80269887-38b1d500-86e6-11ea-8174-3e1e0278cf92.png)

**Desktop (please complete the following information):**
 - OS: [e.g. win10]

**Additional context**
回滚版本到：
Magicodes.IE.Core" version="2.1.3"
Magicodes.IE.Excel" version="2.1.2"
便可以获取到数据信息
![image](https://user-images.githubusercontent.com/63500846/80269960-ec1ac980-86e6-11ea-926e-0e9522af9ae8.png)

![image](https://user-images.githubusercontent.com/63500846/80269945-db6a5380-86e6-11ea-8071-7b212935418e.png)

**Comment by hueifeng** [comment]
#67
You can upgrade to the preview version first.The issue has been resolved in the preview release

**Comment by GeenoLiT** [comment]
thks
