### ISSUE TITLE
无法在docker里面使用DinkToPdf ，应该是少了wkhtmltopdf，请问一下怎么安装

### ISSUE THREAD

**Issue by iamstephen** [dotnetcore/Magicodes.IE#92]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hueifeng** [comment]
Can you describe the issues in use in detail?

**Comment by xin-lai** [comment]
@iamstephen 
支持Docker的，你应该是没有安装字体。
You need to install fonts.
参考[在Docker中使用](docs/4.在Docker中使用.md)

**Comment by iamstephen** [comment]
> @iamstephen
> 支持Docker的，你应该是没有安装字体。
> You need to install fonts.
> 
> 请参考：
> 
> 1. **[在Docker中使用](docs/4.%E5%9C%A8Docker%E4%B8%AD%E4%BD%BF%E7%94%A8.md)**

打不开

**Comment by hueifeng** [comment]
Check this link
https://github.com/dotnetcore/Magicodes.IE/blob/master/docs/4.%E5%9C%A8Docker%E4%B8%AD%E4%BD%BF%E7%94%A8.md
