### ISSUE TITLE
.net core 2.2导入数据报错

### ISSUE THREAD

**Issue by cunzhu** [dotnetcore/Magicodes.IE#93]
您好，我在使用您的插件进行数据导入时，遇到以下错误：
Method not found: 'System.String Magicodes.ExporterAndImporter.Core.Extension.Extension.Save(System.Drawing.Image, System.String, System.Drawing.Imaging.ImageFormat)'.

更详细的错误信息是：
   at Magicodes.ExporterAndImporter.Excel.Utility.ImportHelper`1.ParseData(ExcelPackage excelPackage)
   at Magicodes.ExporterAndImporter.Excel.Utility.ImportHelper`1.Import(String filePath)
出错部分的代码：
![image](https://user-images.githubusercontent.com/50855175/81394391-7128c880-9154-11ea-9e70-083b7e0ae8a3.png)
其中上传文件是由导出模板导出后填写的数据，最后两个是int型，
![image](https://user-images.githubusercontent.com/50855175/81394590-bcdb7200-9154-11ea-97a7-304d5629fe8d.png)
模型如下
![image](https://user-images.githubusercontent.com/50855175/81394710-f7dda580-9154-11ea-9183-87664dc0c7a6.png)
一开始我没有用枚举后面用了枚举还是这个错，请这是问题，是我什么地方写错了吗，

另外导出并没有自动根据枚举的描述转换

最后，感谢您提供的插件，并在百忙之中抽空回答我的问题，谢谢

**Comment by hueifeng** [comment]
> Method not found: 'System.String Magicodes.ExporterAndImporter.Core.Extension.Extension.Save(System.Drawing.Image, System.String, System.Drawing.Imaging.ImageFormat)'.

#67
You can upgrade to the preview version first.The issue has been resolved in the preview release
