### ISSUE TITLE
support stream?

### ISSUE THREAD

**Issue by moxixuan** [dotnetcore/Magicodes.IE#96]
Hey,I try to reference it in WebApi,
In my case, it like this

```
[HttpPost]
 public async Task<IActionResult> PostImport(IFormFile upfile)
{
            using (var memoryStream = new MemoryStream())
            {
                await upfile.CopyToAsync(memoryStream).ConfigureAwait(false);
                var importer = new ExcelImporter();
                await  importer.Import<T>(memoryStream);
            }
           return ok();
}
```

I want to input stram not string path , Is there any solution?

Thanks you so much.

**Comment by hueifeng** [comment]
You could generate it into a temporary file, but that's a stupid way to do it. 
I think it's possible to add a file stream extension method. Welcome to PR.

**Comment by moxixuan** [comment]
thanks you so much, it's helpful for me.
