### ISSUE TITLE
怎么样让标题或者内容居中显示的

### ISSUE THREAD

**Issue by qcjxberin** [dotnetcore/Magicodes.IE#99]
怎么样让标题或者内容居中显示的

**Comment by hueifeng** [comment]
Centered display is currently not supported, I think this function can be added.

**Comment by qcjxberin** [comment]
目前最新提交的是标题居中还是内容居中，或者是同时都给居中了。这个能分别设置吗？

**Comment by hueifeng** [comment]
@qcjxberin 
Are you talking about setting separately for a column, or setting the title and content separately?
目前是通过设置属性全局居中，你这边是想针对于某个列单独设置，还是说只是将内容和标题分别设置？

**Comment by qcjxberin** [comment]
希望标题可设置是否居中，然后内容字段根据自己的需要针对某列居中

**Comment by hueifeng** [comment]
@qcjxberin OK, Please give me some time to think about this.
好的，我知道了，我考虑一下这个问题
